# Set Up

In [1]:
import json
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm

pd.set_option('display.max_columns', None)

In [2]:
cd ..

/Users/hyunwoo/Penn Dropbox/Hyunwoo Jung/1_Personal/_Hyunwoo Place/graduate school/2_coursework (2025-F)/2_CIS5200_Machine Learning/5_final project/3_analyses

# Load Data

## Reviews

In [16]:
list_reviews = []
with open("data/1_raw/Appliances.jsonl", 'r') as fp:
    for line in tqdm(fp):
        list_reviews.append(json.loads(line.strip()))

df_reviews = pd.DataFrame(list_reviews)

0it [00:00, ?it/s]

In [17]:
display(df_reviews.head())
display(df_reviews.tail())

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5.0,Work great,work great. use a new one every month,[],B01N0TQ0OH,B01N0TQ0OH,AGKHLEW2SOWHNMFQIJGBECAF7INQ,1519317108692,0,True
1,5.0,excellent product,Little on the thin side,[],B07DD2DMXB,B07DD37QPZ,AHWWLSPCJMALVHDDVSUGICL6RUCA,1664746863446,0,True
2,5.0,Happy customer!,"Quick delivery, fixed the issue!",[],B082W3Z9YK,B082W3Z9YK,AHZIJGKEWRTAEOZ673G5B3SNXEGQ,1607225435363,0,True
3,5.0,Amazing value,I wasn't sure whether these were worth it or n...,[],B078W2BJY8,B078W2BJY8,AFGUPTDFAWOHHL4LZDV27ERDNOYQ,1534104184306,0,True
4,5.0,Dryer parts,Easy to install got the product expected to re...,[],B08C9LPCQV,B08C9LPCQV,AELFJFAXQERUSMTXJQ6SYFFRDWMA,1620176603754,0,True

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
2128600,5.0,Accurate description,As described,[],B097948QRP,B097948QRP,AG6IN4MOTWF3743PKIPHYA2S7GXA,1627918432936,0,True
2128601,3.0,Not compatible with Nespresso U Machine,I have tried multiple times with different reu...,[],B072QVZYDD,B0C6XG2JSG,AHVKX5FONDMQVOA7XLMPAH6EGZ2Q,1610912344350,0,True
2128602,5.0,Works with Sears Kenmore model 36275585891,Exact fit for Sears Kenmore model 36275585891....,[],B07QKBMPG2,B07QKBMPG2,AEYETSNK5VL6ZSLN32EE6VCOAYFA,1577986736721,1,True
2128603,5.0,Perfect little ice maker!,Love this!! It doesn’t keep the ice cold but t...,[],B07H7SGQ52,B07H7SGQ52,AHIJLNIXWVFQFWJV3OGGQOHONGMQ,1580267673035,0,True
2128604,1.0,One Star,Did not work. Not the same model as the OEM we...,[],B011LZO5QW,B0C5BHXVH1,AGIOA4MS625NBQAUNM4PMJJX3Q7Q,1454353736000,1,True

In [18]:
''' Change timestamp from unix to datetime'''
df_reviews["timestamp"] = pd.to_datetime(df_reviews["timestamp"], unit="ms")

In [25]:
df_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5.0,Work great,work great. use a new one every month,[],B01N0TQ0OH,B01N0TQ0OH,AGKHLEW2SOWHNMFQIJGBECAF7INQ,2018-02-22 16:31:48.692,0,True
1,5.0,excellent product,Little on the thin side,[],B07DD2DMXB,B07DD37QPZ,AHWWLSPCJMALVHDDVSUGICL6RUCA,2022-10-02 21:41:03.446,0,True
2,5.0,Happy customer!,"Quick delivery, fixed the issue!",[],B082W3Z9YK,B082W3Z9YK,AHZIJGKEWRTAEOZ673G5B3SNXEGQ,2020-12-06 03:30:35.363,0,True
3,5.0,Amazing value,I wasn't sure whether these were worth it or n...,[],B078W2BJY8,B078W2BJY8,AFGUPTDFAWOHHL4LZDV27ERDNOYQ,2018-08-12 20:03:04.306,0,True
4,5.0,Dryer parts,Easy to install got the product expected to re...,[],B08C9LPCQV,B08C9LPCQV,AELFJFAXQERUSMTXJQ6SYFFRDWMA,2021-05-05 01:03:23.754,0,True

In [20]:
df_reviews.to_feather('data/appliances_reviews v1.0.0.ftr')

## Meta

In [21]:
list_meta = []
with open("data/1_raw/meta_Appliances.jsonl", 'r') as fp:
    for line in tqdm(fp):
        list_meta.append(json.loads(line.strip()))

df_meta = pd.DataFrame(list_meta)

0it [00:00, ?it/s]

In [23]:
df_meta.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Industrial & Scientific,"ROVSUN Ice Maker Machine Countertop, Make 44lb...",3.7,61,[【Quick Ice Making】This countertop ice machine...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Our Point of View on the Euhomy Ic...,ROVSUN,"[Appliances, Refrigerators, Freezers & Ice Mak...","{'Brand': 'ROVSUN', 'Model Name': 'ICM-2005', ...",B08Z743RRD,None,NaN,NaN
1,Tools & Home Improvement,"HANSGO Egg Holder for Refrigerator, Deviled Eg...",4.2,75,"[Plastic, Practical Kitchen Storage - Our egg ...",[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': '10 Eggs Egg Holder for Refrigerato...,HANSGO,"[Appliances, Parts & Accessories, Refrigerator...","{'Manufacturer': 'HANSGO', 'Part Number': 'HAN...",B097BQDGHJ,None,NaN,NaN
2,Tools & Home Improvement,"Clothes Dryer Drum Slide, General Electric, Ho...",3.5,18,[],"[Brand new dryer drum slide, replaces General ...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],GE,"[Appliances, Parts & Accessories]","{'Manufacturer': 'RPI', 'Part Number': 'WE1M33...",B00IN9AGAE,None,NaN,NaN
3,Tools & Home Improvement,154567702 Dishwasher Lower Wash Arm Assembly f...,4.5,26,[MODEL NUMBER:154567702 Dishwasher Lower Wash ...,[MODEL NUMBER:154567702 Dishwasher Lower Wash ...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],folosem,"[Appliances, Parts & Accessories, Dryer Parts ...","{'Manufacturer': 'folosem', 'Part Number': '15...",B0C7K98JZS,None,NaN,NaN
4,Tools & Home Improvement,Whirlpool W10918546 Igniter,3.8,12,[This is a Genuine OEM Replacement Part.],[Whirlpool Igniter],25.07,[{'thumb': 'https://m.media-amazon.com/images/...,[],Whirlpool,"[Appliances, Parts & Accessories]","{'Manufacturer': 'Whirlpool', 'Part Number': '...",B07QZHQTVJ,None,NaN,NaN

In [22]:
df_meta['images'].iloc[0]

[{'thumb': 'https://m.media-amazon.com/images/I/31idkuA3KlL._SX38_SY50_CR,0,0,38,50_.jpg',
  'large': 'https://m.media-amazon.com/images/I/31idkuA3KlL.jpg',
  'variant': 'MAIN',
  'hi_res': 'https://m.media-amazon.com/images/I/61zNIJh6ZCL._SL1500_.jpg'},
 {'thumb': 'https://m.media-amazon.com/images/I/41-MiODg9xL._SX38_SY50_CR,0,0,38,50_.jpg',
  'large': 'https://m.media-amazon.com/images/I/41-MiODg9xL.jpg',
  'variant': 'PT01',
  'hi_res': 'https://m.media-amazon.com/images/I/71i3VazBG1L._SL1500_.jpg'},
 {'thumb': 'https://m.media-amazon.com/images/I/41wDXfH8m8L._SX38_SY50_CR,0,0,38,50_.jpg',
  'large': 'https://m.media-amazon.com/images/I/41wDXfH8m8L.jpg',
  'variant': 'PT02',
  'hi_res': 'https://m.media-amazon.com/images/I/71INhlaKSGL._SL1500_.jpg'},
 {'thumb': 'https://m.media-amazon.com/images/I/41U-3N4Al4L._SX38_SY50_CR,0,0,38,50_.jpg',
  'large': 'https://m.media-amazon.com/images/I/41U-3N4Al4L.jpg',
  'variant': 'PT03',
  'hi_res': 'https://m.media-amazon.com/images/I/71IjZxwpPgL._SL1500_.jpg'},
 {'thumb': 'https://m.media-amazon.com/images/I/51ZMIaw5j+L._SX38_SY50_CR,0,0,38,50_.jpg',
  'large': 'https://m.media-amazon.com/images/I/51ZMIaw5j+L.jpg',
  'variant': 'PT04',
  'hi_res': 'https://m.media-amazon.com/images/I/8154EOa6mML._SL1500_.jpg'},
 {'thumb': 'https://m.media-amazon.com/images/I/41rxwKw1FqL._SX38_SY50_CR,0,0,38,50_.jpg',
  'large': 'https://m.media-amazon.com/images/I/41rxwKw1FqL.jpg',
  'variant': 'PT05',
  'hi_res': 'https://m.media-amazon.com/images/I/71P3bDmPIXL._SL1500_.jpg'},
 {'thumb': 'https://m.media-amazon.com/images/I/5146wcOEdfL._SX38_SY50_CR,0,0,38,50_.jpg',
  'large': 'https://m.media-amazon.com/images/I/5146wcOEdfL.jpg',
  'variant': 'PT06',
  'hi_res': 'https://m.media-amazon.com/images/I/71ST326RerL._SL1500_.jpg'},
 {'thumb': 'https://m.media-amazon.com/images/I/61-9E6JF51L._SX38_SY50_CR,0,0,38,50_.jpg',
  'large': 'https://m.media-amazon.com/images/I/61-9E6JF51L.jpg',
  'variant': 'PT07',
  'hi_res': 'https://m.media-amazon.com/images/I/81I6c2yZStL._SL1500_.jpg'},
 {'thumb': 'https://m.media-amazon.com/images/I/51+Ddh3KfhL._SX38_SY50_CR,0,0,38,50_.jpg',
  'large': 'https://m.media-amazon.com/images/I/51+Ddh3KfhL.jpg',
  'variant': 'PT08',
  'hi_res': 'https://m.media-amazon.com/images/I/71Dap4gcywL._SL1500_.jpg'}]

In [24]:
df_meta.to_feather('data/appliances_meta v1.0.0.ftr')

# Eyeballing

In [38]:
df_reviews = pd.read_feather('data/appliances_reviews v1.0.0.ftr')

In [39]:
df_reviews['parent_asin'].nunique(), df_reviews['user_id'].nunique()

(94319, 1755732)

In [40]:
df_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5.0,Work great,work great. use a new one every month,[],B01N0TQ0OH,B01N0TQ0OH,AGKHLEW2SOWHNMFQIJGBECAF7INQ,2018-02-22 16:31:48.692,0,True
1,5.0,excellent product,Little on the thin side,[],B07DD2DMXB,B07DD37QPZ,AHWWLSPCJMALVHDDVSUGICL6RUCA,2022-10-02 21:41:03.446,0,True
2,5.0,Happy customer!,"Quick delivery, fixed the issue!",[],B082W3Z9YK,B082W3Z9YK,AHZIJGKEWRTAEOZ673G5B3SNXEGQ,2020-12-06 03:30:35.363,0,True
3,5.0,Amazing value,I wasn't sure whether these were worth it or n...,[],B078W2BJY8,B078W2BJY8,AFGUPTDFAWOHHL4LZDV27ERDNOYQ,2018-08-12 20:03:04.306,0,True
4,5.0,Dryer parts,Easy to install got the product expected to re...,[],B08C9LPCQV,B08C9LPCQV,AELFJFAXQERUSMTXJQ6SYFFRDWMA,2021-05-05 01:03:23.754,0,True

In [41]:
df_reviews_recent6mon = df_reviews[(df_reviews['timestamp'] >= '2023-01-01') & (df_reviews['timestamp'] < '2023-07-01')]

In [43]:
df_reviews_recent6mon.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,medium_image_url
25,5.0,Percolator filter rings,"I have a percolator of course, but I also have...",[],B01I4NO4T2,B082DQDDBV,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2023-02-08 21:26:23.448,0,True,NaN
104,5.0,Love my Chemex,These filters feel responsible environmentally...,[],B00S1PW58Q,B00S1PW58Q,AEZ26WGWJ3EOQ4KWSHG77HJAG4EA,2023-02-18 22:04:41.936,0,True,NaN
184,5.0,Fits stove perfectly,Very sturdy and protects my stove from acciden...,[],B09LLVXZYD,B0BKYCRTZK,AGZT7ZU75PHSV22C2QMPHLJNFK5A,2023-03-11 17:40:59.261,0,True,NaN
208,5.0,Christmas Gift,My niece loved these!,"[{'attachment_type': 'IMAGE', 'large_image_url...",B0B9J6P1PQ,B0B9J4TVR8,AGTFULIOVJK6RHUYWETEGSE5ITCQ,2023-01-23 21:47:14.866,0,True,https://m.media-amazon.com/images/I/61wBIRqjlg...
245,5.0,Great quality,"This is a high quality machine, worth every pe...",[],B08375XS5G,B0C86NF3DH,AETGCWXC47MSMK6B2TLZ44KCFJZQ,2023-03-02 20:41:25.346,2,True,NaN

In [51]:
df_reviews_recent6mon.iloc[0]['images']

array([], dtype=object)

In [53]:
df_reviews_recent6mon['parent_asin'].nunique()

22334

In [55]:
df_reviews_recent6mon['parent_asin'].value_counts().mean()

np.float64(5.2221276976806665)

In [56]:
df_reviews_recent6mon.to_feather('data/appliances_meta_012023_062023 v1.0.0.ftr')

## Recent 6-months

In [3]:
df_reviews = pd.read_feather('data/appliances_meta_012023_062023 v1.0.0.ftr')

In [4]:
col = "images"   # <- change to your real column name

def to_list(x):
    if isinstance(x, (list, tuple)): 
        return list(x)
    if isinstance(x, np.ndarray): 
        return x.tolist()
    if pd.isna(x): 
        return []
    return [x]  # single dict or scalar

def extract_mediums(seq):
    out = []
    for item in seq:
        if isinstance(item, dict) and item.get("attachment_type") == "IMAGE":
            url = item.get("medium_image_url")
            if url:
                out.append(url)
    return out

seqs = df_reviews[col].apply(to_list)
medium_lists = seqs.apply(extract_mediums)

# 1) If you want a single column with the first medium image (or NaN):
df_reviews["medium_image_url"] = medium_lists.str[0]

# 2) If you want one column per image:
exp = pd.DataFrame(medium_lists.tolist(), index=df_reviews.index)
exp.columns = [f"medium_image_url_{i+1}" for i in range(exp.shape[1])]
df_reviews_imgs = df_reviews.drop(columns=[col]).join(exp)

In [5]:
''' Slice products with more than 2 reviews -> to calculate inter-review time '''
df_rv_vc = df_reviews_imgs['parent_asin'].value_counts()
df_reviews_mt2rvs = df_reviews_imgs[df_reviews_imgs['parent_asin'].isin(df_rv_vc[df_rv_vc>=2].index)]

In [6]:
''' 11,701 products with average 9 reviews'''
df_reviews_mt2rvs['parent_asin'].nunique(), df_reviews_mt2rvs['parent_asin'].value_counts().mean()

(11701, np.float64(9.058883856080676))

In [7]:
df_reviews_mt2rvs.head()

,rating,title,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,medium_image_url,medium_image_url_1,medium_image_url_2,medium_image_url_3,medium_image_url_4,medium_image_url_5,medium_image_url_6,medium_image_url_7,medium_image_url_8,medium_image_url_9,medium_image_url_10,medium_image_url_11,medium_image_url_12,medium_image_url_13,medium_image_url_14,medium_image_url_15,medium_image_url_16,medium_image_url_17,medium_image_url_18,medium_image_url_19,medium_image_url_20,medium_image_url_21,medium_image_url_22,medium_image_url_23,medium_image_url_24,medium_image_url_25,medium_image_url_26,medium_image_url_27
25,5.0,Percolator filter rings,"I have a percolator of course, but I also have...",B01I4NO4T2,B082DQDDBV,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2023-02-08 21:26:23.448,0,True,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
104,5.0,Love my Chemex,These filters feel responsible environmentally...,B00S1PW58Q,B00S1PW58Q,AEZ26WGWJ3EOQ4KWSHG77HJAG4EA,2023-02-18 22:04:41.936,0,True,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
184,5.0,Fits stove perfectly,Very sturdy and protects my stove from acciden...,B09LLVXZYD,B0BKYCRTZK,AGZT7ZU75PHSV22C2QMPHLJNFK5A,2023-03-11 17:40:59.261,0,True,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
208,5.0,Christmas Gift,My niece loved these!,B0B9J6P1PQ,B0B9J4TVR8,AGTFULIOVJK6RHUYWETEGSE5ITCQ,2023-01-23 21:47:14.866,0,True,https://m.media-amazon.com/images/I/61wBIRqjlg...,https://m.media-amazon.com/images/I/61wBIRqjlg...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
245,5.0,Great quality,"This is a high quality machine, worth every pe...",B08375XS5G,B0C86NF3DH,AETGCWXC47MSMK6B2TLZ44KCFJZQ,2023-03-02 20:41:25.346,2,True,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [8]:
''' 91.79% of reviews do not have review images '''
len(df_reviews_mt2rvs[df_reviews_mt2rvs['medium_image_url'].isnull()]) / len(df_reviews_mt2rvs)

0.917960716239929

- with images

In [9]:
df_reviews = df_reviews_mt2rvs.copy().sort_values(by=['parent_asin', 'timestamp'], ascending=[True, False])

In [10]:
len(df_reviews), df_reviews['parent_asin'].nunique(), df_reviews['parent_asin'].value_counts().mean()

(105998, 11701, np.float64(9.058883856080676))

In [11]:
len(df_reviews[df_reviews['medium_image_url'].notnull()])/ len(df_reviews)

0.08203928376007094

In [12]:
df_reviews['text_len'] = df_reviews['text'].str.len()
df_reviews['text_words'] =  df_reviews['text'].str.split(' ').str.len()

In [13]:
df_reviews['inter_review_time'] = df_reviews.groupby(['parent_asin'])['timestamp'].diff().abs()

In [14]:
df_reviews.head()

,rating,title,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,medium_image_url,medium_image_url_1,medium_image_url_2,medium_image_url_3,medium_image_url_4,medium_image_url_5,medium_image_url_6,medium_image_url_7,medium_image_url_8,medium_image_url_9,medium_image_url_10,medium_image_url_11,medium_image_url_12,medium_image_url_13,medium_image_url_14,medium_image_url_15,medium_image_url_16,medium_image_url_17,medium_image_url_18,medium_image_url_19,medium_image_url_20,medium_image_url_21,medium_image_url_22,medium_image_url_23,medium_image_url_24,medium_image_url_25,medium_image_url_26,medium_image_url_27,text_len,text_words,inter_review_time
70468,3.0,Needs hose clamps,Needs metal hose clamps not plastic ties.... C...,B00004YWK2,B00004YWK2,AFFPAJDCW7NSKE4FZWBRWETUKZ2A,2023-02-18 02:32:06.278,0,True,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,108,18,NaT
1321298,1.0,Don't waste your money,Product is cheap and the door doesn't work well,B00004YWK2,B00004YWK2,AEI6B25VF65CG2HPBQ2FNBG7IQKA,2023-02-10 00:31:39.499,0,True,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,47,9,8 days 02:00:26.779000
1130013,1.0,Must have been a return,No cover to close it and plastic was separated.,B00004YWK2,B00004YWK2,AGA5X6NUWSQM42KDFJLO25JBXOEA,2023-02-07 14:55:58.766,0,True,https://m.media-amazon.com/images/I/71eRK2xYuJ...,https://m.media-amazon.com/images/I/71eRK2xYuJ...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,47,9,2 days 09:35:40.733000
977568,5.0,Great product,"I love this it keeps my garage, nice and warm ...",B00004YWK2,B00004YWK2,AGO4SBTXOUTKYMHKQQNX7ZFDQSFA,2023-01-29 19:37:40.587,0,True,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,115,24,8 days 19:18:18.179000
164731,5.0,Why be wasteful?,"So I mounted this, as you see, behind and just...",B00004YWK2,B00004YWK2,AHKTIX6L7FKPYDENUALEPNPMAIHQ,2023-01-03 16:32:51.697,0,True,https://m.media-amazon.com/images/I/61ctMn42LX...,https://m.media-amazon.com/images/I/61ctMn42LX...,https://m.media-amazon.com/images/I/71QP-FAvlQ...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,708,148,26 days 03:04:48.890000

In [15]:
df_reviews[['helpful_vote', 'rating', 'text_len', 'text_words', 'inter_review_time']].describe().T

,count,mean,std,min,25%,50%,75%,max
helpful_vote,105998.0,0.396932,2.012085,0.0,0.0,0.0,0.0,194.0
rating,105998.0,4.00016,1.53567,1.0,3.0,5.0,5.0,5.0
text_len,105998.0,189.585322,261.608314,1.0,48.0,109.0,232.0,14421.0
text_words,105998.0,35.84361,49.201634,1.0,9.0,20.0,44.0,2601.0
inter_review_time,94297,10 days 11:49:38.720509475,17 days 23:20:09.999348140,0 days 00:00:00,0 days 19:30:17.182000,3 days 04:24:31.248000,11 days 15:05:58.557000,178 days 06:43:40.536000

In [17]:
df_reviews.insert(0, 'review_id', range(1, len(df_reviews)+1))

In [19]:
df_reviews.head()

,review_id,rating,title,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,medium_image_url,medium_image_url_1,medium_image_url_2,medium_image_url_3,medium_image_url_4,medium_image_url_5,medium_image_url_6,medium_image_url_7,medium_image_url_8,medium_image_url_9,medium_image_url_10,medium_image_url_11,medium_image_url_12,medium_image_url_13,medium_image_url_14,medium_image_url_15,medium_image_url_16,medium_image_url_17,medium_image_url_18,medium_image_url_19,medium_image_url_20,medium_image_url_21,medium_image_url_22,medium_image_url_23,medium_image_url_24,medium_image_url_25,medium_image_url_26,medium_image_url_27,text_len,text_words,inter_review_time
70468,1,3.0,Needs hose clamps,Needs metal hose clamps not plastic ties.... C...,B00004YWK2,B00004YWK2,AFFPAJDCW7NSKE4FZWBRWETUKZ2A,2023-02-18 02:32:06.278,0,True,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,108,18,NaT
1321298,2,1.0,Don't waste your money,Product is cheap and the door doesn't work well,B00004YWK2,B00004YWK2,AEI6B25VF65CG2HPBQ2FNBG7IQKA,2023-02-10 00:31:39.499,0,True,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,47,9,8 days 02:00:26.779000
1130013,3,1.0,Must have been a return,No cover to close it and plastic was separated.,B00004YWK2,B00004YWK2,AGA5X6NUWSQM42KDFJLO25JBXOEA,2023-02-07 14:55:58.766,0,True,https://m.media-amazon.com/images/I/71eRK2xYuJ...,https://m.media-amazon.com/images/I/71eRK2xYuJ...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,47,9,2 days 09:35:40.733000
977568,4,5.0,Great product,"I love this it keeps my garage, nice and warm ...",B00004YWK2,B00004YWK2,AGO4SBTXOUTKYMHKQQNX7ZFDQSFA,2023-01-29 19:37:40.587,0,True,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,115,24,8 days 19:18:18.179000
164731,5,5.0,Why be wasteful?,"So I mounted this, as you see, behind and just...",B00004YWK2,B00004YWK2,AHKTIX6L7FKPYDENUALEPNPMAIHQ,2023-01-03 16:32:51.697,0,True,https://m.media-amazon.com/images/I/61ctMn42LX...,https://m.media-amazon.com/images/I/61ctMn42LX...,https://m.media-amazon.com/images/I/71QP-FAvlQ...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,708,148,26 days 03:04:48.890000

In [20]:
df_reviews.reset_index(drop=True).to_feather('data/appliances_meta_012023_062023 v1.1.0.ftr')

# Merge Metadata

In [23]:
df_meta = pd.read_feather('data/1_raw/appliances_meta v1.0.0.ftr')[['parent_asin', 'main_category', 'average_rating', 'rating_number', 'price', 'store', 'categories',]]
df_reviews = pd.read_feather('data/appliances_reviews_012023_062023 v1.3.0.ftr')

In [24]:
df_meta['categories'] = df_meta['categories'].str[1]

In [25]:
df_meta.head()

,parent_asin,main_category,average_rating,rating_number,price,store,categories
0,B08Z743RRD,Industrial & Scientific,3.7,61,NaN,ROVSUN,"Refrigerators, Freezers & Ice Makers"
1,B097BQDGHJ,Tools & Home Improvement,4.2,75,NaN,HANSGO,Parts & Accessories
2,B00IN9AGAE,Tools & Home Improvement,3.5,18,NaN,GE,Parts & Accessories
3,B0C7K98JZS,Tools & Home Improvement,4.5,26,NaN,folosem,Parts & Accessories
4,B07QZHQTVJ,Tools & Home Improvement,3.8,12,25.07,Whirlpool,Parts & Accessories

In [26]:
df_reviews_mrgMeta = df_reviews.merge(df_meta, on='parent_asin', how='left')

In [28]:
col_txt = [col for col in df_reviews_mrgMeta.columns if 'MPN' in col]
col_img = [col for col in df_reviews_mrgMeta.columns if 'ResNet' in col]
col_etc = set(list(df_reviews_mrgMeta.columns)) - set(col_txt) - set(col_img)

In [33]:
df_reviews_mrgMeta_org = df_reviews_mrgMeta[['review_id', 'rating', 'title', 'text', 'asin', 'parent_asin', 'user_id', 'timestamp', 'helpful_vote', 'verified_purchase', 'text_len', 'text_words', 
                                             'inter_review_time', 'main_category', 'average_rating', 'rating_number', 'price', 'store', 'categories'] + col_txt + col_img]

In [35]:
df_reviews_mrgMeta_org.head()

,review_id,rating,title,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,text_len,text_words,inter_review_time,main_category,average_rating,rating_number,price,store,categories,MPN_1,MPN_2,MPN_3,MPN_4,MPN_5,MPN_6,MPN_7,MPN_8,MPN_9,MPN_10,MPN_11,MPN_12,MPN_13,MPN_14,MPN_15,MPN_16,MPN_17,MPN_18,MPN_19,MPN_20,MPN_21,MPN_22,MPN_23,MPN_24,MPN_25,MPN_26,MPN_27,MPN_28,MPN_29,MPN_30,MPN_31,MPN_32,MPN_33,MPN_34,MPN_35,MPN_36,MPN_37,MPN_38,MPN_39,MPN_40,MPN_41,MPN_42,MPN_43,MPN_44,MPN_45,MPN_46,MPN_47,MPN_48,MPN_49,MPN_50,MPN_51,MPN_52,MPN_53,MPN_54,MPN_55,MPN_56,MPN_57,MPN_58,MPN_59,MPN_60,MPN_61,MPN_62,MPN_63,MPN_64,MPN_65,MPN_66,MPN_67,MPN_68,MPN_69,MPN_70,MPN_71,MPN_72,MPN_73,MPN_74,MPN_75,MPN_76,MPN_77,MPN_78,MPN_79,MPN_80,MPN_81,MPN_82,MPN_83,MPN_84,MPN_85,MPN_86,MPN_87,MPN_88,MPN_89,MPN_90,MPN_91,MPN_92,MPN_93,MPN_94,MPN_95,MPN_96,MPN_97,MPN_98,MPN_99,MPN_100,MPN_101,MPN_102,MPN_103,MPN_104,MPN_105,MPN_106,MPN_107,MPN_108,MPN_109,MPN_110,MPN_111,MPN_112,MPN_113,MPN_114,MPN_115,MPN_116,MPN_117,MPN_118,MPN_119,MPN_120,MPN_121,MPN_122,MPN_123,MPN_124,MPN_125,MPN_126,MPN_127,MPN_128,MPN_129,MPN_130,MPN_131,MPN_132,MPN_133,MPN_134,MPN_135,MPN_136,MPN_137,MPN_138,MPN_139,MPN_140,MPN_141,MPN_142,MPN_143,MPN_144,MPN_145,MPN_146,MPN_147,MPN_148,MPN_149,MPN_150,MPN_151,MPN_152,MPN_153,MPN_154,MPN_155,MPN_156,MPN_157,MPN_158,MPN_159,MPN_160,MPN_161,MPN_162,MPN_163,MPN_164,MPN_165,MPN_166,MPN_167,MPN_168,MPN_169,MPN_170,MPN_171,MPN_172,MPN_173,MPN_174,MPN_175,MPN_176,MPN_177,MPN_178,MPN_179,MPN_180,MPN_181,MPN_182,MPN_183,MPN_184,MPN_185,MPN_186,MPN_187,MPN_188,MPN_189,MPN_190,MPN_191,MPN_192,MPN_193,MPN_194,MPN_195,MPN_196,MPN_197,MPN_198,MPN_199,MPN_200,MPN_201,MPN_202,MPN_203,MPN_204,MPN_205,MPN_206,MPN_207,MPN_208,MPN_209,MPN_210,MPN_211,MPN_212,MPN_213,MPN_214,MPN_215,MPN_216,MPN_217,MPN_218,MPN_219,MPN_220,MPN_221,MPN_222,MPN_223,MPN_224,MPN_225,MPN_226,MPN_227,MPN_228,MPN_229,MPN_230,MPN_231,MPN_232,MPN_233,MPN_234,MPN_235,MPN_236,MPN_237,MPN_238,MPN_239,MPN_240,MPN_241,MPN_242,MPN_243,MPN_244,MPN_245,MPN_246,MPN_247,MPN_248,MPN_249,MPN_250,MPN_251,MPN_252,MPN_253,MPN_254,MPN_255,MPN_256,MPN_257,MPN_258,MPN_259,MPN_260,MPN_261,MPN_262,MPN_263,MPN_264,MPN_265,MPN_266,MPN_267,MPN_268,MPN_269,MPN_270,MPN_271,MPN_272,MPN_273,MPN_274,MPN_275,MPN_276,MPN_277,MPN_278,MPN_279,MPN_280,MPN_281,MPN_282,MPN_283,MPN_284,MPN_285,MPN_286,MPN_287,MPN_288,MPN_289,MPN_290,MPN_291,MPN_292,MPN_293,MPN_294,MPN_295,MPN_296,MPN_297,MPN_298,MPN_299,MPN_300,MPN_301,MPN_302,MPN_303,MPN_304,MPN_305,MPN_306,MPN_307,MPN_308,MPN_309,MPN_310,MPN_311,MPN_312,MPN_313,MPN_314,MPN_315,MPN_316,MPN_317,MPN_318,MPN_319,MPN_320,MPN_321,MPN_322,MPN_323,MPN_324,MPN_325,MPN_326,MPN_327,MPN_328,MPN_329,MPN_330,MPN_331,MPN_332,MPN_333,MPN_334,MPN_335,MPN_336,MPN_337,MPN_338,MPN_339,MPN_340,MPN_341,MPN_342,MPN_343,MPN_344,MPN_345,MPN_346,MPN_347,MPN_348,MPN_349,MPN_350,MPN_351,MPN_352,MPN_353,MPN_354,MPN_355,MPN_356,MPN_357,MPN_358,MPN_359,MPN_360,MPN_361,MPN_362,MPN_363,MPN_364,MPN_365,MPN_366,MPN_367,MPN_368,MPN_369,MPN_370,MPN_371,MPN_372,MPN_373,MPN_374,MPN_375,MPN_376,MPN_377,MPN_378,MPN_379,MPN_380,MPN_381,MPN_382,MPN_383,MPN_384,MPN_385,MPN_386,MPN_387,MPN_388,MPN_389,MPN_390,MPN_391,MPN_392,MPN_393,MPN_394,MPN_395,MPN_396,MPN_397,MPN_398,MPN_399,MPN_400,MPN_401,MPN_402,MPN_403,MPN_404,MPN_405,MPN_406,MPN_407,MPN_408,MPN_409,MPN_410,MPN_411,MPN_412,MPN_413,MPN_414,MPN_415,MPN_416,MPN_417,MPN_418,MPN_419,MPN_420,MPN_421,MPN_422,MPN_423,MPN_424,MPN_425,MPN_426,MPN_427,MPN_428,MPN_429,MPN_430,MPN_431,MPN_432,MPN_433,MPN_434,MPN_435,MPN_436,MPN_437,MPN_438,MPN_439,MPN_440,MPN_441,MPN_442,MPN_443,MPN_444,MPN_445,MPN_446,MPN_447,MPN_448,MPN_449,MPN_450,MPN_451,MPN_452,MPN_453,MPN_454,MPN_455,MPN_456,MPN_457,MPN_458,MPN_459,MPN_460,MPN_461,MPN_462,MPN_463,MPN_464,MPN_465,MPN_466,MPN_467,MPN_468,MPN_469,MPN_470,MPN_471,MPN_472,MPN_473,MPN_474,MPN_475,MPN_476,MPN_477,MPN_478,MPN_479,MPN_480,MPN_481,MPN_482,MPN_483,MPN_484,MPN_485,MPN_486,MPN_487,MPN_488,MPN_489,MPN_490,MPN_491,MPN_492,MPN_493,MPN_494,MPN_495,MPN_496,MPN_497,MPN_498,MPN_499,MPN_500,MPN_501,MPN_502,MPN_503,MPN_504,MPN_505,MPN_506,MPN_507,MPN_508,MPN_509,MPN_510,MPN_511,MPN_512,MPN_513,MPN_514,MPN_515,MPN_516,MPN_517,MPN_518,MPN_519,MPN_520,MPN_521,MPN_522,MPN_523,MPN_524,MPN_525,MPN_526,MPN_527,MPN_528,MPN_529,MPN_530,MPN_531,MPN_532,MPN_533,MPN_534,MPN_535,MPN_536,MPN_537,MPN_538,MPN_539,MPN_540,MPN_541,MPN_542,MPN_543,MPN_544,MPN_545,MPN_546,MPN_547,MPN_548,MPN_549,MPN_550,MPN_551,MPN_552,MPN_553,MPN_554,MPN_555,MPN_556,MPN_557,MPN_558,MPN_559,MPN_560,MPN_561,MPN_562,MPN_563,MPN_564,MPN_565,MPN_566,MPN_567,MPN_568,MPN_569,MPN_570,MPN_571,MPN_572,MPN_573,MPN_574,MPN_575,MPN_576,MPN_577,MPN_578,MPN_579,MPN_580,MPN_581,MPN_582,MPN_583,MPN_584,MPN_585,MPN_586,MPN_587,MPN_588,MPN_589,MPN_590,MPN_591,MPN_592,MPN_593,MPN_594,MPN_595,MPN_596,MPN_597,MPN_598,MPN_599,MPN_600,MPN_601,MPN_602,MPN_603,MPN_604,MPN_605,MPN_606,MPN_607,MPN_608,MPN_609,MPN_610,MPN_611,MPN_612,MPN_613,MPN_614,MPN_615,MPN_616,MPN_617,MPN_618,MPN_619,MPN_620,MPN_621,MPN_622,MPN_623,MPN_624,MPN_625,MPN_626,MPN_627,MPN_628,MPN_629,MPN_630,MPN_631,MPN_632,MPN_633,MPN_634,MPN_635,MPN_636,MPN_637,MPN_638,MPN_639,MPN_640,MPN_641,MPN_642,MPN_643,MPN_644,MPN_645,MPN_646,MPN_647,MPN_648,MPN_649,MPN_650,MPN_651,MPN_652,MPN_653,MPN_654,MPN_655,MPN_656,MPN_657,MPN_658,MPN_659,MPN_660,MPN_661,MPN_662,MPN_663,MPN_664,MPN_665,MPN_666,MPN_667,MPN_668,MPN_669,MPN_670,MPN_671,MPN_672,MPN_673,MPN_674,MPN_675,MPN_676,MPN_677,MPN_678,MPN_679,MPN_680,MPN_681,MPN_682,MPN_683,MPN_684,MPN_685,MPN_686,MPN_687,MPN_688,MPN_689,MPN_690,MPN_691,MPN_692,MPN_693,MPN_694,MPN_695,MPN_696,MPN_697,MPN_698,MPN_699,MPN_700,MPN_701,MPN_702,MPN_703,MPN_704,MPN_705,MPN_706,MPN_707,MPN_708,MPN_709,MPN_710,MPN_711,MPN_712,MPN_713,MPN_714,MPN_715,MPN_716,MPN_717,MPN_718,MPN_719,MPN_720,MPN_721,MPN_722,MPN_723,MPN_724,MPN_725,MPN_726,MPN_727,MPN_728,MPN_729,MPN_730,MPN_731,MPN_732,MPN_733,MPN_734,MPN_735,MPN_736,MPN_737,MPN_738,MPN_739,MPN_740,MPN_741,MPN_742,MPN_743,MPN_744,MPN_745,MPN_746,MPN_747,MPN_748,MPN_749,MPN_750,MPN_751,MPN_752,MPN_753,MPN_754,MPN_755,MPN_756,MPN_757,MPN_758,MPN_759,MPN_760,MPN_761,MPN_762,MPN_763,MPN_764,MPN_765,MPN_766,MPN_767,MPN_768,ResNet1,ResNet2,ResNet3,ResNet4,ResNet5,ResNet6,ResNet7,ResNet8,ResNet9,ResNet10,ResNet11,ResNet12,ResNet13,ResNet14,ResNet15,ResNet16,ResNet17,ResNet18,ResNet19,ResNet20,ResNet21,ResNet22,ResNet23,ResNet24,ResNet25,ResNet26,ResNet27,ResNet28,ResNet29,ResNet30,ResNet31,ResNet32,ResNet33,ResNet34,ResNet35,ResNet36,ResNet37,ResNet38,ResNet39,ResNet40,ResNet41,ResNet42,ResNet43,ResNet44,ResNet45,ResNet46,ResNet47,ResNet48,ResNet49,ResNet50,ResNet51,ResNet52,ResNet53,ResNet54,ResNet55,ResNet56,ResNet57,ResNet58,ResNet59,ResNet60,ResNet61,ResNet62,ResNet63,ResNet64,ResNet65,ResNet66,ResNet67,ResNet68,ResNet69,ResNet70,ResNet71,ResNet72,ResNet73,ResNet74,ResNet75,ResNet76,ResNet77,ResNet78,ResNet79,ResNet80,ResNet81,ResNet82,ResNet83,ResNet84,ResNet85,ResNet86,ResNet87,ResNet88,ResNet89,ResNet90,ResNet91,ResNet92,ResNet93,ResNet94,ResNet95,ResNet96,ResNet97,ResNet98,ResNet99,ResNet100,ResNet101,ResNet102,ResNet103,ResNet104,ResNet105,ResNet106,ResNet107,ResNet108,ResNet109,ResNet110,ResNet111,ResNet112,ResNet113,ResNet114,ResNet115,ResNet116,ResNet117,ResNet118,ResNet119,ResNet120,ResNet121,ResNet122,ResNet123,ResNet124,ResNet125,ResNet126,ResNet127,ResNet128,ResNet129,ResNet130,ResNet131,ResNet132,ResNet133,ResNet134,ResNet135,ResNet136,ResNet137,ResNet138,ResNet139,ResNet140,ResNet141,ResNet142,ResNet143,ResNet144,ResNet145,ResNet146,ResNet147,ResNet148,ResNet149,ResNet150,ResNet151,ResNet152,ResNet153,ResNet154,ResNet155,ResNet156,ResNet157,ResNet158,ResNet159,ResNet160,ResNet161,ResNet162,ResNet163,ResNet164,ResNet165,ResNet166,ResNet167,ResNet168,ResNet169,ResNet170,ResNet171,ResNet172,ResNet173,ResNet174,ResNet175,ResNet176,ResNet177,ResNet178,ResNet179,ResNet180,ResNet181,ResNet182,ResNet183,ResNet184,ResNet185,ResNet186,ResNet187,ResNet188,ResNet189,ResNet190,ResNet191,ResNet192,ResNet193,ResNet194,ResNet195,ResNet196,ResNet197,ResNet198,ResNet199,ResNet200,ResNet201,ResNet202,ResNet203,ResNet204,ResNet205,ResNet206,ResNet207,ResNet208,ResNet209,ResNet210,ResNet211,ResNet212,ResNet213,ResNet214,ResNet215,ResNet216,ResNet217,ResNet218,ResNet219,ResNet220,ResNet221,ResNet222,ResNet223,ResNet224,ResNet225,ResNet226,ResNet227,ResNet228,ResNet229,ResNet230,ResNet231,ResNet232,ResNet233,ResNet234,ResNet235,ResNet236,ResNet237,ResNet238,ResNet239,ResNet240,ResNet241,ResNet242,ResNet243,ResNet244,ResNet245,ResNet246,ResNet247,ResNet248,ResNet249,ResNet250,ResNet251,ResNet252,ResNet253,ResNet254,ResNet255,ResNet256,ResNet257,ResNet258,ResNet259,ResNet260,ResNet261,ResNet262,ResNet263,ResNet264,ResNet265,ResNet266,ResNet267,ResNet268,ResNet269,ResNet270,ResNet271,ResNet272,ResNet273,ResNet274,ResNet275,ResNet276,ResNet277,ResNet278,ResNet279,ResNet280,ResNet281,ResNet282,ResNet283,ResNet284,ResNet285,ResNet286,ResNet287,ResNet288,ResNet289,ResNet290,ResNet291,ResNet292,ResNet293,ResNet294,ResNet295,ResNet296,ResNet297,ResNet298,ResNet299,ResNet300,ResNet301,ResNet302,ResNet303,ResNet304,ResNet305,ResNet306,ResNet307,ResNet308,ResNet309,ResNet310,ResNet311,ResNet312,ResNet313,ResNet314,ResNet315,ResNet316,ResNet317,ResNet318,ResNet319,ResNet320,ResNet321,ResNet322,ResNet323,ResNet324,ResNet325,ResNet326,ResNet327,ResNet328,ResNet329,ResNet330,ResNet331,ResNet332,ResNet333,ResNet334,ResNet335,ResNet336,ResNet337,ResNet338,ResNet339,ResNet340,ResNet341,ResNet342,ResNet343,ResNet344,ResNet345,ResNet346,ResNet347,ResNet348,ResNet349,ResNet350,ResNet351,ResNet352,ResNet353,ResNet354,ResNet355,ResNet356,ResNet357,ResNet358,ResNet359,ResNet360,ResNet361,ResNet362,ResNet363,ResNet364,ResNet365,ResNet366,ResNet367,ResNet368,ResNet369,ResNet370,ResNet371,ResNet372,ResNet373,ResNet374,ResNet375,ResNet376,ResNet377,ResNet378,ResNet379,ResNet380,ResNet381,ResNet382,ResNet383,ResNet384,ResNet385,ResNet386,ResNet387,ResNet388,ResNet389,ResNet390,ResNet391,ResNet392,ResNet393,ResNet394,ResNet395,ResNet396,ResNet397,ResNet398,ResNet399,ResNet400,ResNet401,ResNet402,ResNet403,ResNet404,ResNet405,ResNet406,ResNet407,ResNet408,ResNet409,ResNet410,ResNet411,ResNet412,ResNet413,ResNet414,ResNet415,ResNet416,ResNet417,ResNet418,ResNet419,ResNet420,ResNet421,ResNet422,ResNet423,ResNet424,ResNet425,ResNet426,ResNet427,ResNet428,ResNet429,ResNet430,ResNet431,ResNet432,ResNet433,ResNet434,ResNet435,ResNet436,ResNet437,ResNet438,ResNet439,ResNet440,ResNet441,ResNet442,ResNet443,ResNet444,ResNet445,ResNet446,ResNet447,ResNet448,ResNet449,ResNet450,ResNet451,ResNet452,ResNet453,ResNet454,ResNet455,ResNet456,ResNet457,ResNet458,ResNet459,ResNet460,ResNet461,ResNet462,ResNet463,ResNet464,ResNet465,ResNet466,ResNet467,ResNet468,ResNet469,ResNet470,ResNet471,ResNet472,ResNet473,ResNet474,ResNet475,ResNet476,ResNet477,ResNet478,ResNet479,ResNet480,ResNet481,ResNet482,ResNet483,ResNet484,ResNet485,ResNet486,ResNet487,ResNet488,ResNet489,ResNet490,ResNet491,ResNet492,ResNet493,ResNet494,ResNet495,ResNet496,ResNet497,ResNet498,ResNet499,ResNet500,ResNet501,ResNet502,ResNet503,ResNet504,ResNet505,ResNet506,ResNet507,ResNet508,ResNet509,ResNet510,ResNet511,ResNet512

In [36]:
df_reviews_mrgMeta_org.to_feather('data/appliances_reviews_012023_062023 v1.4.0.ftr')