# 🦅 Set Up

In [1]:
import json
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm
from sentence_transformers import SentenceTransformer

pd.set_option('display.max_columns', None)

In [2]:
cd ..

C:\Users\chopi\Penn Dropbox\Hyunwoo Jung\1_Personal\_Hyunwoo Place\graduate school\2_coursework (2025-F)\2_CIS5200_Machine Learning\5_final project\3_analyses

# 🦅 Load Data

In [54]:
df_reviews = pd.read_feather('data/appliances_meta_012023_062023 v1.1.0.ftr')

In [56]:
df_reviews.head()

,review_id,rating,title,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,medium_image_url,medium_image_url_1,medium_image_url_2,medium_image_url_3,medium_image_url_4,medium_image_url_5,medium_image_url_6,medium_image_url_7,medium_image_url_8,medium_image_url_9,medium_image_url_10,medium_image_url_11,medium_image_url_12,medium_image_url_13,medium_image_url_14,medium_image_url_15,medium_image_url_16,medium_image_url_17,medium_image_url_18,medium_image_url_19,medium_image_url_20,medium_image_url_21,medium_image_url_22,medium_image_url_23,medium_image_url_24,medium_image_url_25,medium_image_url_26,medium_image_url_27,text_len,text_words,inter_review_time
0,1,3.0,Needs hose clamps,Needs metal hose clamps not plastic ties.... C...,B00004YWK2,B00004YWK2,AFFPAJDCW7NSKE4FZWBRWETUKZ2A,2023-02-18 02:32:06.278,0,True,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,108,18,NaT
1,2,1.0,Don't waste your money,Product is cheap and the door doesn't work well,B00004YWK2,B00004YWK2,AEI6B25VF65CG2HPBQ2FNBG7IQKA,2023-02-10 00:31:39.499,0,True,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,47,9,8 days 02:00:26.779000
2,3,1.0,Must have been a return,No cover to close it and plastic was separated.,B00004YWK2,B00004YWK2,AGA5X6NUWSQM42KDFJLO25JBXOEA,2023-02-07 14:55:58.766,0,True,https://m.media-amazon.com/images/I/71eRK2xYuJ...,https://m.media-amazon.com/images/I/71eRK2xYuJ...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,47,9,2 days 09:35:40.733000
3,4,5.0,Great product,"I love this it keeps my garage, nice and warm ...",B00004YWK2,B00004YWK2,AGO4SBTXOUTKYMHKQQNX7ZFDQSFA,2023-01-29 19:37:40.587,0,True,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,115,24,8 days 19:18:18.179000
4,5,5.0,Why be wasteful?,"So I mounted this, as you see, behind and just...",B00004YWK2,B00004YWK2,AHKTIX6L7FKPYDENUALEPNPMAIHQ,2023-01-03 16:32:51.697,0,True,https://m.media-amazon.com/images/I/61ctMn42LX...,https://m.media-amazon.com/images/I/61ctMn42LX...,https://m.media-amazon.com/images/I/71QP-FAvlQ...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,708,148,26 days 03:04:48.890000

In [4]:
''' 105K reviews, 11K products '''
len(df_reviews), df_reviews['parent_asin'].nunique(), df_reviews['parent_asin'].value_counts().mean()

(105998, 11701, np.float64(9.058883856080676))

In [5]:
df_reviews[['helpful_vote', 'rating', 'text_len', 'text_words', 'inter_review_time']].describe().T

,count,mean,std,min,25%,50%,75%,max
helpful_vote,105998.0,0.396932,2.012085,0.0,0.0,0.0,0.0,194.0
rating,105998.0,4.00016,1.53567,1.0,3.0,5.0,5.0,5.0
text_len,105998.0,189.585322,261.608314,1.0,48.0,109.0,232.0,14421.0
text_words,105998.0,35.84361,49.201634,1.0,9.0,20.0,44.0,2601.0
inter_review_time,94297,10 days 11:49:38.720509475,17 days 23:20:09.999348140,0 days 00:00:00,0 days 19:30:17.182000,3 days 04:24:31.248000,11 days 15:05:58.557000,178 days 06:43:40.536000

# 🦅 Extract Embeddings

In [7]:
model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Users\chopi\anaconda3\envs\ml-project\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\chopi\.cache\huggingface\hub\models--sentence-transformers--all-mpnet-base-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [33]:
''' Extract sentence embeddings '''
df_reviews_text = df_reviews['text']
X = model.encode(df_reviews_text.values, batch_size=256, show_progress_bar=True)

Batches:   0%|          | 0/415 [00:00<?, ?it/s]

In [42]:
X.shape, df_reviews_text.shape

((105998, 768), (105998,))

In [63]:
''' Merge embeddings into the original dataframe'''
df_reviews_text_embeddings = pd.concat([df_reviews_text, pd.DataFrame(X, columns=['MPN_{}'.format(i+1) for i in range(X.shape[1])])], axis=1)
df_reviews_mrgEmb = pd.concat([df_reviews, df_reviews_text_embeddings.drop(columns=['text'])], axis=1)

In [64]:
display(df_reviews_mrgEmb.head())
display(df_reviews_mrgEmb.tail())

,review_id,rating,title,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,medium_image_url,medium_image_url_1,medium_image_url_2,medium_image_url_3,medium_image_url_4,medium_image_url_5,medium_image_url_6,medium_image_url_7,medium_image_url_8,medium_image_url_9,medium_image_url_10,medium_image_url_11,medium_image_url_12,medium_image_url_13,medium_image_url_14,medium_image_url_15,medium_image_url_16,medium_image_url_17,medium_image_url_18,medium_image_url_19,medium_image_url_20,medium_image_url_21,medium_image_url_22,medium_image_url_23,medium_image_url_24,medium_image_url_25,medium_image_url_26,medium_image_url_27,text_len,text_words,inter_review_time,MPN_1,MPN_2,MPN_3,MPN_4,MPN_5,MPN_6,MPN_7,MPN_8,MPN_9,MPN_10,MPN_11,MPN_12,MPN_13,MPN_14,MPN_15,MPN_16,MPN_17,MPN_18,MPN_19,MPN_20,MPN_21,MPN_22,MPN_23,MPN_24,MPN_25,MPN_26,MPN_27,MPN_28,MPN_29,MPN_30,MPN_31,MPN_32,MPN_33,MPN_34,MPN_35,MPN_36,MPN_37,MPN_38,MPN_39,MPN_40,MPN_41,MPN_42,MPN_43,MPN_44,MPN_45,MPN_46,MPN_47,MPN_48,MPN_49,MPN_50,MPN_51,MPN_52,MPN_53,MPN_54,MPN_55,MPN_56,MPN_57,MPN_58,MPN_59,MPN_60,MPN_61,MPN_62,MPN_63,MPN_64,MPN_65,MPN_66,MPN_67,MPN_68,MPN_69,MPN_70,MPN_71,MPN_72,MPN_73,MPN_74,MPN_75,MPN_76,MPN_77,MPN_78,MPN_79,MPN_80,MPN_81,MPN_82,MPN_83,MPN_84,MPN_85,MPN_86,MPN_87,MPN_88,MPN_89,MPN_90,MPN_91,MPN_92,MPN_93,MPN_94,MPN_95,MPN_96,MPN_97,MPN_98,MPN_99,MPN_100,MPN_101,MPN_102,MPN_103,MPN_104,MPN_105,MPN_106,MPN_107,MPN_108,MPN_109,MPN_110,MPN_111,MPN_112,MPN_113,MPN_114,MPN_115,MPN_116,MPN_117,MPN_118,MPN_119,MPN_120,MPN_121,MPN_122,MPN_123,MPN_124,MPN_125,MPN_126,MPN_127,MPN_128,MPN_129,MPN_130,MPN_131,MPN_132,MPN_133,MPN_134,MPN_135,MPN_136,MPN_137,MPN_138,MPN_139,MPN_140,MPN_141,MPN_142,MPN_143,MPN_144,MPN_145,MPN_146,MPN_147,MPN_148,MPN_149,MPN_150,MPN_151,MPN_152,MPN_153,MPN_154,MPN_155,MPN_156,MPN_157,MPN_158,MPN_159,MPN_160,MPN_161,MPN_162,MPN_163,MPN_164,MPN_165,MPN_166,MPN_167,MPN_168,MPN_169,MPN_170,MPN_171,MPN_172,MPN_173,MPN_174,MPN_175,MPN_176,MPN_177,MPN_178,MPN_179,MPN_180,MPN_181,MPN_182,MPN_183,MPN_184,MPN_185,MPN_186,MPN_187,MPN_188,MPN_189,MPN_190,MPN_191,MPN_192,MPN_193,MPN_194,MPN_195,MPN_196,MPN_197,MPN_198,MPN_199,MPN_200,MPN_201,MPN_202,MPN_203,MPN_204,MPN_205,MPN_206,MPN_207,MPN_208,MPN_209,MPN_210,MPN_211,MPN_212,MPN_213,MPN_214,MPN_215,MPN_216,MPN_217,MPN_218,MPN_219,MPN_220,MPN_221,MPN_222,MPN_223,MPN_224,MPN_225,MPN_226,MPN_227,MPN_228,MPN_229,MPN_230,MPN_231,MPN_232,MPN_233,MPN_234,MPN_235,MPN_236,MPN_237,MPN_238,MPN_239,MPN_240,MPN_241,MPN_242,MPN_243,MPN_244,MPN_245,MPN_246,MPN_247,MPN_248,MPN_249,MPN_250,MPN_251,MPN_252,MPN_253,MPN_254,MPN_255,MPN_256,MPN_257,MPN_258,MPN_259,MPN_260,MPN_261,MPN_262,MPN_263,MPN_264,MPN_265,MPN_266,MPN_267,MPN_268,MPN_269,MPN_270,MPN_271,MPN_272,MPN_273,MPN_274,MPN_275,MPN_276,MPN_277,MPN_278,MPN_279,MPN_280,MPN_281,MPN_282,MPN_283,MPN_284,MPN_285,MPN_286,MPN_287,MPN_288,MPN_289,MPN_290,MPN_291,MPN_292,MPN_293,MPN_294,MPN_295,MPN_296,MPN_297,MPN_298,MPN_299,MPN_300,MPN_301,MPN_302,MPN_303,MPN_304,MPN_305,MPN_306,MPN_307,MPN_308,MPN_309,MPN_310,MPN_311,MPN_312,MPN_313,MPN_314,MPN_315,MPN_316,MPN_317,MPN_318,MPN_319,MPN_320,MPN_321,MPN_322,MPN_323,MPN_324,MPN_325,MPN_326,MPN_327,MPN_328,MPN_329,MPN_330,MPN_331,MPN_332,MPN_333,MPN_334,MPN_335,MPN_336,MPN_337,MPN_338,MPN_339,MPN_340,MPN_341,MPN_342,MPN_343,MPN_344,MPN_345,MPN_346,MPN_347,MPN_348,MPN_349,MPN_350,MPN_351,MPN_352,MPN_353,MPN_354,MPN_355,MPN_356,MPN_357,MPN_358,MPN_359,MPN_360,MPN_361,MPN_362,MPN_363,MPN_364,MPN_365,MPN_366,MPN_367,MPN_368,MPN_369,MPN_370,MPN_371,MPN_372,MPN_373,MPN_374,MPN_375,MPN_376,MPN_377,MPN_378,MPN_379,MPN_380,MPN_381,MPN_382,MPN_383,MPN_384,MPN_385,MPN_386,MPN_387,MPN_388,MPN_389,MPN_390,MPN_391,MPN_392,MPN_393,MPN_394,MPN_395,MPN_396,MPN_397,MPN_398,MPN_399,MPN_400,MPN_401,MPN_402,MPN_403,MPN_404,MPN_405,MPN_406,MPN_407,MPN_408,MPN_409,MPN_410,MPN_411,MPN_412,MPN_413,MPN_414,MPN_415,MPN_416,MPN_417,MPN_418,MPN_419,MPN_420,MPN_421,MPN_422,MPN_423,MPN_424,MPN_425,MPN_426,MPN_427,MPN_428,MPN_429,MPN_430,MPN_431,MPN_432,MPN_433,MPN_434,MPN_435,MPN_436,MPN_437,MPN_438,MPN_439,MPN_440,MPN_441,MPN_442,MPN_443,MPN_444,MPN_445,MPN_446,MPN_447,MPN_448,MPN_449,MPN_450,MPN_451,MPN_452,MPN_453,MPN_454,MPN_455,MPN_456,MPN_457,MPN_458,MPN_459,MPN_460,MPN_461,MPN_462,MPN_463,MPN_464,MPN_465,MPN_466,MPN_467,MPN_468,MPN_469,MPN_470,MPN_471,MPN_472,MPN_473,MPN_474,MPN_475,MPN_476,MPN_477,MPN_478,MPN_479,MPN_480,MPN_481,MPN_482,MPN_483,MPN_484,MPN_485,MPN_486,MPN_487,MPN_488,MPN_489,MPN_490,MPN_491,MPN_492,MPN_493,MPN_494,MPN_495,MPN_496,MPN_497,MPN_498,MPN_499,MPN_500,MPN_501,MPN_502,MPN_503,MPN_504,MPN_505,MPN_506,MPN_507,MPN_508,MPN_509,MPN_510,MPN_511,MPN_512,MPN_513,MPN_514,MPN_515,MPN_516,MPN_517,MPN_518,MPN_519,MPN_520,MPN_521,MPN_522,MPN_523,MPN_524,MPN_525,MPN_526,MPN_527,MPN_528,MPN_529,MPN_530,MPN_531,MPN_532,MPN_533,MPN_534,MPN_535,MPN_536,MPN_537,MPN_538,MPN_539,MPN_540,MPN_541,MPN_542,MPN_543,MPN_544,MPN_545,MPN_546,MPN_547,MPN_548,MPN_549,MPN_550,MPN_551,MPN_552,MPN_553,MPN_554,MPN_555,MPN_556,MPN_557,MPN_558,MPN_559,MPN_560,MPN_561,MPN_562,MPN_563,MPN_564,MPN_565,MPN_566,MPN_567,MPN_568,MPN_569,MPN_570,MPN_571,MPN_572,MPN_573,MPN_574,MPN_575,MPN_576,MPN_577,MPN_578,MPN_579,MPN_580,MPN_581,MPN_582,MPN_583,MPN_584,MPN_585,MPN_586,MPN_587,MPN_588,MPN_589,MPN_590,MPN_591,MPN_592,MPN_593,MPN_594,MPN_595,MPN_596,MPN_597,MPN_598,MPN_599,MPN_600,MPN_601,MPN_602,MPN_603,MPN_604,MPN_605,MPN_606,MPN_607,MPN_608,MPN_609,MPN_610,MPN_611,MPN_612,MPN_613,MPN_614,MPN_615,MPN_616,MPN_617,MPN_618,MPN_619,MPN_620,MPN_621,MPN_622,MPN_623,MPN_624,MPN_625,MPN_626,MPN_627,MPN_628,MPN_629,MPN_630,MPN_631,MPN_632,MPN_633,MPN_634,MPN_635,MPN_636,MPN_637,MPN_638,MPN_639,MPN_640,MPN_641,MPN_642,MPN_643,MPN_644,MPN_645,MPN_646,MPN_647,MPN_648,MPN_649,MPN_650,MPN_651,MPN_652,MPN_653,MPN_654,MPN_655,MPN_656,MPN_657,MPN_658,MPN_659,MPN_660,MPN_661,MPN_662,MPN_663,MPN_664,MPN_665,MPN_666,MPN_667,MPN_668,MPN_669,MPN_670,MPN_671,MPN_672,MPN_673,MPN_674,MPN_675,MPN_676,MPN_677,MPN_678,MPN_679,MPN_680,MPN_681,MPN_682,MPN_683,MPN_684,MPN_685,MPN_686,MPN_687,MPN_688,MPN_689,MPN_690,MPN_691,MPN_692,MPN_693,MPN_694,MPN_695,MPN_696,MPN_697,MPN_698,MPN_699,MPN_700,MPN_701,MPN_702,MPN_703,MPN_704,MPN_705,MPN_706,MPN_707,MPN_708,MPN_709,MPN_710,MPN_711,MPN_712,MPN_713,MPN_714,MPN_715,MPN_716,MPN_717,MPN_718,MPN_719,MPN_720,MPN_721,MPN_722,MPN_723,MPN_724,MPN_725,MPN_726,MPN_727,MPN_728,MPN_729,MPN_730,MPN_731,MPN_732,MPN_733,MPN_734,MPN_735,MPN_736,MPN_737,MPN_738,MPN_739,MPN_740,MPN_741,MPN_742,MPN_743,MPN_744,MPN_745,MPN_746,MPN_747,MPN_748,MPN_749,MPN_750,MPN_751,MPN_752,MPN_753,MPN_754,MPN_755,MPN_756,MPN_757,MPN_758,MPN_759,MPN_760,MPN_761,MPN_762,MPN_763,MPN_764,MPN_765,MPN_766,MPN_767,MPN_768
0,1,3.0,Needs hose clamps,Needs metal hose clamps not plastic ties.... C...,B00004YWK2,B00004YWK2,AFFPAJDCW7NSKE4FZWBRWETUKZ2A,2023-02-18 02:32:06.278,0,True,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,108,18,NaT,-0.020346,0.019204,0.020958,-0.048550,0.010455,-0.023150,0.011861,0.002191,0.049635,-0.049258,-0.003276,-0.020520,0.074631,-0.015810,0.001498,-0.060225,-0.002687,0.050768,-0.068025,-0.034828,-0.000118,0.027718,-0.006355,-0.019290,-0.033741,0.025990,0.007909,-0.012121,0.068816,-0.043374,0.005293,0.042930,-0.028887,0.057143,0.000002,-0.052232,0.021237,-0.013935,-0.023606,0.011921,-0.031931,-0.105582,0.018860,0.026198,-0.001819,-0.030436,0.020978,0.011215,0.078170,-0.005116,-0.016194,0.051405,0.025463,-0.038439,-0.040521,-0.001979,-0.035835,0.020465,0.043956,-0.055799,0.002948,-0.027729,-0.046824,0.018722,-0.017408,0.004874,-0.065545,-0.099649,-0.004110,0.000803,-0.019361,-0.009347,-0.038468,0.003206,-0.015416,0.051319,0.027042,-0.012283,0.007180,0.006457,-0.046992,-0.008497,-0.034123,0.008577,0.048844,0.022736,-0.028794,-0.013942,-0.019181,0.051604,-0.034967,-0.053583,0.071189,-0.028962,-0.002795,0.006924,-0.075170,0.012387,0.023076,-0.026535,-0.011555,0.020832,0.122218,-0.031621,-0.074569,0.013045,-0.017058,0.043518,0.005754,-0.006362,-0.070963,-0.027974,0.014041,0.036176,-0.002791,0.004679,0.036574,0.013307,0.019674,0.026793,0.003584,0.002273,0.040892,-0.017804,-0.010935,-0.007564,0.008953,0.077088,0.003402,0.051220,-0.020733,0.004902,-0.010860,-0.030557,0.022424,0.050999,0.014900,0.016038,-0.038588,0.013102,0.030548,-0.012919,-0.016714,0.030111,0.019776,-0.002659,0.044500,0.007856,0.042420,-0.028017,-0.050284,0.007284,-0.050786,-0.026086,-0.045517,0.054016,0.046918,-0.060553,-0.015031,-0.020624,0.002815,0.021348,-0.013570,-0.061204,0.023428,0.009611,0.001607,0.012948,-0.028202,-0.019041,0.066902,0.020027,0.000941,0.026236,-0.054353,-0.047180,0.013241,0.017434,-0.023551,0.059500,0.017026,0.001188,0.000827,-0.021294,0.016824,-0.004551,-0.077701,0.050165,-0.039039,-0.003652,0.007925,0.083881,-0.102858,-0.007530,-0.018349,0.077755,0.053482,0.001282,-0.011584,0.033941,-0.006604,-0.020556,0.002311,0.026141,0.025106,0.067033,-0.054003,0.012858,-0.017309,-0.010149,0.006874,0.034138,-0.040873,0.059993,0.008027,0.042367,-0.000520,0.018184,0.022619,-0.015025,-0.025349,0.021313,0.041991,0.010304,0.048638,0.036262,0.013414,-0.011639,-0.048946,0.001849,0.017770,0.002848,-0.012079,-0.041242,-0.012336,0.012496,0.030874,0.064980,0.047722,-0.030013,0.014823,0.023986,0.002250,-0.028753,0.073951,-0.033580,-0.002914,0.047404,0.064377,0.020786,0.038288,0.002870,0.016127,0.036992,0.006282,0.010490,-0.000660,0.029534,0.001621,-0.037640,-0.015214,-0.018564,0.039863,-0.009938,0.036558,0.010347,0.050889,-0.038888,0.007673,0.000733,0.028417,-0.018421,-0.002392,-0.026720,-0.029961,0.020658,-0.018756,0.032256,-0.046834,0.031517,-0.007795,-0.008041,-0.063795,-0.030012,0.015715,0.081372,-0.011425,-0.015643,-0.032685,-0.002431,0.029829,-0.025216,0.010316,0.026206,-0.026897,0.068406,-0.025451,-0.019691,0.027681,-0.061836,-0.008898,0.045170,-0.060768,0.002642,0.008372,-0.032318,0.042693,0.070368,-0.054867,-0.042584,0.010940,-0.030711,0.011105,0.006577,0.039127,0.011399,0.023375,-0.030560,0.054252,0.049763,0.042989,0.013824,-0.023519,-0.034775,0.011375,0.011689,-0.023059,-0.042294,0.027314,0.063762,0.009345,0.080754,0.005995,-0.003632,-0.018753,-0.034781,0.048438,-0.036787,-0.011674,0.016120,-0.015761,-0.044674,-0.052388,0.007894,-0.011237,0.038927,-0.002534,0.028439,-0.001437,0.022519,0.049705,-0.005265,-0.049312,0.019802,-0.004744,0.071941,0.048811,-0.047298,-0.023361,-0.027425,-0.030405,-0.068113,-0.013518,0.004904,-0.044254,0.061260,-0.016272,-0.007539,-0.012243,-0.065407,-0.032986,0.011887,-0.029341,-0.009118,-0.012217,0.040658,0.017531,-0.009402,0.044583,-0.012749,0.028781,9.389830e-02,0.022243,-0.025207,0.024888,0.017391,0.050527,0.040893,0.003298,-0.030715,-0.021907,0.014260,-0.025571,-0.042183,-0.006053,-0.033627,0.026815,-0.043952,-0.005431,0.039131,0.022325,0.038166,-0.105138,-0.036234,-0.013844,0.003204,0.045037,0.016270,0.032014,-0.029905,0.104686,0.034207,0.001953,0.011294,-0.037928,0.012603,0.064313,0.012848,-0.073746,-0.053065,-0.021103,-0.006946,0.004527,-0.041195,0.027354,-0.058284,0.027795,-0.053927,0.013098,0.026805,-0.021226,-0.034664,-0.005785,0.021088,-0.025494,-0.027546,-0.033198,-0.060911,0.005368,0.014500,0.050322,0.015364,0.045028,-0.004091,0.014705,-0.036689,-0.016282,0.029514,-0.002315,-0.084810,-0.009560,0.019806,0.054415,0.045054,-0.027018,0.009128,0.000876,0.036589,-0.000366,-0.003469,-0.061288,0.041493,0.011100,-0.005665,0.104944,-0.071706,0.023882,-0.043406,-0.070634,-0.016280,0.011770,-0.035431,-0.015162,0.040148,0.025058,-0.065873,0.004461,0.010043,0.022628,0.014388,0.041263,-0.005326,-0.033439,-0.047451,0.046491,0.041580,0.062953,-0.029464,-0.004056,0.058195,-0.005025,-0.034257,0.015677,-0.085501,-0.028438,0.104033,0.039643,-0.008929,-0.026063,-0.030057,0.005888,-0.006245,0.012587,0.019186,0.000287,-0.022956,0.002442,-0.063684,-0.016802,0.029544,0.033995,-0.008025,-0.008022,0.039943,-0.029523,-0.010972,-0.033868,-0.012106,-0.000359,-0.020558,0.015276,0.023930,-0.031396,-0.053176,0.033094,-0.033118,0.012722,0.023820,-0.067952,-0.022901,-0.045360,-0.031273,0.044245,-0.007999,0.006731,-0.034108,0.019653,0.040311,-0.020081,-0.010332,-0.035949,0.001701,-0.052824,-0.001794,0.065588,0.058367,0.011123,-0.027171,-0.016611,0.044290,0.003672,-0.109192,0.002914,0.054213,-0.022975,-4.537978e-33,-0.084671,-0.009206,-0.032483,0.002768,-0.005519,0.017573,-0.044898,0.023067,-0.030664,-0.019662,0.018532,-0.020976,-0.012494,0.059721,0.008697,-0.016298,0.024957,-0.004551,-0.013863,-0.038994,-0.042065,0.006918,-0.039609,0.081100,-0.033648,0.023950,-0.056235,0.029949,0.050691,0.006441,-0.011175,0.012565,-0.020883,-0.010401,-0.020942,0.040821,-0.097004,-0.001711,0.019140,-0.012686,0.043686,0.040660,0.003233,0.029180,0.039921,-0.027847,0.031638,0.032072,0.039567,-0.003032,0.015010,0.037550,0.027108,-0.015443,-0.012890,0.013283,0.040965,-0.049229,0.018515,-0.016822,-0.063214,-0.010951,0.036861,-0.076880,-0.025991,-0.027763,-0.103462,-0.030598,-0.016911,0.022471,-0.009833,-0.005950,0.046689,-0.064021,-0.045196,-0.003733,0.007174,-0.007640,-0.018557,0.031850,0.010014,0.004040,-0.037885,-0.044053,0.005207,-0.071541,-0.032523,0.006458,-0.031996,0.042111,0.058349,-0.044562,-0.026206,0.027216,0.006227,0.022254,0.034981,-0.009523,0.025005,0.016324,-0.010948,0.010191,-0.036949,-0.009086,0.048397,0.024607,0.021290,-0.003285,-0.000987,-0.007296,0.018380,0.013400,0.036833,-0.022981,-0.057515,-0.023193,-0.027240,0.010666,0.016400,-0.016398,0.032463,0.090374,-0.015504,0.026349,0.006136,-0.002853,0.012939,-0.049611,0.046681,0.000943,-0.009725,0.014872,2.322044e-07,-0.035863,0.016213,-0.007458,0.066209,-0.006664,-0.003122,-0.042244,-0.019812,-0.074418,0.001744,-0.027820,0.001961,0.007776,0.072272,-0.045673,-0.033433,0.090937,-0.020227,-0.028647,-0.028231,0.050625,0.050130,0.041781,0.033818,0.005371,-0.019499,-0.027083,-0.009976,0.038383,0.018382,0.052832,-0.013003,-0.012362,0.107628,-0.048151,0.020068,0.018094,-0.052215,0.006651,-0.051554,0.003454,-0.016251,0.025642,-0.039286,0.008837,-0.051004,-0.015622,0.024724,-0.031746,0.028445,0.006061,0.088971,0.018175,-0.041762,0.015042,0.041467,-0.040350,-0.014341,-0.042898,0.043501,-0.041297,-0.011302,0.013946,-0.024341,0.014390,-0.024299,-0.112248,2.305557e-34,-0.039653,0.052984,-0.019695,-0.011811,0.021838,-0.028240,0.021108,0.034708,-0.016407,0.018476,-0.024001

,review_id,rating,title,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,medium_image_url,medium_image_url_1,medium_image_url_2,medium_image_url_3,medium_image_url_4,medium_image_url_5,medium_image_url_6,medium_image_url_7,medium_image_url_8,medium_image_url_9,medium_image_url_10,medium_image_url_11,medium_image_url_12,medium_image_url_13,medium_image_url_14,medium_image_url_15,medium_image_url_16,medium_image_url_17,medium_image_url_18,medium_image_url_19,medium_image_url_20,medium_image_url_21,medium_image_url_22,medium_image_url_23,medium_image_url_24,medium_image_url_25,medium_image_url_26,medium_image_url_27,text_len,text_words,inter_review_time,MPN_1,MPN_2,MPN_3,MPN_4,MPN_5,MPN_6,MPN_7,MPN_8,MPN_9,MPN_10,MPN_11,MPN_12,MPN_13,MPN_14,MPN_15,MPN_16,MPN_17,MPN_18,MPN_19,MPN_20,MPN_21,MPN_22,MPN_23,MPN_24,MPN_25,MPN_26,MPN_27,MPN_28,MPN_29,MPN_30,MPN_31,MPN_32,MPN_33,MPN_34,MPN_35,MPN_36,MPN_37,MPN_38,MPN_39,MPN_40,MPN_41,MPN_42,MPN_43,MPN_44,MPN_45,MPN_46,MPN_47,MPN_48,MPN_49,MPN_50,MPN_51,MPN_52,MPN_53,MPN_54,MPN_55,MPN_56,MPN_57,MPN_58,MPN_59,MPN_60,MPN_61,MPN_62,MPN_63,MPN_64,MPN_65,MPN_66,MPN_67,MPN_68,MPN_69,MPN_70,MPN_71,MPN_72,MPN_73,MPN_74,MPN_75,MPN_76,MPN_77,MPN_78,MPN_79,MPN_80,MPN_81,MPN_82,MPN_83,MPN_84,MPN_85,MPN_86,MPN_87,MPN_88,MPN_89,MPN_90,MPN_91,MPN_92,MPN_93,MPN_94,MPN_95,MPN_96,MPN_97,MPN_98,MPN_99,MPN_100,MPN_101,MPN_102,MPN_103,MPN_104,MPN_105,MPN_106,MPN_107,MPN_108,MPN_109,MPN_110,MPN_111,MPN_112,MPN_113,MPN_114,MPN_115,MPN_116,MPN_117,MPN_118,MPN_119,MPN_120,MPN_121,MPN_122,MPN_123,MPN_124,MPN_125,MPN_126,MPN_127,MPN_128,MPN_129,MPN_130,MPN_131,MPN_132,MPN_133,MPN_134,MPN_135,MPN_136,MPN_137,MPN_138,MPN_139,MPN_140,MPN_141,MPN_142,MPN_143,MPN_144,MPN_145,MPN_146,MPN_147,MPN_148,MPN_149,MPN_150,MPN_151,MPN_152,MPN_153,MPN_154,MPN_155,MPN_156,MPN_157,MPN_158,MPN_159,MPN_160,MPN_161,MPN_162,MPN_163,MPN_164,MPN_165,MPN_166,MPN_167,MPN_168,MPN_169,MPN_170,MPN_171,MPN_172,MPN_173,MPN_174,MPN_175,MPN_176,MPN_177,MPN_178,MPN_179,MPN_180,MPN_181,MPN_182,MPN_183,MPN_184,MPN_185,MPN_186,MPN_187,MPN_188,MPN_189,MPN_190,MPN_191,MPN_192,MPN_193,MPN_194,MPN_195,MPN_196,MPN_197,MPN_198,MPN_199,MPN_200,MPN_201,MPN_202,MPN_203,MPN_204,MPN_205,MPN_206,MPN_207,MPN_208,MPN_209,MPN_210,MPN_211,MPN_212,MPN_213,MPN_214,MPN_215,MPN_216,MPN_217,MPN_218,MPN_219,MPN_220,MPN_221,MPN_222,MPN_223,MPN_224,MPN_225,MPN_226,MPN_227,MPN_228,MPN_229,MPN_230,MPN_231,MPN_232,MPN_233,MPN_234,MPN_235,MPN_236,MPN_237,MPN_238,MPN_239,MPN_240,MPN_241,MPN_242,MPN_243,MPN_244,MPN_245,MPN_246,MPN_247,MPN_248,MPN_249,MPN_250,MPN_251,MPN_252,MPN_253,MPN_254,MPN_255,MPN_256,MPN_257,MPN_258,MPN_259,MPN_260,MPN_261,MPN_262,MPN_263,MPN_264,MPN_265,MPN_266,MPN_267,MPN_268,MPN_269,MPN_270,MPN_271,MPN_272,MPN_273,MPN_274,MPN_275,MPN_276,MPN_277,MPN_278,MPN_279,MPN_280,MPN_281,MPN_282,MPN_283,MPN_284,MPN_285,MPN_286,MPN_287,MPN_288,MPN_289,MPN_290,MPN_291,MPN_292,MPN_293,MPN_294,MPN_295,MPN_296,MPN_297,MPN_298,MPN_299,MPN_300,MPN_301,MPN_302,MPN_303,MPN_304,MPN_305,MPN_306,MPN_307,MPN_308,MPN_309,MPN_310,MPN_311,MPN_312,MPN_313,MPN_314,MPN_315,MPN_316,MPN_317,MPN_318,MPN_319,MPN_320,MPN_321,MPN_322,MPN_323,MPN_324,MPN_325,MPN_326,MPN_327,MPN_328,MPN_329,MPN_330,MPN_331,MPN_332,MPN_333,MPN_334,MPN_335,MPN_336,MPN_337,MPN_338,MPN_339,MPN_340,MPN_341,MPN_342,MPN_343,MPN_344,MPN_345,MPN_346,MPN_347,MPN_348,MPN_349,MPN_350,MPN_351,MPN_352,MPN_353,MPN_354,MPN_355,MPN_356,MPN_357,MPN_358,MPN_359,MPN_360,MPN_361,MPN_362,MPN_363,MPN_364,MPN_365,MPN_366,MPN_367,MPN_368,MPN_369,MPN_370,MPN_371,MPN_372,MPN_373,MPN_374,MPN_375,MPN_376,MPN_377,MPN_378,MPN_379,MPN_380,MPN_381,MPN_382,MPN_383,MPN_384,MPN_385,MPN_386,MPN_387,MPN_388,MPN_389,MPN_390,MPN_391,MPN_392,MPN_393,MPN_394,MPN_395,MPN_396,MPN_397,MPN_398,MPN_399,MPN_400,MPN_401,MPN_402,MPN_403,MPN_404,MPN_405,MPN_406,MPN_407,MPN_408,MPN_409,MPN_410,MPN_411,MPN_412,MPN_413,MPN_414,MPN_415,MPN_416,MPN_417,MPN_418,MPN_419,MPN_420,MPN_421,MPN_422,MPN_423,MPN_424,MPN_425,MPN_426,MPN_427,MPN_428,MPN_429,MPN_430,MPN_431,MPN_432,MPN_433,MPN_434,MPN_435,MPN_436,MPN_437,MPN_438,MPN_439,MPN_440,MPN_441,MPN_442,MPN_443,MPN_444,MPN_445,MPN_446,MPN_447,MPN_448,MPN_449,MPN_450,MPN_451,MPN_452,MPN_453,MPN_454,MPN_455,MPN_456,MPN_457,MPN_458,MPN_459,MPN_460,MPN_461,MPN_462,MPN_463,MPN_464,MPN_465,MPN_466,MPN_467,MPN_468,MPN_469,MPN_470,MPN_471,MPN_472,MPN_473,MPN_474,MPN_475,MPN_476,MPN_477,MPN_478,MPN_479,MPN_480,MPN_481,MPN_482,MPN_483,MPN_484,MPN_485,MPN_486,MPN_487,MPN_488,MPN_489,MPN_490,MPN_491,MPN_492,MPN_493,MPN_494,MPN_495,MPN_496,MPN_497,MPN_498,MPN_499,MPN_500,MPN_501,MPN_502,MPN_503,MPN_504,MPN_505,MPN_506,MPN_507,MPN_508,MPN_509,MPN_510,MPN_511,MPN_512,MPN_513,MPN_514,MPN_515,MPN_516,MPN_517,MPN_518,MPN_519,MPN_520,MPN_521,MPN_522,MPN_523,MPN_524,MPN_525,MPN_526,MPN_527,MPN_528,MPN_529,MPN_530,MPN_531,MPN_532,MPN_533,MPN_534,MPN_535,MPN_536,MPN_537,MPN_538,MPN_539,MPN_540,MPN_541,MPN_542,MPN_543,MPN_544,MPN_545,MPN_546,MPN_547,MPN_548,MPN_549,MPN_550,MPN_551,MPN_552,MPN_553,MPN_554,MPN_555,MPN_556,MPN_557,MPN_558,MPN_559,MPN_560,MPN_561,MPN_562,MPN_563,MPN_564,MPN_565,MPN_566,MPN_567,MPN_568,MPN_569,MPN_570,MPN_571,MPN_572,MPN_573,MPN_574,MPN_575,MPN_576,MPN_577,MPN_578,MPN_579,MPN_580,MPN_581,MPN_582,MPN_583,MPN_584,MPN_585,MPN_586,MPN_587,MPN_588,MPN_589,MPN_590,MPN_591,MPN_592,MPN_593,MPN_594,MPN_595,MPN_596,MPN_597,MPN_598,MPN_599,MPN_600,MPN_601,MPN_602,MPN_603,MPN_604,MPN_605,MPN_606,MPN_607,MPN_608,MPN_609,MPN_610,MPN_611,MPN_612,MPN_613,MPN_614,MPN_615,MPN_616,MPN_617,MPN_618,MPN_619,MPN_620,MPN_621,MPN_622,MPN_623,MPN_624,MPN_625,MPN_626,MPN_627,MPN_628,MPN_629,MPN_630,MPN_631,MPN_632,MPN_633,MPN_634,MPN_635,MPN_636,MPN_637,MPN_638,MPN_639,MPN_640,MPN_641,MPN_642,MPN_643,MPN_644,MPN_645,MPN_646,MPN_647,MPN_648,MPN_649,MPN_650,MPN_651,MPN_652,MPN_653,MPN_654,MPN_655,MPN_656,MPN_657,MPN_658,MPN_659,MPN_660,MPN_661,MPN_662,MPN_663,MPN_664,MPN_665,MPN_666,MPN_667,MPN_668,MPN_669,MPN_670,MPN_671,MPN_672,MPN_673,MPN_674,MPN_675,MPN_676,MPN_677,MPN_678,MPN_679,MPN_680,MPN_681,MPN_682,MPN_683,MPN_684,MPN_685,MPN_686,MPN_687,MPN_688,MPN_689,MPN_690,MPN_691,MPN_692,MPN_693,MPN_694,MPN_695,MPN_696,MPN_697,MPN_698,MPN_699,MPN_700,MPN_701,MPN_702,MPN_703,MPN_704,MPN_705,MPN_706,MPN_707,MPN_708,MPN_709,MPN_710,MPN_711,MPN_712,MPN_713,MPN_714,MPN_715,MPN_716,MPN_717,MPN_718,MPN_719,MPN_720,MPN_721,MPN_722,MPN_723,MPN_724,MPN_725,MPN_726,MPN_727,MPN_728,MPN_729,MPN_730,MPN_731,MPN_732,MPN_733,MPN_734,MPN_735,MPN_736,MPN_737,MPN_738,MPN_739,MPN_740,MPN_741,MPN_742,MPN_743,MPN_744,MPN_745,MPN_746,MPN_747,MPN_748,MPN_749,MPN_750,MPN_751,MPN_752,MPN_753,MPN_754,MPN_755,MPN_756,MPN_757,MPN_758,MPN_759,MPN_760,MPN_761,MPN_762,MPN_763,MPN_764,MPN_765,MPN_766,MPN_767,MPN_768
105993,105994,5.0,Very well constructed,Purchased to replace plastic cups that have sh...,B0BZPYRHBV,B0CHS3BKCJ,AFVITXRPGQDGKSZQYEHUTUJ5ASUA,2023-05-26 23:41:28.224,0,True,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,60,9,5 days 12:40:17.586000,0.050479,-0.016503,-0.015042,-0.016718,-0.044396,0.001988,0.035471,-0.008197,-0.023188,0.016285,0.020096,-0.023186,0.017341,0.020997,-0.028126,-0.043734,-0.000575,0.013992,0.051515,0.006197,-0.021589,0.005685,0.008013,0.052006,0.009623,-0.002488,0.017406,-0.030869,-0.019425,-0.056804,0.081333,-0.014795,-0.047743,-0.019969,0.000001,0.006191,0.071854,0.033149,-0.036579,-0.003232,0.002296,0.024319,-0.019944,0.054985,0.014985,-0.047659,-0.019068,0.008317,-0.028510,-0.011876,-0.013573,0.015120,0.027306,-0.035873,0.095873,-0.032850,0.026219,-0.007832,0.012434,0.002683,0.020399,0.037849,-0.015850,-0.020156,-0.067929,-0.018435,0.020220,-0.023072,0.008049,0.017166,0.012053,0.024499,0.005317,0.053763,-0.010433,0.066529,-0.013331,-0.051177,0.042950,-0.036875,-0.005167,0.055412,-0.026842,0.029754,-0.010476,-0.013514,-0.001717,0.021667,0.046620,-0.037641,0.017905,-0.005207,0.004329,-0.044976,0.100168,-0.022168,-0.018339,0.084296,0.024237,0.011897,-0.017376,0.059038,-0.029696,0.001806,-0.097840,-0.082665,0.018055,-8.771079e-07,-0.044242,0.024959,-0.061992,-0.048111,0.034485,0.048187,0.008215,-0.008898,0.027317,-0.002559,-0.058990,0.042173,0.039317,0.012794,0.024702,0.029037,-0.044878,0.110418,-0.044408,-0.016854,-0.040643,0.030915,-0.003488,0.021058,0.025617,0.008353,-0.011551,0.072793,-0.037582,-0.057422,-0.065305,-0.018736,0.018417,-0.041849,-0.024512,0.035125,-0.015104,-0.019396,0.027314,0.020645,0.028544,0.029608,-0.012330,-0.032262,0.014311,0.057535,-0.000386,-0.025596,-0.003201,-0.026772,0.029397,-0.049053,-0.031264,-0.063856,-0.053949,-0.014046,-0.065487,0.039372,-0.008147,0.025356,-0.039146,-0.018260,0.029613,-0.022858,-0.015513,0.036613,0.101887,-0.011297,-0.094583,-0.018324,-0.019362,-0.085175,0.006372,-0.033133,0.003227,-0.026655,-0.007927,0.033946,-0.040836,-0.050943,-0.016462,-0.048546,0.002198,0.015150,0.017932,0.016622,0.034206,0.001256,-0.030068,0.066228,-0.102728,-0.002649,0.014620,0.004067,0.091623,0.060782,-0.011271,-0.042691,0.019137,-0.004819,-0.002465,-0.017689,0.035625,0.004622,-0.036183,0.019712,0.001918,0.059073,-0.011741,0.058888,0.020793,0.090335,-0.002069,-0.023091,0.018046,0.005050,0.038769,0.023512,0.029967,0.022802,-0.036613,0.012073,0.017521,0.048743,0.048422,0.000141,-0.041395,0.103880,-0.015021,0.008107,-0.020667,-0.088807,-0.013032,-0.067225,0.022977,-0.000246,0.013158,0.021812,0.047023,0.002059,-0.032957,-0.016388,-0.012672,0.002794,0.051283,-0.060995,-0.067035,0.034460,0.005792,0.033039,0.024855,0.081996,-0.000437,-0.033373,-0.031892,0.002998,0.044665,-0.059117,-0.011262,0.012841,0.008894,0.007605,-0.007817,0.006509,0.009366,-0.010366,0.001481,0.021939,0.003591,-0.000336,-0.037868,0.015465,-0.003824,-0.000727,-0.006905,0.021177,0.015692,0.015949,-0.056892,-0.022209,-0.045823,0.054299,0.058927,-0.005694,0.007097,-0.048984,0.002504,-0.036229,0.000091,0.069675,0.035755,0.015101,-0.048552,-0.047371,0.013781,0.002862,-0.043139,-0.047949,-0.020098,-0.036608,-0.008945,-0.048239,0.006535,0.019672,-0.027967,-0.013924,0.047615,-0.024905,-0.032773,0.010371,-0.005325,0.021390,0.023357,0.047305,-0.019873,0.020281,0.005767,0.004729,-0.058401,-0.004228,0.005657,0.004433,-0.006644,-0.021808,0.009338,0.015206,0.080854,-0.065137,-0.053704,-0.025632,-0.069398,-0.021235,0.034965,-0.031652,0.032123,-0.094551,0.014382,-0.027604,-0.057873,0.031815,-0.124270,0.066586,0.038799,0.033667,0.001154,-0.043651,-0.063345,0.039329,-0.011152,-0.005643,-0.030277,0.036884,-0.000404,-0.027469,0.036004,-0.015651,-0.028522,0.059119,0.024910,0.005526,0.061699,-0.006517,0.028348,0.031356,-0.006281,-0.006305,-0.000860,0.025510,0.016319,0.036273,0.022494,0.017858,-0.037480,-0.040154,-0.012919,0.004846,-0.056550,-0.040209,-0.016054,-0.056306,-0.062617,-0.037101,0.025609,-0.010574,0.004039,0.025374,0.058750,0.014463,0.033447,-0.014089,0.003450,0.005278,-0.031963,-0.063885,-0.104531,0.048708,0.019572,-0.033812,-0.001842,0.002716,-0.030348,-0.008637,-0.015881,-0.074267,0.009863,0.023323,0.005533,0.006490,-0.004862,0.070094,0.061391,-0.097246,0.013227,0.022441,-0.012908,0.030989,-0.018663,-0.023083,-0.034852,0.013932,0.015590,0.014079,-0.043565,-0.021320,-0.004544,0.017187,-0.029273,0.078145,0.021600,-0.054848,0.001650,0.023850,0.024862,-0.014654,-0.013252,-0.009392,0.009558,0.019542,0.011882,0.076256,-0.009383,-0.061735,0.018679,-0.027378,-0.013248,0.013280,0.062604,-0.042732,0.010159,0.024150,0.001883,0.029974,0.045000,0.032172,-0.049672,-0.008945,0.017773,-0.051887,-0.025540,0.026709,-0.036485,-0.052335,0.009179,0.008508,-0.045466,-0.005808,-0.002821,-0.062680,-0.018725,-0.022617,-0.042352,0.037738,-0.028180,-0.038138,-0.011286,0.086366,0.033967,0.062042,0.055898,-0.069713,0.028951,-0.034017,0.027543,-0.042364,-0.015507,-0.071790,-0.008807,0.077501,0.032263,-0.062392,0.025856,-0.003925,-0.006636,0.006004,0.029166,0.037835,0.005033,0.040797,-0.036098,0.051996,0.000299,0.002748,0.054991,0.031998,-0.046535,0.001940,0.020338,-0.040638,-0.019022,-0.113788,0.004452,-0.021969,-0.006109,-0.014131,-0.001404,-0.016759,0.034389,-0.030725,0.017027,0.035821,-0.044404,0.032302,-0.036391,-0.017835,-0.026306,0.028464,-0.004028,0.088797,-0.035502,-0.014230,0.035115,-0.084971,-0.007751,0.036641,0.016982,-0.007623,0.076583,0.021177,-0.027852,0.068834,0.030228,-0.006147,-0.032914,0.055210,0.002463,0.007615,-0.036408,-4.928854e-33,0.016286,-0.045831,-0.041734,-0.065535,-0.005313,0.003308,-0.029960,-0.046649,0.026723,0.025047,0.046164,-0.022460,0.027559,-0.022971,0.023052,-0.077388,0.053767,0.015595,0.047909,-0.030731,-0.003151,-0.041086,-0.025940,0.031438,0.045858,0.001610,0.037868,-0.016207,0.048742,0.021693,0.038317,0.009176,-0.007746,0.061633,0.010095,0.081551,-0.014618,-0.022839,-0.012020,0.021754,-0.041035,-0.008143,-0.040178,0.002873,0.008014,0.007583,-0.033504,0.028233,0.015985,0.027855,0.042161,-0.031563,-0.023332,0.035564,0.033107,-0.038648,0.012582,0.036603,0.042696,0.003814,0.000692,0.005328,-0.031013,-0.019775,-0.041831,-0.030074,-0.014537,0.043193,0.055046,0.004101,0.045120,-0.047322,0.035055,0.014319,0.024195,-0.055641,-0.026526,0.000399,-0.001566,0.006918,-0.000468,-0.004033,0.063536,-0.019742,-0.091634,-0.041159,-0.012643,0.010031,0.021353,0.017097,-0.000907,-0.033868,-0.018386,0.051606,-0.013188,-0.007231,0.027985,0.032760,0.004860,0.008764,0.016697,0.008304,-0.057049,0.056534,0.042582,-0.010089,-0.021104,-0.006569,-0.062380,0.042682,-0.009262,0.024269,0.017252,-0.008852,-0.028257,0.015523,-0.011962,-0.054180,0.038363,-0.003137,0.000467,-0.003538,-0.012747,0.011805,0.054669,0.016965,-0.004271,0.013051,0.050586,-0.006269,0.024923,0.039204,2.029915e-07,0.042475,0.035940,0.024884,0.022438,0.019812,-0.028027,0.003943,0.008218,-0.011515,-0.062842,0.036902,-0.010044,0.013252,0.024428,-0.063563,0.008035,-0.012998,-0.038798,-0.013354,0.041242,0.061861,-0.059615,-0.015822,-0.018662,-0.042660,0.022645,0.014376,-0.064389,0.040141,-0.022572,-0.029312,0.029599,0.033012,-0.000333,0.002110,0.005009,0.010241,-0.040549,0.027103,-0.012878,-0.003295,0.003946,0.018147,0.020343,0.053974,-0.023143,0.039792,0.051671,-0.017709,-0.014558,-0.021498,-0.056712,-0.046187,0.022589,0.006203,0.052791,0.014679,-0.010708,0.020554,0.011832,-0.014603,-0.019297,-0.034915,0.055644,-0.020931,-0.055344,-0.024126,1.340556e-34,0.005793,-0.058340,-0.039073,0.011174,-0.002454,-0.019225,-0.003652,0.036732,0.001384,-0.019171,0.025763

In [65]:
df_reviews_mrgEmb.shape

(105998, 809)

In [66]:
df_reviews_mrgEmb.isnull().sum()

review_id    0
rating       0
title        0
text         0
asin         0
            ..
MPN_764      0
MPN_765      0
MPN_766      0
MPN_767      0
MPN_768      0
Length: 809, dtype: int64

In [67]:
df_reviews_mrgEmb.head()

,review_id,rating,title,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,medium_image_url,medium_image_url_1,medium_image_url_2,medium_image_url_3,medium_image_url_4,medium_image_url_5,medium_image_url_6,medium_image_url_7,medium_image_url_8,medium_image_url_9,medium_image_url_10,medium_image_url_11,medium_image_url_12,medium_image_url_13,medium_image_url_14,medium_image_url_15,medium_image_url_16,medium_image_url_17,medium_image_url_18,medium_image_url_19,medium_image_url_20,medium_image_url_21,medium_image_url_22,medium_image_url_23,medium_image_url_24,medium_image_url_25,medium_image_url_26,medium_image_url_27,text_len,text_words,inter_review_time,MPN_1,MPN_2,MPN_3,MPN_4,MPN_5,MPN_6,MPN_7,MPN_8,MPN_9,MPN_10,MPN_11,MPN_12,MPN_13,MPN_14,MPN_15,MPN_16,MPN_17,MPN_18,MPN_19,MPN_20,MPN_21,MPN_22,MPN_23,MPN_24,MPN_25,MPN_26,MPN_27,MPN_28,MPN_29,MPN_30,MPN_31,MPN_32,MPN_33,MPN_34,MPN_35,MPN_36,MPN_37,MPN_38,MPN_39,MPN_40,MPN_41,MPN_42,MPN_43,MPN_44,MPN_45,MPN_46,MPN_47,MPN_48,MPN_49,MPN_50,MPN_51,MPN_52,MPN_53,MPN_54,MPN_55,MPN_56,MPN_57,MPN_58,MPN_59,MPN_60,MPN_61,MPN_62,MPN_63,MPN_64,MPN_65,MPN_66,MPN_67,MPN_68,MPN_69,MPN_70,MPN_71,MPN_72,MPN_73,MPN_74,MPN_75,MPN_76,MPN_77,MPN_78,MPN_79,MPN_80,MPN_81,MPN_82,MPN_83,MPN_84,MPN_85,MPN_86,MPN_87,MPN_88,MPN_89,MPN_90,MPN_91,MPN_92,MPN_93,MPN_94,MPN_95,MPN_96,MPN_97,MPN_98,MPN_99,MPN_100,MPN_101,MPN_102,MPN_103,MPN_104,MPN_105,MPN_106,MPN_107,MPN_108,MPN_109,MPN_110,MPN_111,MPN_112,MPN_113,MPN_114,MPN_115,MPN_116,MPN_117,MPN_118,MPN_119,MPN_120,MPN_121,MPN_122,MPN_123,MPN_124,MPN_125,MPN_126,MPN_127,MPN_128,MPN_129,MPN_130,MPN_131,MPN_132,MPN_133,MPN_134,MPN_135,MPN_136,MPN_137,MPN_138,MPN_139,MPN_140,MPN_141,MPN_142,MPN_143,MPN_144,MPN_145,MPN_146,MPN_147,MPN_148,MPN_149,MPN_150,MPN_151,MPN_152,MPN_153,MPN_154,MPN_155,MPN_156,MPN_157,MPN_158,MPN_159,MPN_160,MPN_161,MPN_162,MPN_163,MPN_164,MPN_165,MPN_166,MPN_167,MPN_168,MPN_169,MPN_170,MPN_171,MPN_172,MPN_173,MPN_174,MPN_175,MPN_176,MPN_177,MPN_178,MPN_179,MPN_180,MPN_181,MPN_182,MPN_183,MPN_184,MPN_185,MPN_186,MPN_187,MPN_188,MPN_189,MPN_190,MPN_191,MPN_192,MPN_193,MPN_194,MPN_195,MPN_196,MPN_197,MPN_198,MPN_199,MPN_200,MPN_201,MPN_202,MPN_203,MPN_204,MPN_205,MPN_206,MPN_207,MPN_208,MPN_209,MPN_210,MPN_211,MPN_212,MPN_213,MPN_214,MPN_215,MPN_216,MPN_217,MPN_218,MPN_219,MPN_220,MPN_221,MPN_222,MPN_223,MPN_224,MPN_225,MPN_226,MPN_227,MPN_228,MPN_229,MPN_230,MPN_231,MPN_232,MPN_233,MPN_234,MPN_235,MPN_236,MPN_237,MPN_238,MPN_239,MPN_240,MPN_241,MPN_242,MPN_243,MPN_244,MPN_245,MPN_246,MPN_247,MPN_248,MPN_249,MPN_250,MPN_251,MPN_252,MPN_253,MPN_254,MPN_255,MPN_256,MPN_257,MPN_258,MPN_259,MPN_260,MPN_261,MPN_262,MPN_263,MPN_264,MPN_265,MPN_266,MPN_267,MPN_268,MPN_269,MPN_270,MPN_271,MPN_272,MPN_273,MPN_274,MPN_275,MPN_276,MPN_277,MPN_278,MPN_279,MPN_280,MPN_281,MPN_282,MPN_283,MPN_284,MPN_285,MPN_286,MPN_287,MPN_288,MPN_289,MPN_290,MPN_291,MPN_292,MPN_293,MPN_294,MPN_295,MPN_296,MPN_297,MPN_298,MPN_299,MPN_300,MPN_301,MPN_302,MPN_303,MPN_304,MPN_305,MPN_306,MPN_307,MPN_308,MPN_309,MPN_310,MPN_311,MPN_312,MPN_313,MPN_314,MPN_315,MPN_316,MPN_317,MPN_318,MPN_319,MPN_320,MPN_321,MPN_322,MPN_323,MPN_324,MPN_325,MPN_326,MPN_327,MPN_328,MPN_329,MPN_330,MPN_331,MPN_332,MPN_333,MPN_334,MPN_335,MPN_336,MPN_337,MPN_338,MPN_339,MPN_340,MPN_341,MPN_342,MPN_343,MPN_344,MPN_345,MPN_346,MPN_347,MPN_348,MPN_349,MPN_350,MPN_351,MPN_352,MPN_353,MPN_354,MPN_355,MPN_356,MPN_357,MPN_358,MPN_359,MPN_360,MPN_361,MPN_362,MPN_363,MPN_364,MPN_365,MPN_366,MPN_367,MPN_368,MPN_369,MPN_370,MPN_371,MPN_372,MPN_373,MPN_374,MPN_375,MPN_376,MPN_377,MPN_378,MPN_379,MPN_380,MPN_381,MPN_382,MPN_383,MPN_384,MPN_385,MPN_386,MPN_387,MPN_388,MPN_389,MPN_390,MPN_391,MPN_392,MPN_393,MPN_394,MPN_395,MPN_396,MPN_397,MPN_398,MPN_399,MPN_400,MPN_401,MPN_402,MPN_403,MPN_404,MPN_405,MPN_406,MPN_407,MPN_408,MPN_409,MPN_410,MPN_411,MPN_412,MPN_413,MPN_414,MPN_415,MPN_416,MPN_417,MPN_418,MPN_419,MPN_420,MPN_421,MPN_422,MPN_423,MPN_424,MPN_425,MPN_426,MPN_427,MPN_428,MPN_429,MPN_430,MPN_431,MPN_432,MPN_433,MPN_434,MPN_435,MPN_436,MPN_437,MPN_438,MPN_439,MPN_440,MPN_441,MPN_442,MPN_443,MPN_444,MPN_445,MPN_446,MPN_447,MPN_448,MPN_449,MPN_450,MPN_451,MPN_452,MPN_453,MPN_454,MPN_455,MPN_456,MPN_457,MPN_458,MPN_459,MPN_460,MPN_461,MPN_462,MPN_463,MPN_464,MPN_465,MPN_466,MPN_467,MPN_468,MPN_469,MPN_470,MPN_471,MPN_472,MPN_473,MPN_474,MPN_475,MPN_476,MPN_477,MPN_478,MPN_479,MPN_480,MPN_481,MPN_482,MPN_483,MPN_484,MPN_485,MPN_486,MPN_487,MPN_488,MPN_489,MPN_490,MPN_491,MPN_492,MPN_493,MPN_494,MPN_495,MPN_496,MPN_497,MPN_498,MPN_499,MPN_500,MPN_501,MPN_502,MPN_503,MPN_504,MPN_505,MPN_506,MPN_507,MPN_508,MPN_509,MPN_510,MPN_511,MPN_512,MPN_513,MPN_514,MPN_515,MPN_516,MPN_517,MPN_518,MPN_519,MPN_520,MPN_521,MPN_522,MPN_523,MPN_524,MPN_525,MPN_526,MPN_527,MPN_528,MPN_529,MPN_530,MPN_531,MPN_532,MPN_533,MPN_534,MPN_535,MPN_536,MPN_537,MPN_538,MPN_539,MPN_540,MPN_541,MPN_542,MPN_543,MPN_544,MPN_545,MPN_546,MPN_547,MPN_548,MPN_549,MPN_550,MPN_551,MPN_552,MPN_553,MPN_554,MPN_555,MPN_556,MPN_557,MPN_558,MPN_559,MPN_560,MPN_561,MPN_562,MPN_563,MPN_564,MPN_565,MPN_566,MPN_567,MPN_568,MPN_569,MPN_570,MPN_571,MPN_572,MPN_573,MPN_574,MPN_575,MPN_576,MPN_577,MPN_578,MPN_579,MPN_580,MPN_581,MPN_582,MPN_583,MPN_584,MPN_585,MPN_586,MPN_587,MPN_588,MPN_589,MPN_590,MPN_591,MPN_592,MPN_593,MPN_594,MPN_595,MPN_596,MPN_597,MPN_598,MPN_599,MPN_600,MPN_601,MPN_602,MPN_603,MPN_604,MPN_605,MPN_606,MPN_607,MPN_608,MPN_609,MPN_610,MPN_611,MPN_612,MPN_613,MPN_614,MPN_615,MPN_616,MPN_617,MPN_618,MPN_619,MPN_620,MPN_621,MPN_622,MPN_623,MPN_624,MPN_625,MPN_626,MPN_627,MPN_628,MPN_629,MPN_630,MPN_631,MPN_632,MPN_633,MPN_634,MPN_635,MPN_636,MPN_637,MPN_638,MPN_639,MPN_640,MPN_641,MPN_642,MPN_643,MPN_644,MPN_645,MPN_646,MPN_647,MPN_648,MPN_649,MPN_650,MPN_651,MPN_652,MPN_653,MPN_654,MPN_655,MPN_656,MPN_657,MPN_658,MPN_659,MPN_660,MPN_661,MPN_662,MPN_663,MPN_664,MPN_665,MPN_666,MPN_667,MPN_668,MPN_669,MPN_670,MPN_671,MPN_672,MPN_673,MPN_674,MPN_675,MPN_676,MPN_677,MPN_678,MPN_679,MPN_680,MPN_681,MPN_682,MPN_683,MPN_684,MPN_685,MPN_686,MPN_687,MPN_688,MPN_689,MPN_690,MPN_691,MPN_692,MPN_693,MPN_694,MPN_695,MPN_696,MPN_697,MPN_698,MPN_699,MPN_700,MPN_701,MPN_702,MPN_703,MPN_704,MPN_705,MPN_706,MPN_707,MPN_708,MPN_709,MPN_710,MPN_711,MPN_712,MPN_713,MPN_714,MPN_715,MPN_716,MPN_717,MPN_718,MPN_719,MPN_720,MPN_721,MPN_722,MPN_723,MPN_724,MPN_725,MPN_726,MPN_727,MPN_728,MPN_729,MPN_730,MPN_731,MPN_732,MPN_733,MPN_734,MPN_735,MPN_736,MPN_737,MPN_738,MPN_739,MPN_740,MPN_741,MPN_742,MPN_743,MPN_744,MPN_745,MPN_746,MPN_747,MPN_748,MPN_749,MPN_750,MPN_751,MPN_752,MPN_753,MPN_754,MPN_755,MPN_756,MPN_757,MPN_758,MPN_759,MPN_760,MPN_761,MPN_762,MPN_763,MPN_764,MPN_765,MPN_766,MPN_767,MPN_768
0,1,3.0,Needs hose clamps,Needs metal hose clamps not plastic ties.... C...,B00004YWK2,B00004YWK2,AFFPAJDCW7NSKE4FZWBRWETUKZ2A,2023-02-18 02:32:06.278,0,True,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,108,18,NaT,-0.020346,0.019204,0.020958,-0.048550,0.010455,-0.023150,0.011861,0.002191,0.049635,-0.049258,-0.003276,-0.020520,0.074631,-0.015810,0.001498,-0.060225,-0.002687,0.050768,-0.068025,-0.034828,-0.000118,0.027718,-0.006355,-0.019290,-0.033741,0.025990,0.007909,-0.012121,0.068816,-0.043374,0.005293,0.042930,-0.028887,0.057143,0.000002,-0.052232,0.021237,-0.013935,-0.023606,0.011921,-0.031931,-0.105582,0.018860,0.026198,-0.001819,-0.030436,0.020978,0.011215,0.078170,-0.005116,-0.016194,0.051405,0.025463,-0.038439,-0.040521,-0.001979,-0.035835,0.020465,0.043956,-0.055799,0.002948,-0.027729,-0.046824,0.018722,-0.017408,0.004874,-0.065545,-0.099649,-0.004110,0.000803,-0.019361,-0.009347,-0.038468,0.003206,-0.015416,0.051319,0.027042,-0.012283,0.007180,0.006457,-0.046992,-0.008497,-0.034123,0.008577,0.048844,0.022736,-0.028794,-0.013942,-0.019181,0.051604,-0.034967,-0.053583,0.071189,-0.028962,-0.002795,0.006924,-0.075170,0.012387,0.023076,-0.026535,-0.011555,0.020832,0.122218,-0.031621,-0.074569,0.013045,-0.017058,0.043518,0.005754,-0.006362,-0.070963,-0.027974,0.014041,0.036176,-0.002791,0.004679,0.036574,0.013307,0.019674,0.026793,0.003584,0.002273,0.040892,-0.017804,-0.010935,-0.007564,0.008953,0.077088,0.003402,0.051220,-0.020733,0.004902,-0.010860,-0.030557,0.022424,0.050999,0.014900,0.016038,-0.038588,0.013102,0.030548,-0.012919,-0.016714,0.030111,0.019776,-0.002659,0.044500,0.007856,0.042420,-0.028017,-0.050284,0.007284,-0.050786,-0.026086,-0.045517,0.054016,0.046918,-0.060553,-0.015031,-0.020624,0.002815,0.021348,-0.013570,-0.061204,0.023428,0.009611,0.001607,0.012948,-0.028202,-0.019041,0.066902,0.020027,0.000941,0.026236,-0.054353,-0.047180,0.013241,0.017434,-0.023551,0.059500,0.017026,0.001188,0.000827,-0.021294,0.016824,-0.004551,-0.077701,0.050165,-0.039039,-0.003652,0.007925,0.083881,-0.102858,-0.007530,-0.018349,0.077755,0.053482,0.001282,-0.011584,0.033941,-0.006604,-0.020556,0.002311,0.026141,0.025106,0.067033,-0.054003,0.012858,-0.017309,-0.010149,0.006874,0.034138,-0.040873,0.059993,0.008027,0.042367,-0.000520,0.018184,0.022619,-0.015025,-0.025349,0.021313,0.041991,0.010304,0.048638,0.036262,0.013414,-0.011639,-0.048946,0.001849,0.017770,0.002848,-0.012079,-0.041242,-0.012336,0.012496,0.030874,0.064980,0.047722,-0.030013,0.014823,0.023986,0.002250,-0.028753,0.073951,-0.033580,-0.002914,0.047404,0.064377,0.020786,0.038288,0.002870,0.016127,0.036992,0.006282,0.010490,-0.000660,0.029534,0.001621,-0.037640,-0.015214,-0.018564,0.039863,-0.009938,0.036558,0.010347,0.050889,-0.038888,0.007673,0.000733,0.028417,-0.018421,-0.002392,-0.026720,-0.029961,0.020658,-0.018756,0.032256,-0.046834,0.031517,-0.007795,-0.008041,-0.063795,-0.030012,0.015715,0.081372,-0.011425,-0.015643,-0.032685,-0.002431,0.029829,-0.025216,0.010316,0.026206,-0.026897,0.068406,-0.025451,-0.019691,0.027681,-0.061836,-0.008898,0.045170,-0.060768,0.002642,0.008372,-0.032318,0.042693,0.070368,-0.054867,-0.042584,0.010940,-0.030711,0.011105,0.006577,0.039127,0.011399,0.023375,-0.030560,0.054252,0.049763,0.042989,0.013824,-0.023519,-0.034775,0.011375,0.011689,-0.023059,-0.042294,0.027314,0.063762,0.009345,0.080754,0.005995,-0.003632,-0.018753,-0.034781,0.048438,-0.036787,-0.011674,0.016120,-0.015761,-0.044674,-0.052388,0.007894,-0.011237,0.038927,-0.002534,0.028439,-0.001437,0.022519,0.049705,-0.005265,-0.049312,0.019802,-0.004744,0.071941,0.048811,-0.047298,-0.023361,-0.027425,-0.030405,-0.068113,-0.013518,0.004904,-0.044254,0.061260,-0.016272,-0.007539,-0.012243,-0.065407,-0.032986,0.011887,-0.029341,-0.009118,-0.012217,0.040658,0.017531,-0.009402,0.044583,-0.012749,0.028781,9.389830e-02,0.022243,-0.025207,0.024888,0.017391,0.050527,0.040893,0.003298,-0.030715,-0.021907,0.014260,-0.025571,-0.042183,-0.006053,-0.033627,0.026815,-0.043952,-0.005431,0.039131,0.022325,0.038166,-0.105138,-0.036234,-0.013844,0.003204,0.045037,0.016270,0.032014,-0.029905,0.104686,0.034207,0.001953,0.011294,-0.037928,0.012603,0.064313,0.012848,-0.073746,-0.053065,-0.021103,-0.006946,0.004527,-0.041195,0.027354,-0.058284,0.027795,-0.053927,0.013098,0.026805,-0.021226,-0.034664,-0.005785,0.021088,-0.025494,-0.027546,-0.033198,-0.060911,0.005368,0.014500,0.050322,0.015364,0.045028,-0.004091,0.014705,-0.036689,-0.016282,0.029514,-0.002315,-0.084810,-0.009560,0.019806,0.054415,0.045054,-0.027018,0.009128,0.000876,0.036589,-0.000366,-0.003469,-0.061288,0.041493,0.011100,-0.005665,0.104944,-0.071706,0.023882,-0.043406,-0.070634,-0.016280,0.011770,-0.035431,-0.015162,0.040148,0.025058,-0.065873,0.004461,0.010043,0.022628,0.014388,0.041263,-0.005326,-0.033439,-0.047451,0.046491,0.041580,0.062953,-0.029464,-0.004056,0.058195,-0.005025,-0.034257,0.015677,-0.085501,-0.028438,0.104033,0.039643,-0.008929,-0.026063,-0.030057,0.005888,-0.006245,0.012587,0.019186,0.000287,-0.022956,0.002442,-0.063684,-0.016802,0.029544,0.033995,-0.008025,-0.008022,0.039943,-0.029523,-0.010972,-0.033868,-0.012106,-0.000359,-0.020558,0.015276,0.023930,-0.031396,-0.053176,0.033094,-0.033118,0.012722,0.023820,-0.067952,-0.022901,-0.045360,-0.031273,0.044245,-0.007999,0.006731,-0.034108,0.019653,0.040311,-0.020081,-0.010332,-0.035949,0.001701,-0.052824,-0.001794,0.065588,0.058367,0.011123,-0.027171,-0.016611,0.044290,0.003672,-0.109192,0.002914,0.054213,-0.022975,-4.537978e-33,-0.084671,-0.009206,-0.032483,0.002768,-0.005519,0.017573,-0.044898,0.023067,-0.030664,-0.019662,0.018532,-0.020976,-0.012494,0.059721,0.008697,-0.016298,0.024957,-0.004551,-0.013863,-0.038994,-0.042065,0.006918,-0.039609,0.081100,-0.033648,0.023950,-0.056235,0.029949,0.050691,0.006441,-0.011175,0.012565,-0.020883,-0.010401,-0.020942,0.040821,-0.097004,-0.001711,0.019140,-0.012686,0.043686,0.040660,0.003233,0.029180,0.039921,-0.027847,0.031638,0.032072,0.039567,-0.003032,0.015010,0.037550,0.027108,-0.015443,-0.012890,0.013283,0.040965,-0.049229,0.018515,-0.016822,-0.063214,-0.010951,0.036861,-0.076880,-0.025991,-0.027763,-0.103462,-0.030598,-0.016911,0.022471,-0.009833,-0.005950,0.046689,-0.064021,-0.045196,-0.003733,0.007174,-0.007640,-0.018557,0.031850,0.010014,0.004040,-0.037885,-0.044053,0.005207,-0.071541,-0.032523,0.006458,-0.031996,0.042111,0.058349,-0.044562,-0.026206,0.027216,0.006227,0.022254,0.034981,-0.009523,0.025005,0.016324,-0.010948,0.010191,-0.036949,-0.009086,0.048397,0.024607,0.021290,-0.003285,-0.000987,-0.007296,0.018380,0.013400,0.036833,-0.022981,-0.057515,-0.023193,-0.027240,0.010666,0.016400,-0.016398,0.032463,0.090374,-0.015504,0.026349,0.006136,-0.002853,0.012939,-0.049611,0.046681,0.000943,-0.009725,0.014872,2.322044e-07,-0.035863,0.016213,-0.007458,0.066209,-0.006664,-0.003122,-0.042244,-0.019812,-0.074418,0.001744,-0.027820,0.001961,0.007776,0.072272,-0.045673,-0.033433,0.090937,-0.020227,-0.028647,-0.028231,0.050625,0.050130,0.041781,0.033818,0.005371,-0.019499,-0.027083,-0.009976,0.038383,0.018382,0.052832,-0.013003,-0.012362,0.107628,-0.048151,0.020068,0.018094,-0.052215,0.006651,-0.051554,0.003454,-0.016251,0.025642,-0.039286,0.008837,-0.051004,-0.015622,0.024724,-0.031746,0.028445,0.006061,0.088971,0.018175,-0.041762,0.015042,0.041467,-0.040350,-0.014341,-0.042898,0.043501,-0.041297,-0.011302,0.013946,-0.024341,0.014390,-0.024299,-0.112248,2.305557e-34,-0.039653,0.052984,-0.019695,-0.011811,0.021838,-0.028240,0.021108,0.034708,-0.016407,0.018476,-0.024001

In [68]:
df_reviews_mrgEmb.to_feather('data/appliances_meta_012023_062023 v1.2.0.ftr')