# 🦅 Set Up

In [1]:
import json
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm

pd.set_option('display.max_columns', None)

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
from torchvision import datasets, models, transforms

import requests
from PIL import Image
from io import BytesIO
from torch.autograd import Variable
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

In [12]:
def get_vector_fromURL(url):
    response = requests.get(url)
    img = Image.open(BytesIO(response.content)).convert('RGB').resize((300, 300))
    t_img = Variable(normalize(to_tensor(scaler(img))).unsqueeze(0))
    my_embedding = torch.zeros(512)
    def copy_data(m, i, o):
        my_embedding.copy_(o.data.reshape(o.data.size(1)))
    h = layer.register_forward_hook(copy_data)
    model(t_img)
    h.remove()
    return my_embedding

In [31]:
def save_as_dataframe(dict_):
    df = pd.DataFrame(dict_).T
    df.columns = ['ResNet'+str(i) for i in range(1, 513)]
    return df

In [4]:
cd ..

C:\Users\chopi\Penn Dropbox\Hyunwoo Jung\1_Personal\_Hyunwoo Place\graduate school\2_coursework (2025-F)\2_CIS5200_Machine Learning\5_final project\3_analyses

# 🦅 Load Data

In [8]:
df_reviews = pd.read_feather('data/appliances_meta_012023_062023 v1.1.0.ftr')

In [10]:
df_reviews.head()

,review_id,rating,title,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,medium_image_url,medium_image_url_1,medium_image_url_2,medium_image_url_3,medium_image_url_4,medium_image_url_5,medium_image_url_6,medium_image_url_7,medium_image_url_8,medium_image_url_9,medium_image_url_10,medium_image_url_11,medium_image_url_12,medium_image_url_13,medium_image_url_14,medium_image_url_15,medium_image_url_16,medium_image_url_17,medium_image_url_18,medium_image_url_19,medium_image_url_20,medium_image_url_21,medium_image_url_22,medium_image_url_23,medium_image_url_24,medium_image_url_25,medium_image_url_26,medium_image_url_27,text_len,text_words,inter_review_time
0,1,3.0,Needs hose clamps,Needs metal hose clamps not plastic ties.... C...,B00004YWK2,B00004YWK2,AFFPAJDCW7NSKE4FZWBRWETUKZ2A,2023-02-18 02:32:06.278,0,True,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,108,18,NaT
1,2,1.0,Don't waste your money,Product is cheap and the door doesn't work well,B00004YWK2,B00004YWK2,AEI6B25VF65CG2HPBQ2FNBG7IQKA,2023-02-10 00:31:39.499,0,True,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,47,9,8 days 02:00:26.779000
2,3,1.0,Must have been a return,No cover to close it and plastic was separated.,B00004YWK2,B00004YWK2,AGA5X6NUWSQM42KDFJLO25JBXOEA,2023-02-07 14:55:58.766,0,True,https://m.media-amazon.com/images/I/71eRK2xYuJ...,https://m.media-amazon.com/images/I/71eRK2xYuJ...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,47,9,2 days 09:35:40.733000
3,4,5.0,Great product,"I love this it keeps my garage, nice and warm ...",B00004YWK2,B00004YWK2,AGO4SBTXOUTKYMHKQQNX7ZFDQSFA,2023-01-29 19:37:40.587,0,True,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,115,24,8 days 19:18:18.179000
4,5,5.0,Why be wasteful?,"So I mounted this, as you see, behind and just...",B00004YWK2,B00004YWK2,AHKTIX6L7FKPYDENUALEPNPMAIHQ,2023-01-03 16:32:51.697,0,True,https://m.media-amazon.com/images/I/61ctMn42LX...,https://m.media-amazon.com/images/I/61ctMn42LX...,https://m.media-amazon.com/images/I/71QP-FAvlQ...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,708,148,26 days 03:04:48.890000

## 🐔 get urls

In [14]:
df_reviews_imgs = df_reviews[['review_id'] +[col for col in df_reviews.columns if 'medium_image_url' in col]]
df_reviews_imgs = df_reviews_imgs[df_reviews_imgs['medium_image_url'].notnull()]

In [19]:
df_reviews_imgs.head()

,review_id,medium_image_url,medium_image_url_1,medium_image_url_2,medium_image_url_3,medium_image_url_4,medium_image_url_5,medium_image_url_6,medium_image_url_7,medium_image_url_8,medium_image_url_9,medium_image_url_10,medium_image_url_11,medium_image_url_12,medium_image_url_13,medium_image_url_14,medium_image_url_15,medium_image_url_16,medium_image_url_17,medium_image_url_18,medium_image_url_19,medium_image_url_20,medium_image_url_21,medium_image_url_22,medium_image_url_23,medium_image_url_24,medium_image_url_25,medium_image_url_26,medium_image_url_27
2,3,https://m.media-amazon.com/images/I/71eRK2xYuJ...,https://m.media-amazon.com/images/I/71eRK2xYuJ...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,5,https://m.media-amazon.com/images/I/61ctMn42LX...,https://m.media-amazon.com/images/I/61ctMn42LX...,https://m.media-amazon.com/images/I/71QP-FAvlQ...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
16,17,https://m.media-amazon.com/images/I/61VedqsVak...,https://m.media-amazon.com/images/I/61VedqsVak...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
50,51,https://m.media-amazon.com/images/I/71S7C6wu2h...,https://m.media-amazon.com/images/I/71S7C6wu2h...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
102,103,https://m.media-amazon.com/images/I/61vLTOZo2L...,https://m.media-amazon.com/images/I/61vLTOZo2L...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [16]:
url_cols = [col for col in df_reviews_imgs.columns if 'medium_image_url' in col]

# Melt the dataframe to long format
df_reviews_imgs_long = df_reviews_imgs.melt(
    id_vars=['review_id'],
    value_vars=url_cols,
    var_name='image_slot',
    value_name='image_url'
)

# Drop rows with missing URLs
df_reviews_imgs_long = df_reviews_imgs_long.dropna(subset=['image_url'])

# Keep only the relevant columns
df_reviews_imgs_long = df_reviews_imgs_long[['review_id', 'image_url']].sort_values('review_id').reset_index(drop=True)

In [20]:
df_reviews_imgs_long.head(10)

   review_id                                          image_url
0          3  https://m.media-amazon.com/images/I/71eRK2xYuJ...
1          3  https://m.media-amazon.com/images/I/71eRK2xYuJ...
2          5  https://m.media-amazon.com/images/I/61ctMn42LX...
3          5  https://m.media-amazon.com/images/I/61ctMn42LX...
4          5  https://m.media-amazon.com/images/I/71QP-FAvlQ...
5         17  https://m.media-amazon.com/images/I/61VedqsVak...
6         17  https://m.media-amazon.com/images/I/61VedqsVak...
7         51  https://m.media-amazon.com/images/I/71S7C6wu2h...
8         51  https://m.media-amazon.com/images/I/71S7C6wu2h...
9        103  https://m.media-amazon.com/images/I/61vLTOZo2L...

In [21]:
df_reviews_imgs_long.to_feather('data/appliances_meta_012023_062023 v1.1.0_imgUrls.ftr')

# 🦅 Extract ResNet Vector

## 🐔 extract embeddings

In [5]:
df_photoURL = pd.read_feather('data/appliances_meta_012023_062023 v1.1.0_imgUrls.ftr')

In [6]:
df_photoURL.head()

   review_id                                          image_url
0          3  https://m.media-amazon.com/images/I/71eRK2xYuJ...
1          3  https://m.media-amazon.com/images/I/71eRK2xYuJ...
2          5  https://m.media-amazon.com/images/I/61ctMn42LX...
3          5  https://m.media-amazon.com/images/I/61ctMn42LX...
4          5  https://m.media-amazon.com/images/I/71QP-FAvlQ...

In [7]:
len(df_photoURL)

24684

In [8]:
''' model setting '''
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = models.resnet18(pretrained=True) 
layer = model._modules.get('avgpool')    
model.eval()

C:\Users\chopi\anaconda3\envs\ml-project\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\chopi\anaconda3\envs\ml-project\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer2): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(64, 128, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer3): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer4): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(1, 1))
  (fc): Linear(in_features=512, out_features=1000, bias=True)
)

In [9]:
''' prep image data '''
scaler = transforms.Resize((224, 224))
normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225])
to_tensor = transforms.ToTensor()

In [37]:
''' change photo to vector '''
dict_data = {}
list_failed_URL = []
for idx in tqdm(df_photoURL.index):
    url = df_photoURL.loc[idx, 'image_url']
    try: 
        dict_data[url] = np.array(get_vector_fromURL(url))
    except Exception as e:
        print("index {}: with Error {}".format(idx, e))
        list_failed_URL.append({'image_url': url, 'idx': idx})

  0%|          | 0/24684 [00:00<?, ?it/s]

index 40: with Error cannot identify image file <_io.BytesIO object at 0x000001610BFDBF90>
index 41: with Error cannot identify image file <_io.BytesIO object at 0x00000161115A22C0>
index 998: with Error cannot identify image file <_io.BytesIO object at 0x000001611029CE50>
index 999: with Error cannot identify image file <_io.BytesIO object at 0x00000161113B3590>
index 2021: with Error cannot identify image file <_io.BytesIO object at 0x0000016111560450>
index 2022: with Error cannot identify image file <_io.BytesIO object at 0x00000161115F4680>
index 2084: with Error cannot identify image file <_io.BytesIO object at 0x000001611153FB80>
index 2085: with Error cannot identify image file <_io.BytesIO object at 0x000001611160FA40>
index 2491: with Error cannot identify image file <_io.BytesIO object at 0x000001611153F810>
index 2492: with Error cannot identify image file <_io.BytesIO object at 0x0000016109902BD0>
index 2493: with Error cannot identify image file <_io.BytesIO object at 0x000001610FC6A450>
index 3821: with Error cannot identify image file <_io.BytesIO object at 0x00000161113AC450>
index 3822: with Error cannot identify image file <_io.BytesIO object at 0x000001611029CE50>
index 3823: with Error cannot identify image file <_io.BytesIO object at 0x00000161113B3590>
index 3824: with Error cannot identify image file <_io.BytesIO object at 0x000001611158E450>
index 3825: with Error cannot identify image file <_io.BytesIO object at 0x00000161113B3590>
index 3826: with Error cannot identify image file <_io.BytesIO object at 0x0000016111551310>
index 3827: with Error cannot identify image file <_io.BytesIO object at 0x00000161115A22C0>
index 4080: with Error cannot identify image file <_io.BytesIO object at 0x000001611158E450>
index 4081: with Error cannot identify image file <_io.BytesIO object at 0x0000016111551310>
index 4644: with Error cannot identify image file <_io.BytesIO object at 0x000001610C753EA0>
index 4645: with Error cannot identify image file <_io.BytesIO object at 0x00000161115F4680>
index 5132: with Error cannot identify image file <_io.BytesIO object at 0x000001611029CE50>
index 5133: with Error cannot identify image file <_io.BytesIO object at 0x0000016111560220>
index 5692: with Error cannot identify image file <_io.BytesIO object at 0x000001610B382D60>
index 5693: with Error cannot identify image file <_io.BytesIO object at 0x0000016110287450>
index 6256: with Error cannot identify image file <_io.BytesIO object at 0x00000161115A22C0>
index 6640: with Error cannot identify image file <_io.BytesIO object at 0x000001610FC6A450>
index 6641: with Error cannot identify image file <_io.BytesIO object at 0x0000016110340040>
index 6642: with Error cannot identify image file <_io.BytesIO object at 0x000001610FC6A450>
index 6862: with Error cannot identify image file <_io.BytesIO object at 0x000001610FC6A450>
index 6863: with Error cannot identify image file <_io.BytesIO object at 0x00000161115A22C0>
index 7583: with Error cannot identify image file <_io.BytesIO object at 0x000001611153FB80>
index 7584: with Error cannot identify image file <_io.BytesIO object at 0x000001610B382D60>
index 7585: with Error cannot identify image file <_io.BytesIO object at 0x0000016109902BD0>
index 7586: with Error cannot identify image file <_io.BytesIO object at 0x000001610FC6A450>
index 7587: with Error cannot identify image file <_io.BytesIO object at 0x00000161115548B0>
index 8334: with Error cannot identify image file <_io.BytesIO object at 0x00000161113B35E0>
index 8335: with Error cannot identify image file <_io.BytesIO object at 0x00000161115441D0>
index 8336: with Error cannot identify image file <_io.BytesIO object at 0x0000016111560220>
index 8337: with Error cannot identify image file <_io.BytesIO object at 0x0000016111560220>
index 8338: with Error cannot identify image file <_io.BytesIO object at 0x00000161113B35E0>
index 9214: with Error cannot identify image file <_io.BytesIO object at 0x000001611153FB80>
index 9215: with Error cannot identify image file <_io.BytesIO object at 0x000001611029CE50>
index 9216: with Error cannot identify image file <_io.BytesIO object at 0x00000161115548B0>
index 9217: with Error cannot identify image file <_io.BytesIO object at 0x0000016111543E50>
index 9499: with Error cannot identify image file <_io.BytesIO object at 0x00000161115F4680>
index 9500: with Error cannot identify image file <_io.BytesIO object at 0x0000016110287450>
index 9800: with Error cannot identify image file <_io.BytesIO object at 0x00000161115549A0>
index 9801: with Error cannot identify image file <_io.BytesIO object at 0x0000016111551310>
index 9949: with Error cannot identify image file <_io.BytesIO object at 0x00000161115F4680>
index 9950: with Error cannot identify image file <_io.BytesIO object at 0x00000161115441D0>
index 9951: with Error cannot identify image file <_io.BytesIO object at 0x00000161113B31D0>
index 10833: with Error cannot identify image file <_io.BytesIO object at 0x00000161115441D0>
index 10834: with Error cannot identify image file <_io.BytesIO object at 0x0000016110287450>
index 10835: with Error cannot identify image file <_io.BytesIO object at 0x00000161115548B0>
index 10841: with Error cannot identify image file <_io.BytesIO object at 0x00000161113B6C70>
index 10842: with Error cannot identify image file <_io.BytesIO object at 0x00000161115548B0>
index 10843: with Error cannot identify image file <_io.BytesIO object at 0x00000161113B6C70>
index 11405: with Error cannot identify image file <_io.BytesIO object at 0x00000161113AC450>
index 11406: with Error cannot identify image file <_io.BytesIO object at 0x000001610BFBFE00>
index 12179: with Error cannot identify image file <_io.BytesIO object at 0x0000016111551310>
index 12180: with Error cannot identify image file <_io.BytesIO object at 0x0000016110391680>
index 12181: with Error cannot identify image file <_io.BytesIO object at 0x00000161115444F0>
index 12182: with Error cannot identify image file <_io.BytesIO object at 0x0000016110340040>
index 12330: with Error cannot identify image file <_io.BytesIO object at 0x00000161115444F0>
index 12331: with Error cannot identify image file <_io.BytesIO object at 0x0000016110287450>
index 12332: with Error cannot identify image file <_io.BytesIO object at 0x000001611160FCC0>
index 12333: with Error cannot identify image file <_io.BytesIO object at 0x00000161113B3590>
index 12334: with Error cannot identify image file <_io.BytesIO object at 0x0000016110287450>
index 12419: with Error cannot identify image file <_io.BytesIO object at 0x00000161115F4680>
index 12420: with Error cannot identify image file <_io.BytesIO object at 0x00000161113AC450>
index 13482: with Error cannot identify image file <_io.BytesIO object at 0x000001610BFBFE00>
index 13483: with Error cannot identify image file <_io.BytesIO object at 0x00000161115A22C0>
index 13484: with Error cannot identify image file <_io.BytesIO object at 0x00000161115F4680>
index 13485: with Error cannot identify image file <_io.BytesIO object at 0x000001611153FB80>
index 13486: with Error cannot identify image file <_io.BytesIO object at 0x00000161113AC450>
index 13487: with Error cannot identify image file <_io.BytesIO object at 0x00000161115A22C0>
index 13498: with Error cannot identify image file <_io.BytesIO object at 0x000001611029CE50>
index 13499: with Error cannot identify image file <_io.BytesIO object at 0x000001610C753EA0>
index 13552: with Error cannot identify image file <_io.BytesIO object at 0x0000016111551310>
index 13553: with Error cannot identify image file <_io.BytesIO object at 0x00000161115444F0>
index 13554: with Error cannot identify image file <_io.BytesIO object at 0x0000016111543E50>
index 13555: with Error cannot identify image file <_io.BytesIO object at 0x00000161115549A0>
index 13556: with Error cannot identify image file <_io.BytesIO object at 0x0000016110287450>
index 13557: with Error cannot identify image file <_io.BytesIO object at 0x00000161115549A0>
index 13558: with Error cannot identify image file <_io.BytesIO object at 0x0000016110287450>
index 13615: with Error cannot identify image file <_io.BytesIO object at 0x00000161115548B0>
index 13616: with Error cannot identify image file <_io.BytesIO object at 0x0000016110391680>
index 13754: with Error cannot identify image file <_io.BytesIO object at 0x0000016110340040>
index 13755: with Error cannot identify image file <_io.BytesIO object at 0x000001611153FB80>
index 13756: with Error cannot identify image file <_io.BytesIO object at 0x00000161115549A0>
index 16194: with Error cannot identify image file <_io.BytesIO object at 0x0000016111543E50>
index 16195: with Error cannot identify image file <_io.BytesIO object at 0x00000161113B6C70>
index 18824: with Error cannot identify image file <_io.BytesIO object at 0x0000016111560220>
index 18825: with Error cannot identify image file <_io.BytesIO object at 0x000001610FC6A450>
index 20559: with Error cannot identify image file <_io.BytesIO object at 0x000001610BFBFE00>
index 20560: with Error cannot identify image file <_io.BytesIO object at 0x00000161115549A0>
index 21881: with Error cannot identify image file <_io.BytesIO object at 0x000001611153F810>
index 21882: with Error cannot identify image file <_io.BytesIO object at 0x0000016111551310>
index 21883: with Error cannot identify image file <_io.BytesIO object at 0x00000161113B3590>
index 22779: with Error cannot identify image file <_io.BytesIO object at 0x00000161115441D0>
index 22780: with Error cannot identify image file <_io.BytesIO object at 0x000001611029CE50>
index 22802: with Error cannot identify image file <_io.BytesIO object at 0x0000016110391680>
index 22803: with Error cannot identify image file <_io.BytesIO object at 0x0000016111560220>
index 22804: with Error cannot identify image file <_io.BytesIO object at 0x0000016109902BD0>
index 22805: with Error cannot identify image file <_io.BytesIO object at 0x00000161113B31D0>
index 22998: with Error cannot identify image file <_io.BytesIO object at 0x0000016110391680>
index 22999: with Error cannot identify image file <_io.BytesIO object at 0x000001610B382D60>
index 23000: with Error cannot identify image file <_io.BytesIO object at 0x00000161115548B0>
index 23053: with Error cannot identify image file <_io.BytesIO object at 0x000001611153FB80>
index 23054: with Error cannot identify image file <_io.BytesIO object at 0x000001610B382D60>
index 23055: with Error cannot identify image file <_io.BytesIO object at 0x0000016110287450>
index 23202: with Error cannot identify image file <_io.BytesIO object at 0x00000161115441D0>
index 23203: with Error cannot identify image file <_io.BytesIO object at 0x000001610B382D60>
index 23243: with Error cannot identify image file <_io.BytesIO object at 0x000001611158E450>
index 23244: with Error cannot identify image file <_io.BytesIO object at 0x000001610BFD83B0>
index 23519: with Error cannot identify image file <_io.BytesIO object at 0x000001611153FB80>
index 23520: with Error cannot identify image file <_io.BytesIO object at 0x000001610FC6A450>
index 23521: with Error cannot identify image file <_io.BytesIO object at 0x0000016110287450>
index 23522: with Error cannot identify image file <_io.BytesIO object at 0x00000161115A22C0>
index 23539: with Error cannot identify image file <_io.BytesIO object at 0x00000161115549A0>
index 23540: with Error cannot identify image file <_io.BytesIO object at 0x000001611029CE50>
index 23541: with Error cannot identify image file <_io.BytesIO object at 0x00000161113B3590>
index 23542: with Error cannot identify image file <_io.BytesIO object at 0x0000016111560450>
index 23543: with Error cannot identify image file <_io.BytesIO object at 0x0000016110391680>
index 23544: with Error cannot identify image file <_io.BytesIO object at 0x00000161113B3590>
index 24374: with Error cannot identify image file <_io.BytesIO object at 0x0000016111560450>
index 24375: with Error cannot identify image file <_io.BytesIO object at 0x000001610BFBFE00>
index 24663: with Error cannot identify image file <_io.BytesIO object at 0x00000161115549A0>
index 24664: with Error cannot identify image file <_io.BytesIO object at 0x00000161113AC450>

In [38]:
len(list_failed_URL)

131

In [39]:
df_imgEmb = save_as_dataframe(dict_data).reset_index().rename(columns={'index':'image_url'})

In [41]:
df_imgEmb['image_url'].nunique()

15566

In [45]:
df_imgEmb.shape, df_photoURL.shape

((15566, 513), (24684, 2))

In [42]:
df_imgEmb.head()

,image_url,ResNet1,ResNet2,ResNet3,ResNet4,ResNet5,ResNet6,ResNet7,ResNet8,ResNet9,ResNet10,ResNet11,ResNet12,ResNet13,ResNet14,ResNet15,ResNet16,ResNet17,ResNet18,ResNet19,ResNet20,ResNet21,ResNet22,ResNet23,ResNet24,ResNet25,ResNet26,ResNet27,ResNet28,ResNet29,ResNet30,ResNet31,ResNet32,ResNet33,ResNet34,ResNet35,ResNet36,ResNet37,ResNet38,ResNet39,ResNet40,ResNet41,ResNet42,ResNet43,ResNet44,ResNet45,ResNet46,ResNet47,ResNet48,ResNet49,ResNet50,ResNet51,ResNet52,ResNet53,ResNet54,ResNet55,ResNet56,ResNet57,ResNet58,ResNet59,ResNet60,ResNet61,ResNet62,ResNet63,ResNet64,ResNet65,ResNet66,ResNet67,ResNet68,ResNet69,ResNet70,ResNet71,ResNet72,ResNet73,ResNet74,ResNet75,ResNet76,ResNet77,ResNet78,ResNet79,ResNet80,ResNet81,ResNet82,ResNet83,ResNet84,ResNet85,ResNet86,ResNet87,ResNet88,ResNet89,ResNet90,ResNet91,ResNet92,ResNet93,ResNet94,ResNet95,ResNet96,ResNet97,ResNet98,ResNet99,ResNet100,ResNet101,ResNet102,ResNet103,ResNet104,ResNet105,ResNet106,ResNet107,ResNet108,ResNet109,ResNet110,ResNet111,ResNet112,ResNet113,ResNet114,ResNet115,ResNet116,ResNet117,ResNet118,ResNet119,ResNet120,ResNet121,ResNet122,ResNet123,ResNet124,ResNet125,ResNet126,ResNet127,ResNet128,ResNet129,ResNet130,ResNet131,ResNet132,ResNet133,ResNet134,ResNet135,ResNet136,ResNet137,ResNet138,ResNet139,ResNet140,ResNet141,ResNet142,ResNet143,ResNet144,ResNet145,ResNet146,ResNet147,ResNet148,ResNet149,ResNet150,ResNet151,ResNet152,ResNet153,ResNet154,ResNet155,ResNet156,ResNet157,ResNet158,ResNet159,ResNet160,ResNet161,ResNet162,ResNet163,ResNet164,ResNet165,ResNet166,ResNet167,ResNet168,ResNet169,ResNet170,ResNet171,ResNet172,ResNet173,ResNet174,ResNet175,ResNet176,ResNet177,ResNet178,ResNet179,ResNet180,ResNet181,ResNet182,ResNet183,ResNet184,ResNet185,ResNet186,ResNet187,ResNet188,ResNet189,ResNet190,ResNet191,ResNet192,ResNet193,ResNet194,ResNet195,ResNet196,ResNet197,ResNet198,ResNet199,ResNet200,ResNet201,ResNet202,ResNet203,ResNet204,ResNet205,ResNet206,ResNet207,ResNet208,ResNet209,ResNet210,ResNet211,ResNet212,ResNet213,ResNet214,ResNet215,ResNet216,ResNet217,ResNet218,ResNet219,ResNet220,ResNet221,ResNet222,ResNet223,ResNet224,ResNet225,ResNet226,ResNet227,ResNet228,ResNet229,ResNet230,ResNet231,ResNet232,ResNet233,ResNet234,ResNet235,ResNet236,ResNet237,ResNet238,ResNet239,ResNet240,ResNet241,ResNet242,ResNet243,ResNet244,ResNet245,ResNet246,ResNet247,ResNet248,ResNet249,ResNet250,ResNet251,ResNet252,ResNet253,ResNet254,ResNet255,ResNet256,ResNet257,ResNet258,ResNet259,ResNet260,ResNet261,ResNet262,ResNet263,ResNet264,ResNet265,ResNet266,ResNet267,ResNet268,ResNet269,ResNet270,ResNet271,ResNet272,ResNet273,ResNet274,ResNet275,ResNet276,ResNet277,ResNet278,ResNet279,ResNet280,ResNet281,ResNet282,ResNet283,ResNet284,ResNet285,ResNet286,ResNet287,ResNet288,ResNet289,ResNet290,ResNet291,ResNet292,ResNet293,ResNet294,ResNet295,ResNet296,ResNet297,ResNet298,ResNet299,ResNet300,ResNet301,ResNet302,ResNet303,ResNet304,ResNet305,ResNet306,ResNet307,ResNet308,ResNet309,ResNet310,ResNet311,ResNet312,ResNet313,ResNet314,ResNet315,ResNet316,ResNet317,ResNet318,ResNet319,ResNet320,ResNet321,ResNet322,ResNet323,ResNet324,ResNet325,ResNet326,ResNet327,ResNet328,ResNet329,ResNet330,ResNet331,ResNet332,ResNet333,ResNet334,ResNet335,ResNet336,ResNet337,ResNet338,ResNet339,ResNet340,ResNet341,ResNet342,ResNet343,ResNet344,ResNet345,ResNet346,ResNet347,ResNet348,ResNet349,ResNet350,ResNet351,ResNet352,ResNet353,ResNet354,ResNet355,ResNet356,ResNet357,ResNet358,ResNet359,ResNet360,ResNet361,ResNet362,ResNet363,ResNet364,ResNet365,ResNet366,ResNet367,ResNet368,ResNet369,ResNet370,ResNet371,ResNet372,ResNet373,ResNet374,ResNet375,ResNet376,ResNet377,ResNet378,ResNet379,ResNet380,ResNet381,ResNet382,ResNet383,ResNet384,ResNet385,ResNet386,ResNet387,ResNet388,ResNet389,ResNet390,ResNet391,ResNet392,ResNet393,ResNet394,ResNet395,ResNet396,ResNet397,ResNet398,ResNet399,ResNet400,ResNet401,ResNet402,ResNet403,ResNet404,ResNet405,ResNet406,ResNet407,ResNet408,ResNet409,ResNet410,ResNet411,ResNet412,ResNet413,ResNet414,ResNet415,ResNet416,ResNet417,ResNet418,ResNet419,ResNet420,ResNet421,ResNet422,ResNet423,ResNet424,ResNet425,ResNet426,ResNet427,ResNet428,ResNet429,ResNet430,ResNet431,ResNet432,ResNet433,ResNet434,ResNet435,ResNet436,ResNet437,ResNet438,ResNet439,ResNet440,ResNet441,ResNet442,ResNet443,ResNet444,ResNet445,ResNet446,ResNet447,ResNet448,ResNet449,ResNet450,ResNet451,ResNet452,ResNet453,ResNet454,ResNet455,ResNet456,ResNet457,ResNet458,ResNet459,ResNet460,ResNet461,ResNet462,ResNet463,ResNet464,ResNet465,ResNet466,ResNet467,ResNet468,ResNet469,ResNet470,ResNet471,ResNet472,ResNet473,ResNet474,ResNet475,ResNet476,ResNet477,ResNet478,ResNet479,ResNet480,ResNet481,ResNet482,ResNet483,ResNet484,ResNet485,ResNet486,ResNet487,ResNet488,ResNet489,ResNet490,ResNet491,ResNet492,ResNet493,ResNet494,ResNet495,ResNet496,ResNet497,ResNet498,ResNet499,ResNet500,ResNet501,ResNet502,ResNet503,ResNet504,ResNet505,ResNet506,ResNet507,ResNet508,ResNet509,ResNet510,ResNet511,ResNet512
0,https://m.media-amazon.com/images/I/71eRK2xYuJ...,1.227711,2.299861,0.940519,1.547089,1.179963,1.118080,0.883333,1.075238,0.793488,0.597802,0.453003,0.705684,0.058664,1.280268,0.816059,0.301466,1.003663,0.949884,0.468697,0.644233,0.149071,0.000000,1.452253,1.586333,0.258196,1.090885,0.843890,0.496784,0.273786,0.843188,1.177152,0.406214,1.891665,0.587672,0.624082,0.261904,1.687648,0.917587,2.100833,1.558447,1.337976,1.077066,0.757252,0.099686,1.017920,2.931376,2.481516,2.540691,0.646838,1.480900,0.442617,0.216109,0.242987,0.072367,0.572265,1.707805,0.736578,2.073210,0.067422,0.886495,0.914696,0.059353,0.478773,0.755636,0.046745,0.711528,0.602871,0.000669,0.718780,1.156330,1.027720,0.242149,1.115860,1.611139,0.090275,1.064418,5.148195,0.722860,1.270357,0.866186,0.673880,0.409866,0.689974,0.106730,0.991083,0.737271,0.113362,0.273628,0.704169,0.664158,0.704608,0.510205,0.452984,0.362143,0.851318,2.248016,0.953664,1.343452,0.653854,1.773282,0.323284,0.442887,1.640411,2.921854,1.481178,0.100580,0.703790,0.258204,0.975079,1.331311,0.309202,0.711838,1.178556,0.590169,2.639046,1.072111,0.160349,0.386257,1.074922,1.406540,3.242885,0.339277,0.871912,0.555328,0.000300,0.030195,2.754407,0.415137,0.795492,0.478813,1.271368,0.777827,0.045241,0.082873,0.249745,0.038548,1.969092,1.605269,1.340340,0.027930,0.542212,1.132841,0.577193,1.892887,1.291315,2.561778,0.165315,1.472095,0.372185,0.794260,0.901804,1.167165,0.103809,1.405308,0.799857,4.812631,0.975512,0.674425,0.175323,0.342655,0.204638,0.994730,1.392988,0.751032,1.574340,0.516448,0.495743,0.360129,0.080834,0.767415,1.605972,2.130967,0.099045,0.785190,0.085145,1.666519,2.785354,1.794753,2.548560,0.155301,0.013425,0.812344,0.482122,0.156694,1.314035,0.066303,1.520728,0.392657,1.056735,0.359128,3.385186,0.642479,4.195302,0.238271,1.610449,0.805396,1.089323,0.179746,1.524459,0.760455,0.047516,0.510277,0.595407,0.767493,0.836427,1.515707,2.226846,0.849578,0.218885,1.212618,0.706728,0.830115,1.969190,0.059764,0.920290,0.493255,0.721851,0.269020,0.112665,0.322929,0.634898,1.419523,1.760468,0.016130,2.348598,1.484697,0.787576,0.178013,0.116176,0.895578,0.110612,2.639354,0.025386,1.437565,0.497577,0.981396,1.096836,1.032154,0.640693,0.542766,2.033211,0.468355,0.383072,4.995461,1.359656,0.009555,0.053998,1.079787,0.854989,0.109913,0.075905,0.292015,0.447561,0.031771,0.235049,0.795762,1.854512,1.053983,0.941417,0.591025,0.121786,1.591393,0.322470,0.710966,0.294437,1.494097,0.052011,0.694961,0.033469,0.218362,3.301681,1.328967,0.026123,0.616827,0.362491,0.606808,0.009813,1.767751,2.270111,1.259911,0.468837,0.093027,1.029588,0.738871,1.203018,0.264040,2.344477,1.073996,0.957686,0.325306,2.270401,0.194988,0.151415,0.211911,1.045168,2.731534,0.359895,0.204583,0.656505,0.764407,1.235148,0.255227,1.026459,0.496334,0.234826,1.772517,0.706520,0.566361,0.021673,0.352655,0.188716,1.531117,0.223690,0.958670,0.607296,0.791094,0.567887,1.257743,0.895649,0.192131,1.142151,0.358989,3.504979,2.805244,0.157127,0.730060,2.433485,2.444082,0.572740,0.070405,1.305212,0.922421,0.049362,0.833759,0.945557,1.862685,2.280724,0.274572,2.068399,1.345611,0.856098,1.318183,0.469974,3.637373,0.205213,0.926087,0.456564,1.031149,0.164934,1.714794,0.553875,0.053002,0.269595,1.195919,0.271873,0.257650,0.150856,0.581114,0.285604,0.446169,1.231503,4.013209,0.334072,1.230207,0.989097,0.717439,0.158482,1.982626,0.172567,1.361397,0.259471,0.978459,1.392763,0.378698,0.299109,0.326532,1.020432,0.379632,1.266562,0.174183,0.902249,0.105092,1.010698,2.222369,0.471096,0.310682,2.146286,0.903140,1.279613,0.627323,0.694811,0.038724,0.050881,0.955844,1.145123,1.140274,2.233325,2.182087,1.173434,0.555852,0.087925,2.549562,1.749725,0.618062,1.063979,2.076983,0.196686,0.862627,1.372637,0.574398,1.410587,0.013522,0.105750,1.228777,0.126628,2.659401,0.293985,2.856863,0.360468,0.008539,1.645209,2.396109,0.313881,0.093914,0.206505,1.853129,0.139302,0.877898,0.690170,0.439588,0.153363,0.242505,0.652730,2.329982,0.623886,0.276764,0.719051,2.820492,0.023087,1.067416,2.176333,0.303363,1.315041,0.590289,0.951125,1.130207,0.620704,1.398425,0.541101,0.742134,1.199643,0.270611,0.254230,1.146881,0.745572,0.024679,0.561936,0.345947,1.809604,0.902483,1.193404,0.139745,0.499198,1.945667,0.017914,0.397354,0.109788,0.202089,0.318327,1.643803,0.281774,0.650563,1.145050,3.271847,0.300661,0.788357,0.596176,2.962073,1.195113,1.184239,0.885179,0.382822,2.662987,1.649792,3.779634,0.335907,0.992718,1.605413,0.383042,2.595073,1.107632,0.011446,0.137724,1.020166,1.951814,1.115357,0.060669,0.255865,0.948571,0.207325,1.815886,0.330402,0.713876,1.146581,0.103412,0.564442,1.773487,0.983913,0.220921,1.707405,0.076411,0.557772
1,https://m.media-amazon.com/images/I/61ctMn42LX...,0.455526,0.272074,0.698200,0.744720,1.468381,0.775785,1.031355,0.569696,1.399707,0.691715,0.368789,0.840077,1.308668,0.467411,0.289457,1.594978,0.859765,2.075928,0.619103,0.362168,2.561991,0.389718,1.051607,2.446883,0.952276,1.045195,0.597214,0.581440,0.976121,1.213667,0.880817,1.081818,0.657250,2.380730,0.440159,0.579112,3.923927,0.952248,0.467457,1.463264,0.032639,0.284669,0.622746,2.081719,0.753786,1.011658,0.701358,2.948338,2.063522,0.492154,2.963372,0.088087,1.403913,0.616078,0.144424,1.221676,0.708831,0.046282,0.242571,2.153554,0.719535,1.698789,2.039307,2.130577,0.882960,0.261741,2.387467,0.466444,0.007844,0.852542,1.626836,0.287882,0.262244,1.966249,1.544291,0.215683,1.618052,0.653574,0.109985,2.413440,0.577818,0.838743,1.545325,0.793786,0.400394,0.921750,0.778026,0.568925,0.570189,0.973556,1.667902,0.492674,0.427274,1.326577,3.399078,3.680160,1.974873,0.566301,0.150317,2.216802,0.188053,0.487910,2.269673,1.484019,0.651400,0.230226,0.440373,0.110116,0.196687,1.730065,0.741168,0.769006,0.366841,0.264252,2.533339,0.998479,0.868148,0.454438,1.888465,0.442727,1.340506,0.611179,0.523355,0.046395,0.171935,0.008681,1.667436,0.737145,2.587888,0.000000,1.041226,0.612255,0.556791,0.984088,0.001845,0.592018,0.456583,0.069992,1.840710,1.480701,0.849163,0.151804,1.241877,3.731125,0.150750,0.258593,0.597698,0.043984,1.563078,0.720600,0.819757,0.161661,1.363806,0.898005,0.945021,2.316666,1.090798,0.997159,0.125895,1.378513,1.527936,0.713092,0.000000,2.084452,1.457670,1.226569,0.004295,0.701157,0.954918,0.108338,0.864761,0.987093,0.267279,0.629660,0.043989,2.787990,2.187958,2.493583,1.782187,0.197267,0.122809,0.824310,0.370618,0.832515,1.272955,0.852411,1.943373,0.947935,1.311239,0.889954,1.554690,0.033186,1.527565,0.107913,0.446036,0.254642,1.613071,0.473126,3.011805,0.183802,0.023446,2.357367,0.327462,0.974328,0.343326,0.760235,0.761002,0.680837,1.252916,0.216444,0.580271,0.682029,0.586497,0.329406,0.066923,1.017913,2.342450,0.225549,1.694313,0.167705,1.484047,0.434798,1.491734,2.547205,1.058666,3.344168,0.568330,1.647981,0.322228,1.300684,0.625855,1.382790,0.476749,1.929155,0.914816,1.342221,1.843442,1.668315,0.574634,1.124495,0.161157,0.696082,0.343275,1.438442,0.514753,1.592690,1.117171,0.056175,0.538784,0.521998,1.919686,0.158370,0.545470,0.169726,1.193884,1.802432,0.892621,0.337734,0.314654,2.171645,0.855140,1.446572,2.076152,0.218155,0.890773,2.572183,0.660574,0.109954,0.375420,1.804523,0.595743,0.421104,0.420720,0.323311,0.130998,1.482264,0.560386,2.845796,2.201349,0.876215,0.415084,1.314358,0.460555,0.426183,2.188580,0.128242,2.091075,0.445525,0.756967,0.103082,4.494565,1.632618,2.606690,0.273927,0.620779,0.992015,1.051311,0.064190,0.594499,0.116631,0.587187,0.337160,1.091599,2.769103,0.916658,0.231164,1.981135,0.035529,1.188424,0.872216,1.025963,1.567323,1.826220,0.957744,2.463720,2.098568,1.279953,1.207504,0.819100,1.184620,1.105201,1.892880,3.130066,1.987831,0.454902,0.389111,2.248140,2.359459,0.542976,0.285661,0.586982,0.745560,0.045156,0.687291,1.976693,0.860556,0.497428,2.242239,0.320584,1.251310,0.152415,0.651157,0.041665,0.801558,0.653872,0.377013,0.118016,0.461858,0.048615,0.508335,1.423638,1.815000,0.585516,0.350922,0.105402,0.343259,1.716662,0.556371,0.390049,0.836153,0.886257,0.787273,0.265216,2.129151,1.610557,0.062693,0.344122,1.376480,1.554549,0.431550,0.835508,0.823861,0.775061,1.340151,0.067432,0.616940,0.201530,2.452321,0.140674,0.995602,1.578511,0.073721,3.410870,1.311612,0.603516,0.969428,2.860562,0.714925,0.802601,0.415663,0.367294,0.064506,3.218442,0.106462,1.891291,1.590070,1.084262,0.915459,0.765012,0.880710,0.077192,1.609093,1.551907,0.261940,4.309504,0.757505,0.540855,1.157224,2.021982,0.885776,1.397884,3.270962,1.294841,0.502068,0.978152,0.659680,0.602980,1.579259,0.047545,3.322169,0.833161,2.153487,1.080058,0.023548,0.437555,2.074970,0.457627,1.849660,0.780021,1.807136,0.598025,0.981264,0.676252,0.477293,1.277251,0.496577,0.826886,3.557984,0.334541,1.527163,1.553225,0.410599,1.139615,2.216677,0.108144,1.290659,0.875993,3.516400,0.304230,0.051503,0.661844,1.042429,1.333568,0.804312,0.610284,0.747329,2.174398,0.010103,1.105267,3.891287,1.449092,1.894811,1.263405,0.816210,0.855824,0.399211,0.538707,0.884884,1.454802,0.328653,0.339479,0.086767,0.138582,1.818871,0.153536,0.665138,0.094687,0.920715,0.138377,0.229348,0.075891,0.155327,0.287576,1.426284,1.240716,0.798855,2.305583,0.885314,0.320153,0.179770,0.557997,0.133740,0.261576,1.470731,1.143617,0.039237,0.621158,0.202483,1.229121,0.420170,1.011634,2.063149,1.124683,1.463016,1.032661,0.187447,0.297573,0.449004,0.169448,0.909740,0.323248,0.548275
2,https://m.media-amazon.com/images/I/71QP-FAvlQ...,1.005119,0.634475,0.042698,0.698337,1.131603,0.444108,0.714847,1.250394,2.460903,1.117696,0.905359,0.016986,1.479027,1.228292,0.815111,1.036273,0.330845,0.706879,0.527454,0.737064,2.612255,0.972650,1.463817,1.010800,0.829770,0.452652,0.320236,0.138412,3.000493,1.796068,0.499501,1.315641,0.015033,0.627002,0.669974,0.352451,1.774358,2.745976,2.489540,2.335245,0.401028,0.891135,0.754963,1.452563,1.922933,1.207163,0.753054,1.897249,0.846172,0.412422,4.031864,0.161775,0.563656,1.668948,0.194342,1.649960,1.211126,1.704231,0.130803,1.365561,1.681113,2.360585,1.265314,2.286598,0.002387,0.199161,2.669339,0.809932,0.399897,1.212885,2.932585,0.811350,1.206430,1.417316,2.206857,0.332704,4.394799,1.134360,0.149158,1.744967,0.577295,0.182924,1.175337,2.027651,0.821316,1.044110,1.053229,1.978388,0.952904,0.447123,1.673084,0.662977,0.367278,1.132623,3.343849,5.046586,1.102587,1.218873,0.154406,2.993063,0.796018,0.561661,1.530531,0.855141,1.649500,0.540421,0.848130,0.523873,0.826571,0.754789,0.894328,1.627501,1.700523,0.143090,1.863325,0.185482,1.216824,0.377145,2.109644,1.394274,0.977662,0.832246,0.097656,0.902507,1.457676,0.598456,1.734282,0.864116,1.787495,1.498296,0.987445,0.750856,0.052509,0.879115,0.407999,0.471725,1.984150,1.416377,0.756312,1.856932,0.057337,1.009176,0.514597,1.048071,0.020908,1.217340,1.095676,0.251131,1.123558,0.671275,0.895445,0.751592,0.696632,0.927965,0.642003,3.201270,1.196332,1.151449,0.997463,0.606121,1.417312,0.540860,0.102842,1.001084,2.107560,1.037148,0.233624,0.090173,0.298459,0.887011,0.940781,1.275668,0.274707,0.311668,0.037675,1.770092,1.324492,1.731421,1.341150,0.469189,0.370136,0.758049,0.483412,1.176831,0.531753,0.988273,1.617027,2.166291,1.124816,0.223321,2.080357,0.000000,0.752944,0.707989,0.263920,0.973756,2.077808,0.583695,3.398103,0.339750,0.263760,2.268452,0.614580,2.358129,0.675399,0.065849,0.485056,0.278624,1.283327,0.419347,0.809285,1.390500,0.778309,1.179173,0.377310,1.385651,1.363637,0.641463,1.183314,0.262483,1.501227,0.601823,1.537400,2.169671,0.469990,4.151223,0.822587,1.609196,0.145745,2.842613,0.880442,1.301462,0.383935,3.000336,0.620937,1.653499,2.110842,0.916214,0.097379,0.839764,2.521795,0.585013,0.853333,3.259911,0.293309,2.936927,0.590445,0.472017,0.674619,1.273339,1.618520,0.789746,0.841733,0.731894,1.296253,0.957996,0.843149,0.238000,0.667466,1.111400,0.211261,0.367742,2.288021,0.244924,1.433933,2.492666,0.837312,1.419242,1.183182,0.163001,1.223722,0.651672,1.235773,0.001328,0.304024,2.604083,1.033566,2.589700,1.119040,0.857755,1.246285,2.538040,0.692291,0.927869,1.924395,0.093641,2.661106,0.164034,1.061934,0.205378,3.180663,1.103809,1.121930,0.074440,1.525885,0.440575,0.813282,0.179676,0.233132,1.000824,2.570523,1.385570,1.959408,1.666883,0.360412,1.419001,0.188802,0.139212,0.226491,1.216133,1.451087,0.551856,1.081080,1.584090,2.580357,2.286372,1.777301,2.758312,0.376339,0.074717,1.055337,1.931413,2.888090,3.015438,0.500108,0.277577,2.025608,0.323460,0.505560,0.277942,0.627609,0.329047,0.316319,0.279848,2.096413,2.916907,1.185483,2.869165,1.084412,3.364172,0.023426,0.542956,0.432310,1.275427,1.723290,1.929209,0.169152,0.067197,0.998309,2.404622,1.303007,2.575828,0.486242,1.640502,0.274728,0.659607,0.916466,1.953891,0.867108,0.859277,0.894767,1.776108,0.521270,1.812804,2.112298,0.177632,0.364326,1.412875,1.289834,0.922509,0.932909,2.011926,0.583923,0.027419,0.636516,0.828484,0.603753,0.339832,0.424035,0.651650,0.262078,0.266166,3.539123,1.719879,0.787968,1.264026,2.403122,0.058832,2.214447,1.112720,0.531773,0.004448,2.174803,0.295649,0.748526,0.695218,0.993117,2.271925,0.401694,0.259315,0.894236,3.486154,2.046138,1.022187,3.123676,0.270918,0.756263,1.441358,1.374902,0.641360,3.662472,1.073970,1.133856,0.855617,0.904376,1.537277,0.084341,1.667922,0.118183,3.224444,0.239034,2.693961,0.779206,0.257624,0.179429,0.960915,0.696544,1.190372,0.917248,0.796799,0.687818,0.592956,0.481786,0.274139,2.037235,1.231740,0.032469,1.714503,2.252767,1.445510,1.272758,0.012544,0.663230,0.674777,0.306116,0.938294,2.341839,4.280833,0.234176,0.228738,0.663040,0.456215,1.165319,0.227055,1.266863,0.565268,1.468774,0.029747,1.289023,5.101435,0.850519,0.343546,2.808610,1.092179,0.965087,0.337360,1.701365,0.283981,0.721186,1.623617,0.022656,0.009413,0.701178,2.732190,0.000000,1.079968,0.694844,1.441730,0.441630,2.465422,1.030643,0.654287,0.495914,0.623359,1.301888,0.259665,2.178484,1.301081,0.249586,0.536806,0.262988,0.335934,0.425700,0.371848,0.953079,0.247640,0.826022,0.380460,0.543849,0.864970,0.975101,2.574417,2.998233,0.947957,1.563665,0.470347,0.809921,1.110234,0.313295,1.594744,0.155159,1.228578

In [43]:
df_imgEmb.to_csv('data/appliances_meta_012023_062023 v1.1.0_imgUrls_imgEmb.csv', index=False)

## 🐔 debug error lines

In [50]:
df_photoURL = pd.read_feather('data/appliances_meta_012023_062023 v1.1.0_imgUrls.ftr').drop_duplicates(subset='image_url')
df_photoURL_imgEmb = pd.read_csv('data/appliances_meta_012023_062023 v1.1.0_imgUrls_imgEmb.csv')

In [51]:
df_photoURL_leftovers = df_photoURL[~df_photoURL['image_url'].isin(df_photoURL_imgEmb['image_url'].unique())]

In [53]:
df_photoURL['image_url'].nunique(), df_photoURL_leftovers['image_url'].nunique(), df_photoURL_imgEmb['image_url'].nunique()

(15651, 85, 15566)

In [54]:
len(df_photoURL_leftovers)

85

In [55]:
df_photoURL_leftovers.head()

      review_id                                          image_url
40          285  https://m.media-amazon.com/images/I/71Wr5Hq-RD...
998        7100  https://m.media-amazon.com/images/I/611p7No9iZ...
2021      14261  https://m.media-amazon.com/images/I/81HU8d+FTS...
2084      14936  https://m.media-amazon.com/images/I/71kLb368OQ...
2491      17822  https://m.media-amazon.com/images/I/71fw2n5NAe...

In [57]:
''' model setting '''
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = models.resnet18(pretrained=True) 
layer = model._modules.get('avgpool')    
model.eval()

C:\Users\chopi\anaconda3\envs\ml-project\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\chopi\anaconda3\envs\ml-project\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer2): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(64, 128, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer3): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer4): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(1, 1))
  (fc): Linear(in_features=512, out_features=1000, bias=True)
)

In [58]:
''' prep image data '''
scaler = transforms.Resize((224, 224))
normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225])
to_tensor = transforms.ToTensor()

In [59]:
''' change photo to vector '''
dict_data = {}
list_failed_URL = []
for idx in tqdm(df_photoURL_leftovers.index):
    url = df_photoURL_leftovers.loc[idx, 'image_url']
    try: 
        dict_data[url] = np.array(get_vector_fromURL(url))
    except Exception as e:
        print("index {}: with Error {}".format(idx, e))
        list_failed_URL.append({'image_url': url, 'idx': idx})

  0%|          | 0/85 [00:00<?, ?it/s]

index 40: with Error cannot identify image file <_io.BytesIO object at 0x0000016111BF7310>
index 998: with Error cannot identify image file <_io.BytesIO object at 0x0000016111BF79A0>
index 2021: with Error cannot identify image file <_io.BytesIO object at 0x000001611154F540>
index 2084: with Error cannot identify image file <_io.BytesIO object at 0x000001611153F810>
index 2491: with Error cannot identify image file <_io.BytesIO object at 0x00000161113B6C70>
index 2493: with Error cannot identify image file <_io.BytesIO object at 0x0000016110391680>
index 3821: with Error cannot identify image file <_io.BytesIO object at 0x00000161115609F0>
index 3822: with Error cannot identify image file <_io.BytesIO object at 0x000001610B382D60>
index 3824: with Error cannot identify image file <_io.BytesIO object at 0x0000016110391680>
index 3825: with Error cannot identify image file <_io.BytesIO object at 0x0000016111543E50>
index 3826: with Error cannot identify image file <_io.BytesIO object at 0x000001611154F220>
index 3827: with Error cannot identify image file <_io.BytesIO object at 0x0000016110391680>
index 4080: with Error cannot identify image file <_io.BytesIO object at 0x000001611154F220>
index 4644: with Error cannot identify image file <_io.BytesIO object at 0x00000161115F4680>
index 5132: with Error cannot identify image file <_io.BytesIO object at 0x000001610C753EA0>
index 5692: with Error cannot identify image file <_io.BytesIO object at 0x0000016111543E50>
index 6256: with Error cannot identify image file <_io.BytesIO object at 0x000001611154F220>
index 6640: with Error cannot identify image file <_io.BytesIO object at 0x0000016111543E50>
index 6642: with Error cannot identify image file <_io.BytesIO object at 0x000001610BFD83B0>
index 6862: with Error cannot identify image file <_io.BytesIO object at 0x000001611158EC20>
index 7583: with Error cannot identify image file <_io.BytesIO object at 0x000001611154F220>
index 7584: with Error cannot identify image file <_io.BytesIO object at 0x0000016110391680>
index 7585: with Error cannot identify image file <_io.BytesIO object at 0x000001611158EC20>
index 7587: with Error cannot identify image file <_io.BytesIO object at 0x000001610B382D60>
index 8334: with Error cannot identify image file <_io.BytesIO object at 0x00000161115A22C0>
index 8335: with Error cannot identify image file <_io.BytesIO object at 0x000001610B382D60>
index 8336: with Error cannot identify image file <_io.BytesIO object at 0x000001610C753EA0>
index 8338: with Error cannot identify image file <_io.BytesIO object at 0x000001610B382D60>
index 9214: with Error cannot identify image file <_io.BytesIO object at 0x00000161115A22C0>
index 9216: with Error cannot identify image file <_io.BytesIO object at 0x000001610B382D60>
index 9217: with Error cannot identify image file <_io.BytesIO object at 0x000001611153F810>
index 9499: with Error cannot identify image file <_io.BytesIO object at 0x000001611154F270>
index 9800: with Error cannot identify image file <_io.BytesIO object at 0x000001610BFD83B0>
index 9949: with Error cannot identify image file <_io.BytesIO object at 0x000001610BFD83B0>
index 9950: with Error cannot identify image file <_io.BytesIO object at 0x000001611154F270>
index 10833: with Error cannot identify image file <_io.BytesIO object at 0x0000016111560450>
index 10834: with Error cannot identify image file <_io.BytesIO object at 0x0000016111560450>
index 10841: with Error cannot identify image file <_io.BytesIO object at 0x000001610FC6A450>
index 10842: with Error cannot identify image file <_io.BytesIO object at 0x000001610BFD83B0>
index 11405: with Error cannot identify image file <_io.BytesIO object at 0x0000016110391680>
index 12179: with Error cannot identify image file <_io.BytesIO object at 0x000001610BFD83B0>
index 12180: with Error cannot identify image file <_io.BytesIO object at 0x0000016110391680>
index 12182: with Error cannot identify image file <_io.BytesIO object at 0x00000161115F4680>
index 12330: with Error cannot identify image file <_io.BytesIO object at 0x00000161113B6C70>
index 12331: with Error cannot identify image file <_io.BytesIO object at 0x000001611029CE50>
index 12332: with Error cannot identify image file <_io.BytesIO object at 0x000001610C753EA0>
index 12333: with Error cannot identify image file <_io.BytesIO object at 0x000001610BFBFE00>
index 12419: with Error cannot identify image file <_io.BytesIO object at 0x000001610C753EA0>
index 13482: with Error cannot identify image file <_io.BytesIO object at 0x000001610BFBFE00>
index 13483: with Error cannot identify image file <_io.BytesIO object at 0x0000016111BF7BD0>
index 13485: with Error cannot identify image file <_io.BytesIO object at 0x0000016111560AE0>
index 13486: with Error cannot identify image file <_io.BytesIO object at 0x000001610FC6A450>
index 13487: with Error cannot identify image file <_io.BytesIO object at 0x000001610FC6A450>
index 13498: with Error cannot identify image file <_io.BytesIO object at 0x000001610FC6A450>
index 13552: with Error cannot identify image file <_io.BytesIO object at 0x000001611158E450>
index 13553: with Error cannot identify image file <_io.BytesIO object at 0x000001610FC6A450>
index 13554: with Error cannot identify image file <_io.BytesIO object at 0x0000016111BF7BD0>
index 13556: with Error cannot identify image file <_io.BytesIO object at 0x000001611154F270>
index 13557: with Error cannot identify image file <_io.BytesIO object at 0x000001610FC6A450>
index 13558: with Error cannot identify image file <_io.BytesIO object at 0x000001611154F270>
index 13615: with Error cannot identify image file <_io.BytesIO object at 0x000001610FC6A450>
index 13754: with Error cannot identify image file <_io.BytesIO object at 0x000001611154F270>
index 13755: with Error cannot identify image file <_io.BytesIO object at 0x000001611158EC20>
index 16194: with Error cannot identify image file <_io.BytesIO object at 0x000001611153F810>
index 18824: with Error cannot identify image file <_io.BytesIO object at 0x000001610BFD83B0>
index 20559: with Error cannot identify image file <_io.BytesIO object at 0x000001610FC6A450>
index 21881: with Error cannot identify image file <_io.BytesIO object at 0x00000161115F4680>
index 21882: with Error cannot identify image file <_io.BytesIO object at 0x000001610FC6A450>
index 22779: with Error cannot identify image file <_io.BytesIO object at 0x00000161113B6C70>
index 22802: with Error cannot identify image file <_io.BytesIO object at 0x000001610B382D60>
index 22803: with Error cannot identify image file <_io.BytesIO object at 0x000001611029CE50>
index 22805: with Error cannot identify image file <_io.BytesIO object at 0x00000161115609F0>
index 22998: with Error cannot identify image file <_io.BytesIO object at 0x0000016110391680>
index 23000: with Error cannot identify image file <_io.BytesIO object at 0x000001610FC6A450>
index 23053: with Error cannot identify image file <_io.BytesIO object at 0x000001610B382D60>
index 23055: with Error cannot identify image file <_io.BytesIO object at 0x00000161115609F0>
index 23202: with Error cannot identify image file <_io.BytesIO object at 0x000001611163B450>
index 23519: with Error cannot identify image file <_io.BytesIO object at 0x000001611153F810>
index 23539: with Error cannot identify image file <_io.BytesIO object at 0x000001610BFBFE00>
index 23540: with Error cannot identify image file <_io.BytesIO object at 0x0000016111551310>
index 23542: with Error cannot identify image file <_io.BytesIO object at 0x0000016111560450>
index 23543: with Error cannot identify image file <_io.BytesIO object at 0x000001611163B450>
index 23544: with Error cannot identify image file <_io.BytesIO object at 0x000001611154F540>
index 24374: with Error cannot identify image file <_io.BytesIO object at 0x000001610C753EA0>
index 24663: with Error cannot identify image file <_io.BytesIO object at 0x000001610BFBFE00>

In [62]:
''' All leftovers yield error at the second trial '''
len(list_failed_URL)

85

## 🐔 merge to products

In [75]:
df_reviews = pd.read_feather('data/appliances_meta_012023_062023 v1.2.0.ftr')

df_photoURL = pd.read_feather('data/appliances_meta_012023_062023 v1.1.0_imgUrls.ftr')
df_photoURL_imgEmb = pd.read_csv('data/appliances_meta_012023_062023 v1.1.0_imgUrls_imgEmb.csv')

In [64]:
df_photoURL_mrgEmb = df_photoURL.merge(df_photoURL_imgEmb, on='image_url', how='left')

In [66]:
df_photoURL.shape, df_photoURL_mrgEmb.shape

((24684, 2), (24684, 514))

In [72]:
''' Average all embeddings across reviews and drop the review images that do not have embeddings '''
df_photoURL_mrgEmb_gbRv = df_photoURL_mrgEmb[df_photoURL_mrgEmb['ResNet1'].notnull()].drop(columns=['image_url']).groupby('review_id', as_index=False).mean()

In [78]:
df_reviews_mrgImgEmd = df_reviews.merge(df_photoURL_mrgEmb_gbRv, on='review_id', how='left')

In [80]:
df_reviews_mrgImgEmd.shape, df_reviews.shape

((105998, 1321), (105998, 809))

In [84]:
''' Fill NA for ResNet variabels as 0 '''
df_reviews_mrgImgEmd[df_reviews_mrgImgEmd.filter(regex='^ResNet').columns] = df_reviews_mrgImgEmd.filter(regex='^ResNet').fillna(0)

In [88]:
df_reviews_mrgImgEmd.head()

,review_id,rating,title,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,medium_image_url,medium_image_url_1,medium_image_url_2,medium_image_url_3,medium_image_url_4,medium_image_url_5,medium_image_url_6,medium_image_url_7,medium_image_url_8,medium_image_url_9,medium_image_url_10,medium_image_url_11,medium_image_url_12,medium_image_url_13,medium_image_url_14,medium_image_url_15,medium_image_url_16,medium_image_url_17,medium_image_url_18,medium_image_url_19,medium_image_url_20,medium_image_url_21,medium_image_url_22,medium_image_url_23,medium_image_url_24,medium_image_url_25,medium_image_url_26,medium_image_url_27,text_len,text_words,inter_review_time,MPN_1,MPN_2,MPN_3,MPN_4,MPN_5,MPN_6,MPN_7,MPN_8,MPN_9,MPN_10,MPN_11,MPN_12,MPN_13,MPN_14,MPN_15,MPN_16,MPN_17,MPN_18,MPN_19,MPN_20,MPN_21,MPN_22,MPN_23,MPN_24,MPN_25,MPN_26,MPN_27,MPN_28,MPN_29,MPN_30,MPN_31,MPN_32,MPN_33,MPN_34,MPN_35,MPN_36,MPN_37,MPN_38,MPN_39,MPN_40,MPN_41,MPN_42,MPN_43,MPN_44,MPN_45,MPN_46,MPN_47,MPN_48,MPN_49,MPN_50,MPN_51,MPN_52,MPN_53,MPN_54,MPN_55,MPN_56,MPN_57,MPN_58,MPN_59,MPN_60,MPN_61,MPN_62,MPN_63,MPN_64,MPN_65,MPN_66,MPN_67,MPN_68,MPN_69,MPN_70,MPN_71,MPN_72,MPN_73,MPN_74,MPN_75,MPN_76,MPN_77,MPN_78,MPN_79,MPN_80,MPN_81,MPN_82,MPN_83,MPN_84,MPN_85,MPN_86,MPN_87,MPN_88,MPN_89,MPN_90,MPN_91,MPN_92,MPN_93,MPN_94,MPN_95,MPN_96,MPN_97,MPN_98,MPN_99,MPN_100,MPN_101,MPN_102,MPN_103,MPN_104,MPN_105,MPN_106,MPN_107,MPN_108,MPN_109,MPN_110,MPN_111,MPN_112,MPN_113,MPN_114,MPN_115,MPN_116,MPN_117,MPN_118,MPN_119,MPN_120,MPN_121,MPN_122,MPN_123,MPN_124,MPN_125,MPN_126,MPN_127,MPN_128,MPN_129,MPN_130,MPN_131,MPN_132,MPN_133,MPN_134,MPN_135,MPN_136,MPN_137,MPN_138,MPN_139,MPN_140,MPN_141,MPN_142,MPN_143,MPN_144,MPN_145,MPN_146,MPN_147,MPN_148,MPN_149,MPN_150,MPN_151,MPN_152,MPN_153,MPN_154,MPN_155,MPN_156,MPN_157,MPN_158,MPN_159,MPN_160,MPN_161,MPN_162,MPN_163,MPN_164,MPN_165,MPN_166,MPN_167,MPN_168,MPN_169,MPN_170,MPN_171,MPN_172,MPN_173,MPN_174,MPN_175,MPN_176,MPN_177,MPN_178,MPN_179,MPN_180,MPN_181,MPN_182,MPN_183,MPN_184,MPN_185,MPN_186,MPN_187,MPN_188,MPN_189,MPN_190,MPN_191,MPN_192,MPN_193,MPN_194,MPN_195,MPN_196,MPN_197,MPN_198,MPN_199,MPN_200,MPN_201,MPN_202,MPN_203,MPN_204,MPN_205,MPN_206,MPN_207,MPN_208,MPN_209,MPN_210,MPN_211,MPN_212,MPN_213,MPN_214,MPN_215,MPN_216,MPN_217,MPN_218,MPN_219,MPN_220,MPN_221,MPN_222,MPN_223,MPN_224,MPN_225,MPN_226,MPN_227,MPN_228,MPN_229,MPN_230,MPN_231,MPN_232,MPN_233,MPN_234,MPN_235,MPN_236,MPN_237,MPN_238,MPN_239,MPN_240,MPN_241,MPN_242,MPN_243,MPN_244,MPN_245,MPN_246,MPN_247,MPN_248,MPN_249,MPN_250,MPN_251,MPN_252,MPN_253,MPN_254,MPN_255,MPN_256,MPN_257,MPN_258,MPN_259,MPN_260,MPN_261,MPN_262,MPN_263,MPN_264,MPN_265,MPN_266,MPN_267,MPN_268,MPN_269,MPN_270,MPN_271,MPN_272,MPN_273,MPN_274,MPN_275,MPN_276,MPN_277,MPN_278,MPN_279,MPN_280,MPN_281,MPN_282,MPN_283,MPN_284,MPN_285,MPN_286,MPN_287,MPN_288,MPN_289,MPN_290,MPN_291,MPN_292,MPN_293,MPN_294,MPN_295,MPN_296,MPN_297,MPN_298,MPN_299,MPN_300,MPN_301,MPN_302,MPN_303,MPN_304,MPN_305,MPN_306,MPN_307,MPN_308,MPN_309,MPN_310,MPN_311,MPN_312,MPN_313,MPN_314,MPN_315,MPN_316,MPN_317,MPN_318,MPN_319,MPN_320,MPN_321,MPN_322,MPN_323,MPN_324,MPN_325,MPN_326,MPN_327,MPN_328,MPN_329,MPN_330,MPN_331,MPN_332,MPN_333,MPN_334,MPN_335,MPN_336,MPN_337,MPN_338,MPN_339,MPN_340,MPN_341,MPN_342,MPN_343,MPN_344,MPN_345,MPN_346,MPN_347,MPN_348,MPN_349,MPN_350,MPN_351,MPN_352,MPN_353,MPN_354,MPN_355,MPN_356,MPN_357,MPN_358,MPN_359,MPN_360,MPN_361,MPN_362,MPN_363,MPN_364,MPN_365,MPN_366,MPN_367,MPN_368,MPN_369,MPN_370,MPN_371,MPN_372,MPN_373,MPN_374,MPN_375,MPN_376,MPN_377,MPN_378,MPN_379,MPN_380,MPN_381,MPN_382,MPN_383,MPN_384,MPN_385,MPN_386,MPN_387,MPN_388,MPN_389,MPN_390,MPN_391,MPN_392,MPN_393,MPN_394,MPN_395,MPN_396,MPN_397,MPN_398,MPN_399,MPN_400,MPN_401,MPN_402,MPN_403,MPN_404,MPN_405,MPN_406,MPN_407,MPN_408,MPN_409,MPN_410,MPN_411,MPN_412,MPN_413,MPN_414,MPN_415,MPN_416,MPN_417,MPN_418,MPN_419,MPN_420,MPN_421,MPN_422,MPN_423,MPN_424,MPN_425,MPN_426,MPN_427,MPN_428,MPN_429,MPN_430,MPN_431,MPN_432,MPN_433,MPN_434,MPN_435,MPN_436,MPN_437,MPN_438,MPN_439,MPN_440,MPN_441,MPN_442,MPN_443,MPN_444,MPN_445,MPN_446,MPN_447,MPN_448,MPN_449,MPN_450,MPN_451,MPN_452,MPN_453,MPN_454,MPN_455,MPN_456,MPN_457,MPN_458,MPN_459,MPN_460,MPN_461,MPN_462,MPN_463,MPN_464,MPN_465,MPN_466,MPN_467,MPN_468,MPN_469,MPN_470,MPN_471,MPN_472,MPN_473,MPN_474,MPN_475,MPN_476,MPN_477,MPN_478,MPN_479,MPN_480,MPN_481,MPN_482,MPN_483,MPN_484,MPN_485,MPN_486,MPN_487,MPN_488,MPN_489,MPN_490,MPN_491,MPN_492,MPN_493,MPN_494,MPN_495,MPN_496,MPN_497,MPN_498,MPN_499,MPN_500,MPN_501,MPN_502,MPN_503,MPN_504,MPN_505,MPN_506,MPN_507,MPN_508,MPN_509,MPN_510,MPN_511,MPN_512,MPN_513,MPN_514,MPN_515,MPN_516,MPN_517,MPN_518,MPN_519,MPN_520,MPN_521,MPN_522,MPN_523,MPN_524,MPN_525,MPN_526,MPN_527,MPN_528,MPN_529,MPN_530,MPN_531,MPN_532,MPN_533,MPN_534,MPN_535,MPN_536,MPN_537,MPN_538,MPN_539,MPN_540,MPN_541,MPN_542,MPN_543,MPN_544,MPN_545,MPN_546,MPN_547,MPN_548,MPN_549,MPN_550,MPN_551,MPN_552,MPN_553,MPN_554,MPN_555,MPN_556,MPN_557,MPN_558,MPN_559,MPN_560,MPN_561,MPN_562,MPN_563,MPN_564,MPN_565,MPN_566,MPN_567,MPN_568,MPN_569,MPN_570,MPN_571,MPN_572,MPN_573,MPN_574,MPN_575,MPN_576,MPN_577,MPN_578,MPN_579,MPN_580,MPN_581,MPN_582,MPN_583,MPN_584,MPN_585,MPN_586,MPN_587,MPN_588,MPN_589,MPN_590,MPN_591,MPN_592,MPN_593,MPN_594,MPN_595,MPN_596,MPN_597,MPN_598,MPN_599,MPN_600,MPN_601,MPN_602,MPN_603,MPN_604,MPN_605,MPN_606,MPN_607,MPN_608,MPN_609,MPN_610,MPN_611,MPN_612,MPN_613,MPN_614,MPN_615,MPN_616,MPN_617,MPN_618,MPN_619,MPN_620,MPN_621,MPN_622,MPN_623,MPN_624,MPN_625,MPN_626,MPN_627,MPN_628,MPN_629,MPN_630,MPN_631,MPN_632,MPN_633,MPN_634,MPN_635,MPN_636,MPN_637,MPN_638,MPN_639,MPN_640,MPN_641,MPN_642,MPN_643,MPN_644,MPN_645,MPN_646,MPN_647,MPN_648,MPN_649,MPN_650,MPN_651,MPN_652,MPN_653,MPN_654,MPN_655,MPN_656,MPN_657,MPN_658,MPN_659,MPN_660,MPN_661,MPN_662,MPN_663,MPN_664,MPN_665,MPN_666,MPN_667,MPN_668,MPN_669,MPN_670,MPN_671,MPN_672,MPN_673,MPN_674,MPN_675,MPN_676,MPN_677,MPN_678,MPN_679,MPN_680,MPN_681,MPN_682,MPN_683,MPN_684,MPN_685,MPN_686,MPN_687,MPN_688,MPN_689,MPN_690,MPN_691,MPN_692,MPN_693,MPN_694,MPN_695,MPN_696,MPN_697,MPN_698,MPN_699,MPN_700,MPN_701,MPN_702,MPN_703,MPN_704,MPN_705,MPN_706,MPN_707,MPN_708,MPN_709,MPN_710,MPN_711,MPN_712,MPN_713,MPN_714,MPN_715,MPN_716,MPN_717,MPN_718,MPN_719,MPN_720,MPN_721,MPN_722,MPN_723,MPN_724,MPN_725,MPN_726,MPN_727,MPN_728,MPN_729,MPN_730,MPN_731,MPN_732,MPN_733,MPN_734,MPN_735,MPN_736,MPN_737,MPN_738,MPN_739,MPN_740,MPN_741,MPN_742,MPN_743,MPN_744,MPN_745,MPN_746,MPN_747,MPN_748,MPN_749,MPN_750,MPN_751,MPN_752,MPN_753,MPN_754,MPN_755,MPN_756,MPN_757,MPN_758,MPN_759,MPN_760,MPN_761,MPN_762,MPN_763,MPN_764,MPN_765,MPN_766,MPN_767,MPN_768,ResNet1,ResNet2,ResNet3,ResNet4,ResNet5,ResNet6,ResNet7,ResNet8,ResNet9,ResNet10,ResNet11,ResNet12,ResNet13,ResNet14,ResNet15,ResNet16,ResNet17,ResNet18,ResNet19,ResNet20,ResNet21,ResNet22,ResNet23,ResNet24,ResNet25,ResNet26,ResNet27,ResNet28,ResNet29,ResNet30,ResNet31,ResNet32,ResNet33,ResNet34,ResNet35,ResNet36,ResNet37,ResNet38,ResNet39,ResNet40,ResNet41,ResNet42,ResNet43,ResNet44,ResNet45,ResNet46,ResNet47,ResNet48,ResNet49,ResNet50,ResNet51,ResNet52,ResNet53,ResNet54,ResNet55,ResNet56,ResNet57,ResNet58,ResNet59,ResNet60,ResNet61,ResNet62,ResNet63,ResNet64,ResNet65,ResNet66,ResNet67,ResNet68,ResNet69,ResNet70,ResNet71,ResNet72,ResNet73,ResNet74,ResNet75,ResNet76,ResNet77,ResNet78,ResNet79,ResNet80,ResNet81,ResNet82,ResNet83,ResNet84,ResNet85,ResNet86,ResNet87,ResNet88,ResNet89,ResNet90,ResNet91,ResNet92,ResNet93,ResNet94,ResNet95,ResNet96,ResNet97,ResNet98,ResNet99,ResNet100,ResNet101,ResNet102,ResNet103,ResNet104,ResNet105,ResNet106,ResNet107,ResNet108,ResNet109,ResNet110,ResNet111,ResNet112,ResNet113,ResNet114,ResNet115,ResNet116,ResNet117,ResNet118,ResNet119,ResNet120,ResNet121,ResNet122,ResNet123,ResNet124,ResNet125,ResNet126,ResNet127,ResNet128,ResNet129,ResNet130,ResNet131,ResNet132,ResNet133,ResNet134,ResNet135,ResNet136,ResNet137,ResNet138,ResNet139,ResNet140,ResNet141,ResNet142,ResNet143,ResNet144,ResNet145,ResNet146,ResNet147,ResNet148,ResNet149,ResNet150,ResNet151,ResNet152,ResNet153,ResNet154,ResNet155,ResNet156,ResNet157,ResNet158,ResNet159,ResNet160,ResNet161,ResNet162,ResNet163,ResNet164,ResNet165,ResNet166,ResNet167,ResNet168,ResNet169,ResNet170,ResNet171,ResNet172,ResNet173,ResNet174,ResNet175,ResNet176,ResNet177,ResNet178,ResNet179,ResNet180,ResNet181,ResNet182,ResNet183,ResNet184,ResNet185,ResNet186,ResNet187,ResNet188,ResNet189,ResNet190,ResNet191,ResNet192,ResNet193,ResNet194,ResNet195,ResNet196,ResNet197,ResNet198,ResNet199,ResNet200,ResNet201,ResNet202,ResNet203,ResNet204,ResNet205,ResNet206,ResNet207,ResNet208,ResNet209,ResNet210,ResNet211,ResNet212,ResNet213,ResNet214,ResNet215,ResNet216,ResNet217,ResNet218,ResNet219,ResNet220,ResNet221,ResNet222,ResNet223,ResNet224,ResNet225,ResNet226,ResNet227,ResNet228,ResNet229,ResNet230,ResNet231,ResNet232,ResNet233,ResNet234,ResNet235,ResNet236,ResNet237,ResNet238,ResNet239,ResNet240,ResNet241,ResNet242,ResNet243,ResNet244,ResNet245,ResNet246,ResNet247,ResNet248,ResNet249,ResNet250,ResNet251,ResNet252,ResNet253,ResNet254,ResNet255,ResNet256,ResNet257,ResNet258,ResNet259,ResNet260,ResNet261,ResNet262,ResNet263,ResNet264,ResNet265,ResNet266,ResNet267,ResNet268,ResNet269,ResNet270,ResNet271,ResNet272,ResNet273,ResNet274,ResNet275,ResNet276,ResNet277,ResNet278,ResNet279,ResNet280,ResNet281,ResNet282,ResNet283,ResNet284,ResNet285,ResNet286,ResNet287,ResNet288,ResNet289,ResNet290,ResNet291,ResNet292,ResNet293,ResNet294,ResNet295,ResNet296,ResNet297,ResNet298,ResNet299,ResNet300,ResNet301,ResNet302,ResNet303,ResNet304,ResNet305,ResNet306,ResNet307,ResNet308,ResNet309,ResNet310,ResNet311,ResNet312,ResNet313,ResNet314,ResNet315,ResNet316,ResNet317,ResNet318,ResNet319,ResNet320,ResNet321,ResNet322,ResNet323,ResNet324,ResNet325,ResNet326,ResNet327,ResNet328,ResNet329,ResNet330,ResNet331,ResNet332,ResNet333,ResNet334,ResNet335,ResNet336,ResNet337,ResNet338,ResNet339,ResNet340,ResNet341,ResNet342,ResNet343,ResNet344,ResNet345,ResNet346,ResNet347,ResNet348,ResNet349,ResNet350,ResNet351,ResNet352,ResNet353,ResNet354,ResNet355,ResNet356,ResNet357,ResNet358,ResNet359,ResNet360,ResNet361,ResNet362,ResNet363,ResNet364,ResNet365,ResNet366,ResNet367,ResNet368,ResNet369,ResNet370,ResNet371,ResNet372,ResNet373,ResNet374,ResNet375,ResNet376,ResNet377,ResNet378,ResNet379,ResNet380,ResNet381,ResNet382,ResNet383,ResNet384,ResNet385,ResNet386,ResNet387,ResNet388,ResNet389,ResNet390,ResNet391,ResNet392,ResNet393,ResNet394,ResNet395,ResNet396,ResNet397,ResNet398,ResNet399,ResNet400,ResNet401,ResNet402,ResNet403,ResNet404,ResNet405,ResNet406,ResNet407,ResNet408,ResNet409,ResNet410,ResNet411,ResNet412,ResNet413,ResNet414,ResNet415,ResNet416,ResNet417,ResNet418,ResNet419,ResNet420,ResNet421,ResNet422,ResNet423,ResNet424,ResNet425,ResNet426,ResNet427,ResNet428,ResNet429,ResNet430,ResNet431,ResNet432,ResNet433,ResNet434,ResNet435,ResNet436,ResNet437,ResNet438,ResNet439,ResNet440,ResNet441,ResNet442,ResNet443,ResNet444,ResNet445,ResNet446,ResNet447,ResNet448,ResNet449,ResNet450,ResNet451,ResNet452,ResNet453,ResNet454,ResNet455,ResNet456,ResNet457,ResNet458,ResNet459,ResNet460,ResNet461,ResNet462,ResNet463,ResNet464,ResNet465,ResNet466,ResNet467,ResNet468,ResNet469,ResNet470,ResNet471,ResNet472,ResNet473,ResNet474,ResNet475,ResNet476,ResNet477,ResNet478,ResNet479,ResNet480,ResNet481,ResNet482,ResNet483,ResNet484,ResNet485,ResNet486,ResNet487,ResNet488,ResNet489,ResNet490,ResNet491,ResNet492,ResNet493,ResNet494,ResNet495,ResNet496,ResNet497,ResNet498,ResNet499,ResNet500,ResNet501,ResNet502,ResNet503,ResNet504,ResNet505,ResNet506,ResNet507,ResNet508,ResNet509,ResNet510,ResNet511,ResNet512

In [89]:
df_reviews_mrgImgEmd.to_feather('data/appliances_meta_012023_062023 v1.3.0.ftr')

In [90]:
df_check = pd.read_feather('data/appliances_meta_012023_062023 v1.3.0.ftr')

In [93]:
df_check.head()

,review_id,rating,title,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,medium_image_url,medium_image_url_1,medium_image_url_2,medium_image_url_3,medium_image_url_4,medium_image_url_5,medium_image_url_6,medium_image_url_7,medium_image_url_8,medium_image_url_9,medium_image_url_10,medium_image_url_11,medium_image_url_12,medium_image_url_13,medium_image_url_14,medium_image_url_15,medium_image_url_16,medium_image_url_17,medium_image_url_18,medium_image_url_19,medium_image_url_20,medium_image_url_21,medium_image_url_22,medium_image_url_23,medium_image_url_24,medium_image_url_25,medium_image_url_26,medium_image_url_27,text_len,text_words,inter_review_time,MPN_1,MPN_2,MPN_3,MPN_4,MPN_5,MPN_6,MPN_7,MPN_8,MPN_9,MPN_10,MPN_11,MPN_12,MPN_13,MPN_14,MPN_15,MPN_16,MPN_17,MPN_18,MPN_19,MPN_20,MPN_21,MPN_22,MPN_23,MPN_24,MPN_25,MPN_26,MPN_27,MPN_28,MPN_29,MPN_30,MPN_31,MPN_32,MPN_33,MPN_34,MPN_35,MPN_36,MPN_37,MPN_38,MPN_39,MPN_40,MPN_41,MPN_42,MPN_43,MPN_44,MPN_45,MPN_46,MPN_47,MPN_48,MPN_49,MPN_50,MPN_51,MPN_52,MPN_53,MPN_54,MPN_55,MPN_56,MPN_57,MPN_58,MPN_59,MPN_60,MPN_61,MPN_62,MPN_63,MPN_64,MPN_65,MPN_66,MPN_67,MPN_68,MPN_69,MPN_70,MPN_71,MPN_72,MPN_73,MPN_74,MPN_75,MPN_76,MPN_77,MPN_78,MPN_79,MPN_80,MPN_81,MPN_82,MPN_83,MPN_84,MPN_85,MPN_86,MPN_87,MPN_88,MPN_89,MPN_90,MPN_91,MPN_92,MPN_93,MPN_94,MPN_95,MPN_96,MPN_97,MPN_98,MPN_99,MPN_100,MPN_101,MPN_102,MPN_103,MPN_104,MPN_105,MPN_106,MPN_107,MPN_108,MPN_109,MPN_110,MPN_111,MPN_112,MPN_113,MPN_114,MPN_115,MPN_116,MPN_117,MPN_118,MPN_119,MPN_120,MPN_121,MPN_122,MPN_123,MPN_124,MPN_125,MPN_126,MPN_127,MPN_128,MPN_129,MPN_130,MPN_131,MPN_132,MPN_133,MPN_134,MPN_135,MPN_136,MPN_137,MPN_138,MPN_139,MPN_140,MPN_141,MPN_142,MPN_143,MPN_144,MPN_145,MPN_146,MPN_147,MPN_148,MPN_149,MPN_150,MPN_151,MPN_152,MPN_153,MPN_154,MPN_155,MPN_156,MPN_157,MPN_158,MPN_159,MPN_160,MPN_161,MPN_162,MPN_163,MPN_164,MPN_165,MPN_166,MPN_167,MPN_168,MPN_169,MPN_170,MPN_171,MPN_172,MPN_173,MPN_174,MPN_175,MPN_176,MPN_177,MPN_178,MPN_179,MPN_180,MPN_181,MPN_182,MPN_183,MPN_184,MPN_185,MPN_186,MPN_187,MPN_188,MPN_189,MPN_190,MPN_191,MPN_192,MPN_193,MPN_194,MPN_195,MPN_196,MPN_197,MPN_198,MPN_199,MPN_200,MPN_201,MPN_202,MPN_203,MPN_204,MPN_205,MPN_206,MPN_207,MPN_208,MPN_209,MPN_210,MPN_211,MPN_212,MPN_213,MPN_214,MPN_215,MPN_216,MPN_217,MPN_218,MPN_219,MPN_220,MPN_221,MPN_222,MPN_223,MPN_224,MPN_225,MPN_226,MPN_227,MPN_228,MPN_229,MPN_230,MPN_231,MPN_232,MPN_233,MPN_234,MPN_235,MPN_236,MPN_237,MPN_238,MPN_239,MPN_240,MPN_241,MPN_242,MPN_243,MPN_244,MPN_245,MPN_246,MPN_247,MPN_248,MPN_249,MPN_250,MPN_251,MPN_252,MPN_253,MPN_254,MPN_255,MPN_256,MPN_257,MPN_258,MPN_259,MPN_260,MPN_261,MPN_262,MPN_263,MPN_264,MPN_265,MPN_266,MPN_267,MPN_268,MPN_269,MPN_270,MPN_271,MPN_272,MPN_273,MPN_274,MPN_275,MPN_276,MPN_277,MPN_278,MPN_279,MPN_280,MPN_281,MPN_282,MPN_283,MPN_284,MPN_285,MPN_286,MPN_287,MPN_288,MPN_289,MPN_290,MPN_291,MPN_292,MPN_293,MPN_294,MPN_295,MPN_296,MPN_297,MPN_298,MPN_299,MPN_300,MPN_301,MPN_302,MPN_303,MPN_304,MPN_305,MPN_306,MPN_307,MPN_308,MPN_309,MPN_310,MPN_311,MPN_312,MPN_313,MPN_314,MPN_315,MPN_316,MPN_317,MPN_318,MPN_319,MPN_320,MPN_321,MPN_322,MPN_323,MPN_324,MPN_325,MPN_326,MPN_327,MPN_328,MPN_329,MPN_330,MPN_331,MPN_332,MPN_333,MPN_334,MPN_335,MPN_336,MPN_337,MPN_338,MPN_339,MPN_340,MPN_341,MPN_342,MPN_343,MPN_344,MPN_345,MPN_346,MPN_347,MPN_348,MPN_349,MPN_350,MPN_351,MPN_352,MPN_353,MPN_354,MPN_355,MPN_356,MPN_357,MPN_358,MPN_359,MPN_360,MPN_361,MPN_362,MPN_363,MPN_364,MPN_365,MPN_366,MPN_367,MPN_368,MPN_369,MPN_370,MPN_371,MPN_372,MPN_373,MPN_374,MPN_375,MPN_376,MPN_377,MPN_378,MPN_379,MPN_380,MPN_381,MPN_382,MPN_383,MPN_384,MPN_385,MPN_386,MPN_387,MPN_388,MPN_389,MPN_390,MPN_391,MPN_392,MPN_393,MPN_394,MPN_395,MPN_396,MPN_397,MPN_398,MPN_399,MPN_400,MPN_401,MPN_402,MPN_403,MPN_404,MPN_405,MPN_406,MPN_407,MPN_408,MPN_409,MPN_410,MPN_411,MPN_412,MPN_413,MPN_414,MPN_415,MPN_416,MPN_417,MPN_418,MPN_419,MPN_420,MPN_421,MPN_422,MPN_423,MPN_424,MPN_425,MPN_426,MPN_427,MPN_428,MPN_429,MPN_430,MPN_431,MPN_432,MPN_433,MPN_434,MPN_435,MPN_436,MPN_437,MPN_438,MPN_439,MPN_440,MPN_441,MPN_442,MPN_443,MPN_444,MPN_445,MPN_446,MPN_447,MPN_448,MPN_449,MPN_450,MPN_451,MPN_452,MPN_453,MPN_454,MPN_455,MPN_456,MPN_457,MPN_458,MPN_459,MPN_460,MPN_461,MPN_462,MPN_463,MPN_464,MPN_465,MPN_466,MPN_467,MPN_468,MPN_469,MPN_470,MPN_471,MPN_472,MPN_473,MPN_474,MPN_475,MPN_476,MPN_477,MPN_478,MPN_479,MPN_480,MPN_481,MPN_482,MPN_483,MPN_484,MPN_485,MPN_486,MPN_487,MPN_488,MPN_489,MPN_490,MPN_491,MPN_492,MPN_493,MPN_494,MPN_495,MPN_496,MPN_497,MPN_498,MPN_499,MPN_500,MPN_501,MPN_502,MPN_503,MPN_504,MPN_505,MPN_506,MPN_507,MPN_508,MPN_509,MPN_510,MPN_511,MPN_512,MPN_513,MPN_514,MPN_515,MPN_516,MPN_517,MPN_518,MPN_519,MPN_520,MPN_521,MPN_522,MPN_523,MPN_524,MPN_525,MPN_526,MPN_527,MPN_528,MPN_529,MPN_530,MPN_531,MPN_532,MPN_533,MPN_534,MPN_535,MPN_536,MPN_537,MPN_538,MPN_539,MPN_540,MPN_541,MPN_542,MPN_543,MPN_544,MPN_545,MPN_546,MPN_547,MPN_548,MPN_549,MPN_550,MPN_551,MPN_552,MPN_553,MPN_554,MPN_555,MPN_556,MPN_557,MPN_558,MPN_559,MPN_560,MPN_561,MPN_562,MPN_563,MPN_564,MPN_565,MPN_566,MPN_567,MPN_568,MPN_569,MPN_570,MPN_571,MPN_572,MPN_573,MPN_574,MPN_575,MPN_576,MPN_577,MPN_578,MPN_579,MPN_580,MPN_581,MPN_582,MPN_583,MPN_584,MPN_585,MPN_586,MPN_587,MPN_588,MPN_589,MPN_590,MPN_591,MPN_592,MPN_593,MPN_594,MPN_595,MPN_596,MPN_597,MPN_598,MPN_599,MPN_600,MPN_601,MPN_602,MPN_603,MPN_604,MPN_605,MPN_606,MPN_607,MPN_608,MPN_609,MPN_610,MPN_611,MPN_612,MPN_613,MPN_614,MPN_615,MPN_616,MPN_617,MPN_618,MPN_619,MPN_620,MPN_621,MPN_622,MPN_623,MPN_624,MPN_625,MPN_626,MPN_627,MPN_628,MPN_629,MPN_630,MPN_631,MPN_632,MPN_633,MPN_634,MPN_635,MPN_636,MPN_637,MPN_638,MPN_639,MPN_640,MPN_641,MPN_642,MPN_643,MPN_644,MPN_645,MPN_646,MPN_647,MPN_648,MPN_649,MPN_650,MPN_651,MPN_652,MPN_653,MPN_654,MPN_655,MPN_656,MPN_657,MPN_658,MPN_659,MPN_660,MPN_661,MPN_662,MPN_663,MPN_664,MPN_665,MPN_666,MPN_667,MPN_668,MPN_669,MPN_670,MPN_671,MPN_672,MPN_673,MPN_674,MPN_675,MPN_676,MPN_677,MPN_678,MPN_679,MPN_680,MPN_681,MPN_682,MPN_683,MPN_684,MPN_685,MPN_686,MPN_687,MPN_688,MPN_689,MPN_690,MPN_691,MPN_692,MPN_693,MPN_694,MPN_695,MPN_696,MPN_697,MPN_698,MPN_699,MPN_700,MPN_701,MPN_702,MPN_703,MPN_704,MPN_705,MPN_706,MPN_707,MPN_708,MPN_709,MPN_710,MPN_711,MPN_712,MPN_713,MPN_714,MPN_715,MPN_716,MPN_717,MPN_718,MPN_719,MPN_720,MPN_721,MPN_722,MPN_723,MPN_724,MPN_725,MPN_726,MPN_727,MPN_728,MPN_729,MPN_730,MPN_731,MPN_732,MPN_733,MPN_734,MPN_735,MPN_736,MPN_737,MPN_738,MPN_739,MPN_740,MPN_741,MPN_742,MPN_743,MPN_744,MPN_745,MPN_746,MPN_747,MPN_748,MPN_749,MPN_750,MPN_751,MPN_752,MPN_753,MPN_754,MPN_755,MPN_756,MPN_757,MPN_758,MPN_759,MPN_760,MPN_761,MPN_762,MPN_763,MPN_764,MPN_765,MPN_766,MPN_767,MPN_768,ResNet1,ResNet2,ResNet3,ResNet4,ResNet5,ResNet6,ResNet7,ResNet8,ResNet9,ResNet10,ResNet11,ResNet12,ResNet13,ResNet14,ResNet15,ResNet16,ResNet17,ResNet18,ResNet19,ResNet20,ResNet21,ResNet22,ResNet23,ResNet24,ResNet25,ResNet26,ResNet27,ResNet28,ResNet29,ResNet30,ResNet31,ResNet32,ResNet33,ResNet34,ResNet35,ResNet36,ResNet37,ResNet38,ResNet39,ResNet40,ResNet41,ResNet42,ResNet43,ResNet44,ResNet45,ResNet46,ResNet47,ResNet48,ResNet49,ResNet50,ResNet51,ResNet52,ResNet53,ResNet54,ResNet55,ResNet56,ResNet57,ResNet58,ResNet59,ResNet60,ResNet61,ResNet62,ResNet63,ResNet64,ResNet65,ResNet66,ResNet67,ResNet68,ResNet69,ResNet70,ResNet71,ResNet72,ResNet73,ResNet74,ResNet75,ResNet76,ResNet77,ResNet78,ResNet79,ResNet80,ResNet81,ResNet82,ResNet83,ResNet84,ResNet85,ResNet86,ResNet87,ResNet88,ResNet89,ResNet90,ResNet91,ResNet92,ResNet93,ResNet94,ResNet95,ResNet96,ResNet97,ResNet98,ResNet99,ResNet100,ResNet101,ResNet102,ResNet103,ResNet104,ResNet105,ResNet106,ResNet107,ResNet108,ResNet109,ResNet110,ResNet111,ResNet112,ResNet113,ResNet114,ResNet115,ResNet116,ResNet117,ResNet118,ResNet119,ResNet120,ResNet121,ResNet122,ResNet123,ResNet124,ResNet125,ResNet126,ResNet127,ResNet128,ResNet129,ResNet130,ResNet131,ResNet132,ResNet133,ResNet134,ResNet135,ResNet136,ResNet137,ResNet138,ResNet139,ResNet140,ResNet141,ResNet142,ResNet143,ResNet144,ResNet145,ResNet146,ResNet147,ResNet148,ResNet149,ResNet150,ResNet151,ResNet152,ResNet153,ResNet154,ResNet155,ResNet156,ResNet157,ResNet158,ResNet159,ResNet160,ResNet161,ResNet162,ResNet163,ResNet164,ResNet165,ResNet166,ResNet167,ResNet168,ResNet169,ResNet170,ResNet171,ResNet172,ResNet173,ResNet174,ResNet175,ResNet176,ResNet177,ResNet178,ResNet179,ResNet180,ResNet181,ResNet182,ResNet183,ResNet184,ResNet185,ResNet186,ResNet187,ResNet188,ResNet189,ResNet190,ResNet191,ResNet192,ResNet193,ResNet194,ResNet195,ResNet196,ResNet197,ResNet198,ResNet199,ResNet200,ResNet201,ResNet202,ResNet203,ResNet204,ResNet205,ResNet206,ResNet207,ResNet208,ResNet209,ResNet210,ResNet211,ResNet212,ResNet213,ResNet214,ResNet215,ResNet216,ResNet217,ResNet218,ResNet219,ResNet220,ResNet221,ResNet222,ResNet223,ResNet224,ResNet225,ResNet226,ResNet227,ResNet228,ResNet229,ResNet230,ResNet231,ResNet232,ResNet233,ResNet234,ResNet235,ResNet236,ResNet237,ResNet238,ResNet239,ResNet240,ResNet241,ResNet242,ResNet243,ResNet244,ResNet245,ResNet246,ResNet247,ResNet248,ResNet249,ResNet250,ResNet251,ResNet252,ResNet253,ResNet254,ResNet255,ResNet256,ResNet257,ResNet258,ResNet259,ResNet260,ResNet261,ResNet262,ResNet263,ResNet264,ResNet265,ResNet266,ResNet267,ResNet268,ResNet269,ResNet270,ResNet271,ResNet272,ResNet273,ResNet274,ResNet275,ResNet276,ResNet277,ResNet278,ResNet279,ResNet280,ResNet281,ResNet282,ResNet283,ResNet284,ResNet285,ResNet286,ResNet287,ResNet288,ResNet289,ResNet290,ResNet291,ResNet292,ResNet293,ResNet294,ResNet295,ResNet296,ResNet297,ResNet298,ResNet299,ResNet300,ResNet301,ResNet302,ResNet303,ResNet304,ResNet305,ResNet306,ResNet307,ResNet308,ResNet309,ResNet310,ResNet311,ResNet312,ResNet313,ResNet314,ResNet315,ResNet316,ResNet317,ResNet318,ResNet319,ResNet320,ResNet321,ResNet322,ResNet323,ResNet324,ResNet325,ResNet326,ResNet327,ResNet328,ResNet329,ResNet330,ResNet331,ResNet332,ResNet333,ResNet334,ResNet335,ResNet336,ResNet337,ResNet338,ResNet339,ResNet340,ResNet341,ResNet342,ResNet343,ResNet344,ResNet345,ResNet346,ResNet347,ResNet348,ResNet349,ResNet350,ResNet351,ResNet352,ResNet353,ResNet354,ResNet355,ResNet356,ResNet357,ResNet358,ResNet359,ResNet360,ResNet361,ResNet362,ResNet363,ResNet364,ResNet365,ResNet366,ResNet367,ResNet368,ResNet369,ResNet370,ResNet371,ResNet372,ResNet373,ResNet374,ResNet375,ResNet376,ResNet377,ResNet378,ResNet379,ResNet380,ResNet381,ResNet382,ResNet383,ResNet384,ResNet385,ResNet386,ResNet387,ResNet388,ResNet389,ResNet390,ResNet391,ResNet392,ResNet393,ResNet394,ResNet395,ResNet396,ResNet397,ResNet398,ResNet399,ResNet400,ResNet401,ResNet402,ResNet403,ResNet404,ResNet405,ResNet406,ResNet407,ResNet408,ResNet409,ResNet410,ResNet411,ResNet412,ResNet413,ResNet414,ResNet415,ResNet416,ResNet417,ResNet418,ResNet419,ResNet420,ResNet421,ResNet422,ResNet423,ResNet424,ResNet425,ResNet426,ResNet427,ResNet428,ResNet429,ResNet430,ResNet431,ResNet432,ResNet433,ResNet434,ResNet435,ResNet436,ResNet437,ResNet438,ResNet439,ResNet440,ResNet441,ResNet442,ResNet443,ResNet444,ResNet445,ResNet446,ResNet447,ResNet448,ResNet449,ResNet450,ResNet451,ResNet452,ResNet453,ResNet454,ResNet455,ResNet456,ResNet457,ResNet458,ResNet459,ResNet460,ResNet461,ResNet462,ResNet463,ResNet464,ResNet465,ResNet466,ResNet467,ResNet468,ResNet469,ResNet470,ResNet471,ResNet472,ResNet473,ResNet474,ResNet475,ResNet476,ResNet477,ResNet478,ResNet479,ResNet480,ResNet481,ResNet482,ResNet483,ResNet484,ResNet485,ResNet486,ResNet487,ResNet488,ResNet489,ResNet490,ResNet491,ResNet492,ResNet493,ResNet494,ResNet495,ResNet496,ResNet497,ResNet498,ResNet499,ResNet500,ResNet501,ResNet502,ResNet503,ResNet504,ResNet505,ResNet506,ResNet507,ResNet508,ResNet509,ResNet510,ResNet511,ResNet512